= Atomic operations
:page-topic-type: concept

[abstract]
Besides the basic CRUD operations such as [.api]`Insert()`, [.api]`Replace()` and [.api]`Remove()`, the Couchbase SDK also supports atomic operations on a document.

The following table lists the atomic operations that are supported:

[cols="1,4"]
|===
| Name | Description

| [.api]`Increment`
| Increments the value of a key by a given delta

| [.api]`Decrement`
| Decrements the value of a key by a given delta

| [.api]`Append`
| Appends to the back of the value of a given key

| [.api]`Prepend`
| Prepends to the front of the value of a given key
|===

Increment and decrement are often used as counters for game statistics or perhaps for tallying likes or up votes in a social media application.
Here is an example of using [.api]`Increment()` and [.api]`Decrement()`:

[source,csharp]
----
 	static Cluster _cluster = new Cluster();

        static void Main(string[] args)
        {
            using (var bucket = _cluster.OpenBucket())
            {
                var key = "stats::counter1";
                Increment(bucket, key);
                Increment(bucket, key);
                Decrement(bucket, key);
                Decrement(bucket, key);
                Decrement(bucket, key);
            }
            _cluster.Dispose();
            Console.Read();
        }

        static void Increment(IBucket bucket, string key)
        {
            var result = bucket.Increment(key);
            if (result.Success)
            {
                Console.WriteLine(result.Content);
            }
        }

        static void Decrement(IBucket bucket, string key)
        {
            var result = bucket.Decrement(key);
            if (result.Success)
            {
                Console.WriteLine(result.Content);
            }
        }
----

The [.api]`Increment()` or [.api]`Decrement()` operation will return the current value of the counter key after being called.
Additional overloads allow a time-to-live (TTL) to be associated with a key and others allow you to control the delta of the increase or decrease and an optional starting point.

NOTE: The key you are incrementing or decrementing should be created by calling the [.api]`Increment()` or [.api]`Decrement()` themselves, not by using one of the other creational operations, such as [.api]`Insert()` or [.api]`Upsert()`.
The reason is that the server stores the value as the ASCII representation and not as a 64-bit integer.

Decrementing the counter will not result in a negative value, instead it will be set to zero.
Incrementing the counter might cause the counter to wrap.
