= Compatibility of Couchbase Features, Couchbase Versions and the Couchbase .NET SDK
:navtitle: Compatibility

[abstract]
Compatibility Information for the Couchbase .NET SDK

== Couchbase Version/SDK Version Matrix

Couchbase SDKs are tested against a variety of different environments to ensure both backward and forward compatibility with different versions of Couchbase Server.
The matrix below denotes the version of Couchbase Server, the version of the .NET SDK and whether the SDK is:

* ✖ *Unsupported*: This combination is not tested, and is not within the scope of technical support if you have purchased a support agreement.
* ◎ *Compatible*: This combination has been tested previously, and should be compatible.
This combination is not recommended by our technical support organization.
It is best to upgrade either the SDK or the Couchbase version you are using.
* ✔ *Supported*:This combination is subject to ongoing quality assurance, and is fully supported by our technical support organization.

.Couchbase .NET SDK and Couchbase Server Compatibility Version Matrix
[#table_sdk_versions]
|===
| _CB/SDK_ | *SDK 2.0* | *SDK 2.1, SDK 2.2, SDK 2.3, SDK 2.4* | *SDK 2.5, SDK 2.6*

| *CB 3.1*
| *◎*
| *✔*
| *✔*

| *CB 4.0 - 4.6*
| *◎*
| *✔*
| *✔*

| *CB 5.0 - 5.1*
| *◎*
| *✔*
| *✔*
|===

== Couchbase Feature Availability Matrix

.Couchbase .NET SDK and Couchbase Server Feature Availability Matrix
|===
| Server → | 2.0 | 2.5 | 3.0 | 3.1 | 4.0 | 4.1 | 4.5 | 4.6 | 5.0

10+| *Basic Features*

| CRUD Operations
9+| .NET SDK 1.3

| View Querying APIs
9+| .NET SDK 1.3

| Geospatial Views
| Not Supported
2+| Since .NET SDK 1.3
6+| Since .NET SDK 2.1

10+| *Advanced Features*

| Durability Requirements
9+| Since .NET SDK 1.3

| Carrier Publication Configuration
2+| Not Supported
7+| Since .NET SDK 1.3

| SSL Connectivity
3+| Not Supported
6+| Since .NET SDK 2.0

| Bulk Operations
9+| Since .NET SDK 2.1

| N1QL Querying
4+| Not Supported
5+| Since .NET SDK 2.2

| Multi-Dimensional Scaling
4+| Not Supported
5+| Since .NET SDK 2.2

| Sub-document API
6+| Not Supported
3+| Since .NET SDK 2.3

| Full Text Search
6+| Not Supported
3+| Since .NET SDK 2.3

| Datastructures
6+| Not Supported
3+| Since .NET SDK 2.4

| Extended Attributes
8+| Not Supported
| Since .NET SDK 2.4.4

10+| *Administrative Features*

| Administrative API
9+| Since .NET SDK 1.3

| RBAC
8+| Not Supported
| Since .NET SDK 2.5
|===

== .NET Framework Version Compatibility

The Couchbase .NET SDK is compatible with both .NET Framework 4.5 and higher for all SDK versions and .NET Core 1.0 and higher from SDK version 2.4.
Testing is completed on Windows for .NET 4.5 and .NET Core is tested on Windows, Linux and OSX.
Other .NET implementations might work but are not tested and are outside of the scope of our technical support organization.

include::6.0@sdk:shared:partial$interface-stability-pars.adoc[tag=interface-stability-section]
