= Compatibility of Couchbase Features, Couchbase Versions and the Couchbase .NET SDK
:navtitle: Compatibility
:page-aliases: overview,migrate,project-docs:compatibility,project-docs:integrations

[abstract]
Compatibility Information for the Couchbase .NET SDK

== Couchbase Version/SDK Version Matrix

Couchbase SDKs are tested against a variety of different environments to ensure both backward and forward compatibility with different versions of Couchbase Server.
The matrix below denotes the version of Couchbase Server, the version of the .NET SDK and whether the SDK is:

* ✖ *Unsupported*: This combination is not tested, and is not within the scope of technical support if you have purchased a support agreement.
* ◎ *Compatible*: This combination has been tested previously, and should be compatible.
This combination is not recommended by our technical support organization.
It is best to upgrade either the SDK or the Couchbase version you are using.
* ✔ *Supported*:This combination is subject to ongoing quality assurance, and is fully supported by our technical support organization.

.Recommended SDK per Server Version Matrix
[#table_sdk_versions]
[cols="40,25,25,20,20"]
|===
| | SDK 2.2, 2.3 | SDK 2.4, 2.5 | SDK 2.6 | SDK 2.7

| *Server 4.0-4.5*
| ◎
| *✔*
| *✔*
| *✔*

| *Server 4.6*
| ◎
| *✔*
| *✔*
| *✔*

| *Server 5.0-5.5*
| ◎
| *✔*
| *✔*
| *✔*

| *Server 6.0*
| *✖*
| *✔*
| *✔*
| *✔*

| *Server 6.5*
| *✖*
| *✖*
| *✖*
| *✔*
|===

Note the https://www.couchbase.com/support-policy[End of Life dates^] for Couchbase Server and SDK versions.
See the notes there for Support details.

== Couchbase Feature Availability Matrix

.Couchbase Server and .NET SDK Feature Availability Matrix
[cols="<25,.^23,.^24,.^18,.^19"]
|===
| | Server 4.0, 4.1 | Server 4.5, 4.6 | Server 5.x | Server 6.0, 6.5

5+| *Basic Features*

| CRUD Operations
4+| All Versions

| View Querying APIs
4+| All Versions

| Geospatial Views
4+| All Versions

5+| *Advanced Features*

| Durability Requirements
4+| Since 1.3

| Carrier Publication Configuration
4+| All Versions

| SSL Connectivity
4+| All Versions

| Bulk Operations
4+| All Versions

| N1QL Querying
4+| All Versions

| Multi-Dimensional Scaling
4+| All Versions

| Sub-document API
4+| Since 2.3

| Full Text Search
| Since 2.3 (Experimental)
3+| Since 2.4

| Global Secondary Indexes (GSI)
4+| All Versions

| Memory Optimized Indexes (MOI)
| Not Supported
3+| All SDK versions

| Plasma Storage for Indexes
2+| Not Supported
2+| All SDK versions

| FTS Index Management from the SDK
2+| Not Supported
2+| Since 2.3

| Data Structures
| Not Supported
3+| Since 2.3

| Extended Attributes
2+| Not Supported
2+| Since 2.4

| RBAC
2+| Not Supported
2+| Since 2.4

| Analytics
2+| Not supported
| DP in 5.5 with 2.6
| Since 2.7

5+| *Administrative Features*

| Administrative API
4+| All Versions
|===

== .NET Framework Version Compatibility

The Couchbase .NET SDK is compatible with .NET framework 4.5.2 on Windows.
On both Windows and Ubuntu GNU/Linux, it is tested with .NET Standard 1.5, which supports .NET Core 1.1+, and .NET Standard 2.0, which supports .NET Core 2.0+.
Other .NET implementations might work but are not tested and are outside of the scope of our technical support organization.

include::6.0@sdk:shared:partial$interface-stability-pars.adoc[tag=interface-stability-section]
