= CRUD Document Operations Using the .NET SDK with Couchbase Server
:navtitle: Document Operations
:page-topic-type: concept
:page-aliases: documents-creating,documents-updating,documents-retrieving,documents-deleting,howtos:kv-operations

You can access documents in Couchbase using methods of the [.api]`Couchbase.CouchbaseBucket` object.
The methods for retrieving documents are [.api]`Get<T>()` and [.api]`LookupIn<TDocument>()` and the methods for mutating documents are [.api]`Upsert<T>()`, [.api]`Insert<T>()`, [.api]`Replace<T>()` and [.api]`MutateIn<TDocument>()`.

Examples are shown using the synchronous methods.
See the section on xref:async-programming.adoc[Async Programming] for information on other methods.

[#net-additional-options]
== Additional options

Update operations also accept a xref:core-operations.adoc#expiry[TTL (expiry)] value ([.param]`Expiry`) on the passed [.param]`IDocument` which will instruct the server to delete the document after a given amount of time.
This option is useful for transient data (such as sessions).
By default documents do not expire.
See xref:core-operations.adoc#expiry[Expiration Overview] for more information on expiration.

Update operations can also accept a xref:concurrent-mutations-cluster.adoc[CAS] ([.param]`Cas`) value on the passed document to protect against concurrent updates to the same document.
See xref:concurrent-mutations-cluster.adoc[CAS] for a description on how to use CAS values in your application.
Since CAS values are opaque, they are normally retrieved when a Document is loaded from Couchbase and then used subsequently (without modification) on the mutation operations.
If a mutation did succeed, the returned Document will contain the new CAS value.

[#net-mutation-input]
== Document input and output types

Couchbase stores documents.
From an SDK point of view, those documents contain the actual value (like a JSON object) and associated metadata.
Every document in the Java SDK contains the following properties, some of them optional depending on the context:

|===
| Name | Description

| `Id`
| The (per bucket) unique identifier of the document.

| `Content`
| The actual content of the document.

| `Cas`
| The CAS (Compare And Swap) value of the document.

| `Expiry`
| The expiration time of the document.

| `Token`
| The optional MutationToken after a mutation.
|===

There are a few different results using `IDocument` you may encounter:

* [.api]`Document`: The default one in most methods and is backed by a JSON document when stored to Couchbase.
Commonly this is a [.api]`Document<dynamic>` object, which the API will handle automatically on behalf of your program.
* [.api]`DocumentResult`: The return type for any [.api]`IDocument` centric operation requests.
* [.api]`OperationResult<T>`: The return type for any binary operations that return a value.

Because Couchbase Server can store anything and not just JSON, there is the possibility for other implementations of the [.api]`IDocument` interface or the [.api]`IOperationResult` interface.
These are usually returned by other methods on the [.api]`Bucket` or are implemented using an [.api]`ITypeTranscoder`, which is outside the scope of this introduction.

[#net-creating-updating-full-docs]
== Creating and updating full documents

Documents may be created and updated using the [.api]`IBucket.Upsert<T>()`, [.api]`IBucket.Insert<T>()`, and [.api]`IBucket.Replace<T>()` family of methods.
Read more about the difference between these methods at xref:core-operations.adoc#crud-overview[Primitive Key-Value Operations] in the Couchbase developer guide.

These methods accept an IDocument instance where the following properties are considered if set:

* [.param]`Id` (mandatory): The ID of the document to modify (String).
* [.param]`Content` (mandatory): The desired new content of the document, this varies per document type used.
This Type of the content is specified by the generic Type T parameter.
* [.param]`Expiry` (optional): Specify the expiry time for the document.
If specified, the document will expire and no longer exist after the given number of seconds.
See xref:core-operations.adoc#expiry[Expiration Overview] for more information.
* [.param]`Cas` (optional): The CAS value for the document.
If the CAS on the server does not match the CAS supplied to the method, the operation will fail.
See xref:concurrent-mutations-cluster.adoc[Concurrent Document Mutations] for more information on the usage of CAS values.
Note that the Cas is represented here as a [.api]`UInt64`, but you should consider it an opaque value in your programs.

Other optional arguments are also available for more advanced usage:

* [.param]`TimeSpan`: A value for the [.api]`Expiry` on this document.
* [.param]`PersistTo`, [.param]`ReplicateTo`: Specify xref:durability.adoc[durability requirements] for the operations.

Upon success, the returned [.api]`IDocumentResult` instance will contain the new xref:concurrent-mutations-cluster.adoc[CAS] value of the document.
If the document is not mutated successfully, an exception is raised depending on the type of error.
Further details on the exceptional case may be on the [.param]`Exception` property of the returned [.param]`IDocumentResult`.

Inserting a document works like this:

[source,csharp]
----
var doc = new Document<dynamic>{ Id = "document_id", Content = new {Some="value"} };
var result = bucket.Insert(doc);
Console.WriteLine(JsonConvert.SerializeObject(result.Document));
----

....
Output: {"Id":"document_id","Cas":1466044876366741504,"Expiry":0,"Content":null,"Token":null}
....

If the same code is called again, a `ResponseStatus.KeyExists` will be returned.
If you don't care that the document is overridden, you can use [.api]`Upsert` instead:

[source,csharp]
----
var doc = new Document<dynamic>{ Id = "document_id", Content = new {Some="other value"} };
var result = bucket.Upsert(doc);
Console.WriteLine(JsonConvert.SerializeObject(result.Document));
----

....
Output: {"Id":"document_id","Cas":1466044876366741599,"Expiry":0,"Content":null,"Token":null}
....

Finally, a full document can be replaced if it existed before.
If it didn't exist, then a `ResponseStatus.KeyExists` will be returned:

[source,csharp]
----
var doc = new Document<dynamic>{ Id = "document_id", Content = new {Some="other value"} };
var result = bucket.Replace(doc);
Console.WriteLine(result.Status);
----

....
Output: KeyExists
....

[#net-retrieving-full-docs]
== Retrieving full documents

Documents may be retrieved using the [.api]`IBucket.Get()`, [.api]`IBucket.GetWithLock()`, [.api]`IBucket.GetAndTouch()` and [.api]``IBucket.GetFromReplica()``methods.
All of those serve different distinct purposes and accept different parameters.

Most of the time you use the [.api]`get()` method.
It accepts one mandatory argument:

* [.param]`id`: The document ID to retrieve

[source,csharp]
----
Console.WriteLine(bucket.GetDocument<dynamic>("document_id").Content);
----

....
Output: { "some": "value" }
....

It is also possible to read from a replica if you want to explicitly trade availability for consistency during the timeframe when the active partition is not reachable (for example during a node failure or netsplit).

`GetFromReplica` has one mandatory argument as well:

* [.param]`id`: The document ID to retrieve

[source,csharp]
----
var result = bucket.getFromReplica("document_id");
Console.WriteLine(result.Status);
----

IMPORTANT: Since a replica is updated asynchronously and eventually consistent, reading from it may return stale and/or outdated results!

If you need to use pessimistic write locking on a document you can use the [.param]`GetWithLock` which will retreive the document if it exists and also return its [.param]`CAS` value.
You need to provide a time that the document is maximum locked (and the server will unlock it then) if you don't update it with the valid cas.
Also note that this is a pure write lock, reading is still allowed.

[source,csharp]
----
// Get and Lock for max of 10 seconds
var ownedDoc = bucket.GetWithLock<dynamic>("document_id", new TimeSpan(0, 0, 10));

// Do something with your document
var modifiedDoc = ModfiyDocument(ownedDoc.Document);

// Write it back with the correct CAS
bucket.Replace(modifiedDoc);
----

It is also possible to fetch the document and reset its expiration value at the same time.
See xref:document-operations.adoc#net-modifying-expiration[Modifying Expiration] for more information.

[#net-removing-full-docs]
== Removing full documents

Documents may be removed using the [.api]`IBucket.Remove()` method.
This method takes a single mandatory argument:

* [.param]`id`: The ID of the document to remove.

Some additional options:

* [.param]`PersistTo`, [.param]`ReplicateTo`: Specify xref:durability.adoc[durability requirements] for the operations.
* [.param]`Timeout`: Specify a custom timeout which overrides the default timeout setting.

If the `cas` value is set on the Document overload, it is used to provide optimistic currency, very much like the `Replace` operation.

[source,csharp]
----
// Remove the document
var result = bucket.Remove("document_id");
----

[source,csharp]
----
var loaded = bucket.GetDocument<dynamic>("document_id");

// Remove and take the CAS into account
var removed = bucket.Remove(loaded);
----

[#net-modifying-expiration]
== Modifying expiraton

Modifying the xref:core-operations.adoc#expiry[Document expiration] can be performed using the [.api]`IBucket.Touch()` method.
In addition, many methods support setting the expiry value as part of their other primary operations:

* [.api]`IBucket.Touch`: Resets the expiry time for the given document ID to the value provided.
* [.api]`IBucket.GetAndTouchDocument`: Fetches the document and resets the expiry to the given value provided.
* [.api]`IBucket.Insert`, [.api]`IBucket.Upsert`, [.api]`IBucket.Replace`: Stores the expiry value alongside the actual mutation when set on the `Document<T>` instance.

The following example stores a document with an expiry, waits a bit longer and as a result no document is found on the subsequent get:

[source,csharp]
----
uint expiry = 2000; // milliseconds
var stored = bucket.Upsert(new Document<dynamic>
{
    Id = "expires",
    Expiry = expiry,
    Content = new {Some = "value"}
});

Thread.Sleep(3000);

//will be expired, thus KeyNotFound
Console.WriteLine(bucket.GetDocument<dynamic>("expires").Status);
----

....
KeyNotFound
....

You may also use the [.api]`IBucket.Touch()` method to modify expiration without fetching or modifying the document:

[source,csharp]
----
bucket.Touch("expires", TimeSpan.FromSeconds(2));
----

[#net-atomic-modifications]
== Atomic document modifications

Additional atomic document modifications can be performing using the .NET SDK.
You can increase or decrease the value of a document using the [.api]`IBucket.Increment` or  [.api]`IBucket.Decrement` methods.
You can also use the [.api]`IBucket.Append()` and [.api]`Bucket.Prepend()` methods to perform xref:core-operations.adoc#devguide_kvcore_append_prepend_generic[raw byte concatenation].

[#net-batching-ops]
== Batching Operations

The .NET SDK supports the async/await keywords so batching can easily be done by utilizing the Task.WhenAll method:

[source,csharp]
----
var tasks = new List<Task>IDocumentResult<string>>>();
ids.ForEach(x => tasks.Add(bucket.GetDocumentAsync<string>(x)));

var results = await Task.WhenAll(tasks);
results.ToList().ForEach(doc => Console.WriteLine(doc.Status));
----

In addition, there are overloads of the standard CRUD methonds on IBucket which take a list or dictionary of keys and/or documents and internally batch them asynchronously:

[source,csharp]
----
var keys = new []{"key1", "key2", "key3"};
var results = bucket.Get<dynamic>(keys).Values;
results.ToList().ForEach(x=>Console.WriteLine(x.Value));
----

The main difference between the two is that the second way will block while the results are returned (even if they are retrieved in parrallel), and the first is non-blocking from the calling thread.

[#net-subdocs]
== Operating with sub-documents

TIP: Sub-Document API is available starting Couchbase Server version 4.5.
See xref:subdocument-operations.adoc[Sub-Document Operations] for an overview.

Sub-document operations save network bandwidth by allowing you to specify _paths_ of a document to be retrieved or updated.
The document is parsed on the server and only the relevant sections (indicated by _paths_) are transferred between client and server.
You can execute xref:subdocument-operations.adoc[sub-document] operations in the .NET SDK using the [.api]`IBucket.LookupIn()` and [.api]`IBucket.MutateIn()` methods.

Each of these methods accepts a [.param]`key` as its mandatory first argument and give you a builder that you can use to chain several _command specifications_, each specifying the path to be impacted by the specified operation and a document field operand.
You may find all the operations in the [.api]`LookupInBuilder` and [.api]`MutateInBuilder` classes.

[source,csharp]
----
bucket.LookupIn("docid")
    .Get("path.to.get")
    .Exists("check.path.exists")
    .Execute();

boolean createParents = true;
bucket.MutateIn("docid")
    .Upsert("path.to.upsert", value, createParents)
    .Remove("path.to.del"))
    .Execute();
----

All sub-document operations return a special [.api]`IDocumentFragment<T>` object rather than a [.api]`IDocument<T>`.
It shares the `Id`, `Cas` and `MutationToken` fields of a document, but in contrast with a normal [.api]`IDocument<T>` object, a [.api]`IDocumentFragment<T>` object contains multiple results with multiple statuses, one result/status pair for every input operation.
So it exposes method to get the `Content()` and `Status()` of each spec, either by index or by path.
It also allows to check that a response for a particular spec `Exists()`:

[source,csharp]
----
var res =
bucket.LookupIn("docid")
    .Get("foo")
    .Exists("bar")
    .Exists("baz")
    .Execute();

// First result
res.Content("foo");

// or
res.Content(0);
----

Using the `+Content(...)+` methods will raise an exception if the individual spec did not complete successfully.
You can also use the `+Status(...)+` methods to return an error code (a [.api]`ResponseStatus`) rather than throw an exception.

[#net-formats-non-json]
== Formats and Non-JSON Documents

TIP: See xref:nonjson.adoc[Non-JSON Documents] for a general overview of using non-JSON documents with Couchbase

The .NET SDK supports documents in the form of POCOs (plain old csharp objects) as long as they are serializable (public getter/setter properties), dynamic types, and most of the representations of JSON objects from the 3rd party API's such as NewtonSoft.JSON.
In general, if the Type you are storing is an object capable of being serialized, it will be stored natively as JSON in couchbase.
Exceptions include non-JSON strings, byte arrays, and any value that is not representable as JSON.
If the value is not serializable to JSON, then it will be treated as a binary document.
Note that binary documents cannot be queried using N1QL nor do the Sub-Document methods work on them.
