= Full Text Search (FTS) Using the .NET SDK with Couchbase Server
:navtitle: Searching from the SDK
:page-aliases: howtos:full-text-searching-with-sdk

[abstract]
You can use the Full Text Search service (FTS) to create queryable full-text indexes in Couchbase Server.

Full Text Search or FTS allows you to create, manage and query full text indexes on JSON documents stored in Couchbase buckets.
It uses natural language processing for querying documents, provides relevence scoring on the results of your queries and has fast indexes for querying a wide range of possible text searches.
Some of the supported query-types include simple queries like Match and Term queries, range queries like Date Range and Numeric Range and compound queries for conjunctions, disjunctions and/or boolean queries.
The .NET SDK exposes an API for performing FTS queries which abstracts some of the complexity of using the underlying REST API.

Querying a FTS index using the .NET SDK is performed through the `Query(SearchQuery query)` method on the [.api]`CouchbaseBucket` class.
This method returns a [.api]`ISearchQueryResult` that when enumerated yields the results of the query (in the form of [.api]`ISearchQueryRow` objects).
Additionally, you can access the rows via the [.api]`Hits` property, which returns list containing all rows returned.
Other important ISearchQueryResult properties include:

* Status: a [.api]`SearchStatus` value indicating the result of the query - Success or Failed.
* Errors: a list of any errors that may have occurred
* Facets: a list of [.api]`SearchFacet` objects if any were returned

The [.api]`ISearchQueryRow` interface is implemented as a SearchQueryRow object and contains the `Index`, `Id` and `Score` properties, respectively identifying the exact FTS index that returned the hit, the id of the document that matched and a score for the match.
It also contains optional properties depending on the request and the availability of all relevant settings in the FTS mapping.
Those are:

* `Explanation`: an explanation of the plan followed by the FTS index to execute the query as a dynamic Type.
* `Locations`: a map-like listing of the location of all matching terms inside each relevant field that was queried as a dynamic Type.
* `Fragments`: a map-like listing of occurrences of the search terms in each field, with the context of the terms.
* `Fields`: a map of the complete value of each requested field).
Most of these need that the index be configured to store the data of a searched field

Here is an example of a very simple example using a [.api]`MatchQuery`, which is a very generic Full Text Search that will search within the text of the fields that were indexed:

.Querying and FTS index
[source,csharp]
----
ClusterHelper.Initialize(new ClientConfiguration());
var bucket = ClusterHelper.GetBucket("travel-sample");
var results = bucket.Query(new SearchQuery
{
    Index = "idx_travel_content",
    Query = new MatchQuery("inn"),
    SearchParams = new SearchParams().Limit(10).Timeout(TimeSpan.FromMilliseconds(10000))
});

foreach (var result in results)
{
    Console.WriteLine(result);
}
----

First we open a [.api]`CouchbaseBucket`, in this case we are opening the _"travel-sample"_ bucket which comes is a sample bucket and dataset that comes pre-installed with Couchbase server (but must be configured via the Management Console).
In the bucket, using the Management Console, we have created an index named _"idx_travel_content"_ which will index on the _"content"_ field of the _"landmark"_ document type.

We then create a high-level [.api]`SearchQuery` object with our parameters to apply to the entire request.
A [.api]`SearchQuery` can be composed of one or more queries, thus the parameters on the [.api]`SearchQuery` apply to all queries within that instance.
Here are some of the more important parameters:

* [.api]`Limit`: limits the number of matching results from a returned result-set by _"n"_.
* [.api]`Skip`: indicates how many matching results to skip on the result set before returning matches.
* [.api]`Explain`: if true, the response will include additional search score explanations.
* [.api]`Highlighting`: allows setting of additional highlighting on the result set of matching terms.
* [.api]`Fields`: a list of fields values that should be returned in the result assuming that they were indexed.
* [.api]`Facets`: a list of facets used to aggregate information collected on a particluar result set.
* [.api]`Timeout`: a server side timeout allows to specify an upper boundary of request execution so that it potentially doesn't run infinitely.

The [.api]`SearchQuery` is a "fluent" interface, so you can chain method calls togather making it a bit easier to see which options you have available using IntelliSense in Visual Studio.
The index we defined above _"idx_travel_content"_ is assigned to the Index property and the MatchQuery is defined, which will search for the letters _"inn"_ in the _"content"_ field of every _"landmark"_ document in the _"travel-sample"_ bucket.

We then call the [.api]`CouchbaseBucket.Query(SearchQuery query)` method and iterate over the [.api]`ISearchQueryResult` object which will gives the results of the query.

[#dotnet-fts-detailed-example]
== Detailed Example

The following example demonstrates Full Text Search queries that can be made with the .NET SDK.

[source,csharp]
----
static void Main(string[] args)
{
    // Access the cluster that is running on the local host, authenticating with
    // the username and password of any user who has the "FTS Searcher" role
    // for the "travel-sample" bucket...
    //

    var config = new ClientConfiguration
    {
        Servers = new List<Uri> {new Uri("couchbase://localhost")}
    };

    using (var cluster = new Cluster(config))
    {
        cluster.Authenticate("Administrator", "password");

        var travelSample = cluster.OpenBucket("travel-sample");
        SimpleTextQuery(travelSample);
        SimpleTextQueryOnStoredField(travelSample);
        SimpleTextQueryOnNonDefaultIndex(travelSample);
        TextQueryOnStoredFieldWithFacet(travelSample);
        DocIdQueryMethod(travelSample);
        UnAnalyzedTermQuery(travelSample, 0);
        UnAnalyzedTermQuery(travelSample, 2);
        MatchPhraseQueryOnStoredField(travelSample);
        UnAnalyzedPhraseQuery(travelSample);
        ConjunctionQueryMethod(travelSample);
        QueryStringMethod(travelSample);
        WildCardQueryMethod(travelSample);
        NumericRangeQueryMethod(travelSample);
        RegexpQueryMethod(travelSample);
    }
}

public static void SimpleTextQuery(IBucket bucket)
{
    var query = new SearchQuery
        {
            Index = "travel-sample-index-unstored",
            Query = new MatchQuery("swanky")
        }
        .Limit(10);
    var result = bucket.Query(query);

    PrintResult("Simple Text Query", result);
}

public static void SimpleTextQueryOnStoredField(IBucket bucket)
{
    var query = new SearchQuery
        {
            Index = "travel-sample-index-stored",
            Query = new MatchQuery("MDG").Field("destinationairport")
        }
        .Limit(10);

    var result = bucket.Query(query);

    PrintResult("Simple Text Query on Stored Field", result);
}

public static void SimpleTextQueryOnNonDefaultIndex(IBucket bucket)
{
    var query = new SearchQuery
        {
            Index = "travel-sample-index-hotel-description",
            Query = new MatchQuery("swanky")
        }
        .Limit(10);

    var result = bucket.Query(query);

    PrintResult("Simple Text Query on Non-Default Index", result);
}

public static void TextQueryOnStoredFieldWithFacet(IBucket bucket)
{
    var query = new SearchQuery
        {
            Index = "travel-sample-index-stored",
            Query = new MatchQuery("La Rue Saint Denis!!").Field("reviews.content")
        }
        .Limit(10)
        .Highlighting(HighLightStyle.Ansi)
        .Facets(new TermFacet("Countries Referenced", "country", 5));

    var result = bucket.Query(query);

    PrintResult("Match Query with Facet, Result by Row", result);

    Console.WriteLine();
    Console.WriteLine("Match Query with Facet, Result by hits:");
    Console.WriteLine(result.Hits);

    Console.WriteLine();
    Console.WriteLine("Match Query with Facet, Result by facet: ");
    Console.WriteLine(result.Facets);
}

public static void DocIdQueryMethod(IBucket bucket)
{
    var query = new SearchQuery
    {
        Index = "travel-sample-index-unstored",
        Query = new DocIdQuery("hotel_26223", "hotel_28960")
    };

    var result = bucket.Query(query);

    PrintResult("DocId Query", result);
}

public static void UnAnalyzedTermQuery(IBucket bucket, int fuzzinessLevel)
{
    var query = new SearchQuery
        {
            Index = "travel-sample-index-stored",
            Query = new TermQuery("sushi").Field("reviews.content").Fuzziness(fuzzinessLevel)
        }
        .Limit(50)
        .Highlighting(HighLightStyle.Ansi);

    var result = bucket.Query(query);

    PrintResult("Unanalyzed Term Query with Fuzziness Level of "
        + fuzzinessLevel + ":", result);
}

public static void MatchPhraseQueryOnStoredField(IBucket bucket)
{
    var query = new SearchQuery
        {
            Index = "travel-sample-index-stored",
            Query = new MatchQuery("Eiffel Tower").Field("description")
        }
        .Limit(10)
        .Highlighting(HighLightStyle.Ansi);

    var result = bucket.Query(query);

    PrintResult("Match Phrase Query, using Analysis", result);
}

public static void UnAnalyzedPhraseQuery(IBucket bucket)
{
    var query = new SearchQuery
        {
            Index = "travel-sample-index-stored",
            Query = new PhraseQuery("dorm", "rooms").Field("description")
        }
        .Limit(10)
        .Highlighting(HighLightStyle.Ansi);

    var result = bucket.Query(query);

    PrintResult("Phrase Query, without Analysis", result);
}

public static void ConjunctionQueryMethod(IBucket bucket)
{
    var query = new SearchQuery
        {
            Index = "travel-sample-index-stored",
            Query = new ConjunctionQuery(
                new MatchQuery("La Rue Saint Denis!!").Field("reviews.content"),
                new MatchQuery("boutique").Field("description")
            )
        }
        .Limit(10)
        .Highlighting(HighLightStyle.Ansi);

    var result = bucket.Query(query);

    PrintResult("Conjunction Query", result);
}

public static void QueryStringMethod(IBucket bucket)
{
    var query = new SearchQuery
        {
            Index = "travel-sample-index-unstored",
            Query = new QueryStringQuery("description: Imperial")
        }
        .Limit(10);

    var result = bucket.Query(query);

    PrintResult("Query String Query", result);
}

public static void WildCardQueryMethod(IBucket bucket)
{
    var query = new SearchQuery
        {
            Index = "travel-sample-index-stored",
            Query = new WildcardQuery("bouti*ue").Field("description")
        }
        .Limit(10)
        .Highlighting(HighLightStyle.Ansi);

    var result = bucket.Query(query);

    PrintResult("Wild Card Query", result);
}

public static void NumericRangeQueryMethod(IBucket bucket)
{
    var query = new SearchQuery
        {
            Index = "travel-sample-index-unstored",
            Query = new NumericRangeQuery().Min(10100).Max(10200).Field("id")
        }
        .Limit(10);

    var result = bucket.Query(query);

    PrintResult("Numeric Range Query", result);
}

public static void RegexpQueryMethod(IBucket bucket)
{
    var query = new SearchQuery
        {
            Index = "travel-sample-index-stored",
            Query = new RegexpQuery("[a-z]").Field("description")
        }
        .Limit(10)
        .Highlighting(HighLightStyle.Ansi);

    var result = bucket.Query(query);

    PrintResult("Regexp Query", result);
}

private static void PrintResult(string label, ISearchQueryResult resultObject)
{
    Console.WriteLine();
    Console.WriteLine("= = = = = = = = = = = = = = = = = = = = = = =");
    Console.WriteLine("= = = = = = = = = = = = = = = = = = = = = = =");
    Console.WriteLine();
    Console.WriteLine(label);
    Console.WriteLine();

    foreach (var row in resultObject)
    {
        Console.WriteLine(row);
    }
}
----
