= Managing Clusters Using the .NET SDK with Couchbase Server
:navtitle: Managing Clusters

[abstract]
The Couchbase .NET SDK provides an API for managing a Couchbase cluster programmatically: list, configure and create buckets, get cluster information, manipulate nodes in a cluster\...

include::4.5@sdk:shared:partial$flush-info-pars.adoc[tag=management-intro]

The .NET SDK also comes with some convenience functionality for common Couchbase management requests.

Management operations in the .NET SDK may be performed through several interfaces depending on the object:

* [.api]`ClusterProvisioner` class which encapsulates some of the complexity of creating a cluster.
* [.api]`ClusterManager` class (obtained via [.api]`ICluster.CreateManager(string, string)` with the administrative username and password).
* [.api]`BucketManager` class (obtained via [.api]`IBucket.CreateManager(string, string)` with the bucket name/password or administrative username and password).

== Getting Information About the Cluster

When you call `ClusterManager.ClusterInfo()`, the `Result<>` it returns is an `IClusterInfo` object that contains typed information about the general status and configuration of the cluster (as a [.api]`Pools` object) and the configuration of all the buckets (as a [.api]`List<IBucketConfig>`).

== Creating and Removing Buckets

The [.api]`ClusterManager` class may be used to create and delete buckets from the Couchbase cluster.
It is instantiated through the [.api]``Cluster``'s [.api]`CreateManager` method, providing the administrative username and password.

[source,csharp]
----
Cluster cluster = new Cluster();
ClusterManager clusterManager = cluster.CreateManager("Administrator", "123456");
----

To create a bucket, use the [.api]`ClusterManager#CreateBucket(string)` method.
The method has additional parameters that each have a default value, but can be set explicitly in order to use a custom value.

Only [.param]`name` parameter is mandatory.
Here is the list of parameters available:

* [.param]`name`: The name of the bucket (mandatory to create one, cannot be updated).
* [.param]`bucketType`: The type of the bucket (mandatory to create one, cannot be changed).
Defaults to `BucketTypeEnum.Couchbase`, but can also be `BucketTypeEnum.Memcached` to create a cache bucket.
* [.param]`ramQuota`: How much memory should each node use for the bucket.
This number is specified in megabytes.
* [.param]`saslPassword`: If specified, makes this bucket password protected, forcing future connects (using the [.api]`Bucket`) class to specify the [.param]`password` parameter.
* [.param]`flushEnabled`: Enables the [.api]`BucketManager.Flush()` operation to be performed on this bucket (see the <<flushing>> section below).
* [.param]`replicaNumber`: The number of replicas to use for the bucket as a [.api]`ReplicaNumber` enum.
* [.param]`indexReplicas`: Whether or not to replicate indexes.
* [.param]`parallelDbAndViewCompaction`: Indicates whether database and view files on disk can be compacted simultaneously.
* [.param]`threadNumber`: Integer from 2 to 8.
Change the number of concurrent readers and writers for the data bucket.

The following example creates a "new_bucket" password-protected bucket:

[source,csharp]
----
manager.CreateBucket("new_bucket",
    bucketType: BucketTypeEnum.Couchbase,
    saslPassword: "s3cr3t",
    ramQuota: 120, // megabytes
    replicaNumber: ReplicaNumber.TWO,
    indexReplicas: true,
    flushEnabled: true);
----

Once you no longer need to use the bucket, you may delete the bucket using the [.api]`ClusterManager.RemoveBucket(string)` method:

[source,csharp]
----
clusterManager.RemoveBucket("new_bucket");
----

[#flushing]
== Flushing Buckets

include::4.5@sdk:shared:partial$flush-info-pars.adoc[tag=flush-intro]

You may flush a bucket in the .NET SDK by using the [.api]`BucketManager.Flush()` method:

----
bucket.CreateManager("new_bucket", "s3cr3t").Flush()
----

The [.api]`Flush` operation may fail if the bucket does not have flush enabled, returning an error [.api]`IResult` .

== N1QL Index Management

include::4.5@sdk:shared:partial$flush-info-pars.adoc[tag=index-management]

You can manage indexes in the .NET SDK using the [.api]`BucketManager` class, with its various N1QL related methods: [.api]`ListN1qlIndexes()`, [.api]`+CreateN1qlIndex(...)+`, etc\...

The following example creates a N1QL secondary index named "fooBar" on the "test" bucket, indexing fields "foo" and "bar":

[source,csharp]
----
//getting the bucket manager is omitted
testManager.CreateN1qlIndex("fooBar", defer: false, "foo", "bar");
----

Note that the methods return an [.api]`IResult`, which could represent a failure notably if the index you attempt to create already exists (or when attempting to delete an index that doesn't exist).

== View Management

include::4.5@sdk:shared:partial$flush-info-pars.adoc[tag=view-management]

In the .NET SDK, design documents are simply represented as a `string`, the JSON representation of the design document.
All operations on design documents are performed on a `IBucketManager` instance.

To inspect design documents, you can either retrieve them by name (`bucketManager.GetDesignDocument("landmarks")`) or iterate through a list of documents (`bucketManager.GetDesignDocuments()`).
The later can include design documents that are still in _development mode_ (that is, running only on a small fraction of the documents) by using the [.param]`includeDevelopment` parameter.

To create or update design documents, use the [.api]`InsertDesignDocument(string, string)` and [.api]`UpdateDesignDocument(string, string)` methods.

The following example inserts a design document with two regular views and one spatial view into a bucket named `travel-sample`:

[source,csharp]
----
//shortcut for the purpose of this snippet only
BucketManager bucketManager = new Cluster().OpenBucket("travel-sample").CreateManager("travel-sample", "");

// the design document string
string designDoc = "{"
 + "    \"views\": {"
 + "        \"by_country\": {"
 + "            \"map\": \"function (doc, meta) { if (doc.type == 'landmark') { emit([doc.country, doc.city], null); } }\""
 + "        }, \"by_activity\": {"
 + "            \"map\": \"function (doc, meta) { if (doc.type == 'landmark') { emit(doc.activity, null); } }\","
 + "            \"reduce\": \"_count\""
 + "        }"
 + "    }, \"spatialViews\": {"
 + "        \"by_coordinates\": {"
 + "            \"map\": \"function (doc, meta) { if (doc.type == 'landmark') { emit([doc.geo.lon, doc.geo.lat], null); } }\""
 + "        }"
 + "    }"
 + "}";

// Insert design document into the bucket
bucketManager.InsertDesignDocument("landmarks", designDoc);
----

include::4.5@sdk:shared:partial$flush-info-pars.adoc[tag=one-view-update-warning]

To remove a design document from a bucket, pass its name to the `RemoveDesignDocument` method.

== Using the ClusterProvisioner to Create a Whole Cluster

Alternatively to the methods exposed above for dealing with buckets creation, the .NET SDK offers a [.api]`ClusterProvisioner` API that can also create buckets, but goes a little bit beyond as it can be used to provision an entire cluster, including adding/removing nodes.

[NOTE]
====
In order to follow this example, you will need to provision the nodes that will make up the Couchbase cluster.
These can be any supported OS, but each must have Couchbase Server installed and the basic networking done so that they can communicate to each other over common networking protocols such as TCP and HTTP.

In this example, we will use Vagrant, Puppet and the "vagrants" project found here: https://github.com/couchbaselabs/vagrants to provision a cluster.
Additional steps for installing Puppet, Vagrant and VirtualBox can be found here: http://nitschinger.at/A-Couchbase-Cluster-in-Minutes-with-Vagrant-and-Puppet

Once the nodes are provisioned, we can continue with the rest of the example.
====

Using the IP's of your nodes that have been provisioned, the client can bootstrap to the entry-point or "EP" node.
This done either through a configuration object or through the App.config or Web.config (for ASP.NET projects).
In this example we will use a ClientConfiguration object to programmatically create a configuration and bootstrap to the EP node:

[source,csharp]
----
var config = new ClientConfiguration
{
    Servers = new List<Uri>
    {
        new Uri("http://192.168.77.101:8091/"),
        new Uri("http://192.168.77.102:8091/"),
        new Uri("http://192.168.77.103:8091/"),
        new Uri("http://192.168.77.104:8091/")
    }
};

var cluster = new Cluster(config);
var provisioner = new ClusterProvisioner(cluster, "Administrator", "password");
var results = await provisioner.ProvisionEntryPointAsync();
foreach (var res in results.Results)
{
    Console.WriteLine(res.Message);
}
----

In this example, you create a [.api]`ClientConfiguration` and specify the URI's for each of the four nodes you provisioned in the previous step.
The entry-point node or EP node will be the first node in the list.
You then create a [.api]`Cluster` object passing in the [.api]`ClientConfiguration` and then create a [.api]`ClusterProvisioner` object passing in the Cluster references and the user and password.
Then we call `ProvisionEntryPointAsync()` which will create an EP node from the first URI in the [.param]`Servers` list that has a "default" Couchbase (persistent) bucket.
The password and username will be the administrative password and since we are using the defaults, all three services (data, query, and index) will be enabled.
Finally we output the results.

Next you will optionally add two sample buckets: travel-sample and beer-sample.

[source,csharp]
----
var result = await provisioner.ProvisionSampleBucketAsync("beer-sample");
Console.WriteLine(result.Message);

var result = await provisioner.ProvisionSampleBucketAsync("travel-sample");
Console.WriteLine(result.Message);
----

Once again optionally, you may want to *add additional buckets*.
In this case we will add a SASL authenticated Couchbase bucket and a MemcachedBucket:

[source,csharp]
----
var result = await provisioner.ProvisionBucketAsync(new BucketSettings
{
    Name = "authenticated",
    SaslPassword = "secret",
    AuthType = AuthType.Sasl,
    BucketType = BucketTypeEnum.Couchbase
});
Console.WriteLine(result.Message);
----

As you can see the provisioner uses a [.api]`BucketSettings` object rather than named method parameter to define options.
The name of the bucket is "authenticated", the password is "secret", and the [.param]`BucketType` is Couchbase, so this will create a persistent bucket.

[source,csharp]
----
var result = await provisioner.ProvisionBucketAsync(new BucketSettings
{
    Name = "memcached",
    SaslPassword = "",
    AuthType = AuthType.Sasl,
    BucketType = BucketTypeEnum.Memcached
});
Console.WriteLine(result.Message);
----

The name of the bucket is "memcached" with no password and the [.param]`BucketType` is Memcached, so this will create an in-memory bucket.

*Adding nodes to the cluster*: Once you have provisioned and bootstrapped to an EP node, you can add nodes to create a cluster.
In order to do this, the [.api]`ClusterProvisioner` object created earlier will be used to add the rest of the nodes defined in the [.api]`ClientConfiguration` in the first step (102, 103, and 104).

[source,csharp]
----
var results = await provisioner.ProvisionNodesAsync(
    CouchbaseService.Index,
    CouchbaseService.KV,
    CouchbaseService.N1QL);
----

This will provision the rest of the nodes in the ClientConfiguration.
If you want finer grained control of which services are enabled on each node, you can you use [.api]`ProvisionNodeAsync`.
[.api]`ProvisionNodeAsync` provisions a single node.
