= Overview
:page-topic-type: concept

[abstract]
The Couchbase .NET SDK 2.0 is the official .NET client library for Couchbase Server.
Written entirely in the C# programming language, it targets .NET Framework 4.5 and later and Couchbase Server 2.5 and later.

== Compatibility

To take advantage of all features offered by Couchbase Server, you need to know what version of the SDK provides compatibility for the features you want to use.
The following matrix shows which versions of the SDK support the major features of each version of Couchbase Server.

.Couchbase Server and SDK Supported Feature Matrix
|===
| ^| Server 1.8 ^| Server 2.0 ^| Server 2.5 ^| Server 3.0 ^| Server 4.0

6+| *Basic Features*

| K/V Operations
^| 1.0
^| 1.0
^| 1.0/2.0
^| 1.0/2.0
^| 1.0/2.0

| View API
^| -
^| 1.0
^| 1.0/2.0
^| 1.0/2.0
^| 1.0/2.0

6+| *Advanced Features*

| N1QL API
^| -
^| -
^| -
^| 2.0
^| 2.0

| Document API
^| -
^| -
^| 2.0
^| 2.0
^| 2.0

| Durability Requirements
^| -
^| 1.0
^| 1.0/2.0
^| 1.0/2.0
^| 1.0/2.0

| SSL
^| -
^| -
^| -
^| 2.0
^| 2.0

| CRAM MD5 Auth
^| -
^| -
^| -
^| 2.0
^| 2.0

| Bulk Operations
^| 1.0
^| 1.0
^| 1.0/2.0
^| 1.0/2.0
^| 1.0/2.0

| CCCP (fast bootstrapping)
^| -
^| -
^| 2.0
^| 2.0
^| 2.0

6+| *Administrative Features*

| Admin API
^| -
^| 1.0
^| 1.0/2.0
^| 1.0/2.0
^| 2.0
|===

== SSL/TLS Support

The .NET SDK supports the same protocols that Couchbase Server supports, and this is as follows:

* .NET Framework before 4.6: TLS 1.0 or TLS 1.1 (poodle-safe)
* .NET Framework 4.6 or after: TLS 1.0, TLS 1.1, or TLS 1.2
* .NET SDK version 1.0 does not support SSL, which was introduced in Version 2.0.
Therefore, Couchbase Server 2.5 and later support .NET SDK 2.0 and SSL/TLS as explained.
