= Tutorial
:page-topic-type: concept

The travel-sample application takes over where the xref:hello-couchbase.adoc[Hello Couchbase tutorial] ends and provides a comprehensive application blueprint for developing Couchbase applications using the Microsoft .NET Framework.
The sample application demonstrates the best practices that have emerged for developing highly scalable, robust Internet applications with Couchbase.

You can find the complete code for the https://github.com/couchbaselabs/try-cb-dotnet[Couchbase Travel Sample] on GitHub.

== Prerequisites

* Microsoft Visual Studio 2013
* Couchbase Server 4.0 or later installed locally (you can always use a remote cluster, you'll just have to configure your application accordingly)
* NuGet Package Manager 2.0 or later

NOTE: Other versions of Visual Studio or NuGet might work, but this tutorial has not been tested with them.

== Travel-sample tutorial steps

The sample application is in it’s final completed form in the master branch: https://github.com/couchbaselabs/try-cb-dotnet[]

There are several stages to the tutorial.

* Part 1: Create basic static returns for the data we expect to return in the future: https://github.com/couchbaselabs/try-cb-dotnet/tree/tutorial-part-1[]
* Part 2: Add basic lookups when an airport FAA code is requested: https://github.com/couchbaselabs/try-cb-dotnet/tree/tutorial-part-2[]
* Part 3: Extend the basic lookup to handle the lookup of an ICAO request: https://github.com/couchbaselabs/try-cb-dotnet/tree/tutorial-part-3[]
* Part 4: Add a LINQ based lookup of the flight details: https://github.com/couchbaselabs/try-cb-dotnet/tree/tutorial-part-4[]
* Part 5: Complete app: https://github.com/couchbaselabs/try-cb-dotnet/tree/tutorial-part-5[]
