= Distributed Transactions from the .NET SDK
:description: A practical guide to using Couchbase's distributed ACID transactions, via the .NET API.
:navtitle: ACID Transactions
:page-topic-type: howto
:page-aliases: acid-transactions.adoc
:page-toclevels: 2

include::project-docs:partial$attributes.adoc[]
include::partial$acid-transactions-attributes.adoc[]

[abstract]
{description}


include::{version-server}@sdk:shared:partial$acid-transactions.adoc[tag=intro]


Below we show you how to create Transactions, step-by-step.
You may also want to start with our https://github.com/couchbaselabs/couchbase-transactions-dotnet-examples[transactions examples repository],
which features useful downloadable examples of using Distributed Transactions.

API Docs are available https://docs.couchbase.com/sdk-api/couchbase-transactions-dotnet/[online].


== Requirements

* Couchbase Server 6.6.2 or above.
* Couchbase .NET client 3.2.3 or above.
It is recommended you use the package on NuGet.
include::{version-server}@sdk:shared:partial$acid-transactions.adoc[tag=requirements]


== Getting Started

Couchbase transactions require no additional components or services to be configured.
Simply add the transactions library into your project.
Version 1.1.0 was release October 29th, 2021.
See the xref:project-docs:distributed-transactions-dotnet-release-notes.adoc[Release Notes] for the latest version.

With NuGut this can be accomplished by using the NuGet Package Manager in your IDE:

[source]
----
PM > Install-Package Couchbase.Transactions -Version 1.1.0
----

Or via the CLI

[source]
----
dotnet add package Couchbase.Transactions --version 1.1.0
----

Or by using PackageReference in your .csproj file:

[source]
----
<PackageReference Include="Couchbase.Transactions" Version="1.1.0" />
----

A complete simple NuGet example is available on our https://github.com/couchbaselabs/couchbase-transactions-dotnet-examples[transactions examples repository].


== Initializing Transactions

Here are all imports used by the following examples:

[source,csharp]
----
include::example$TransactionsExample.cs[tag=imports,indent=0]
----

The starting point is the `Transactions` object.
It is very important that the application ensures that only one of these is created per cluster, as it performs automated background clean-up processes that should not be duplicated.
In dependency injection context, this instance should be injected as a singleton.

[source,csharp]
----
include::example$TransactionsExample.cs[tag=init,indent=0]
----

=== Multiple Transactions Objects

Generally an application will need just one `Transactions` object, and in fact the library will usually warn if more are created.
Each `Transactions` object uses some resources, including a thread-pool.

There is one rare exception where an application may need to create multiple `Transactions` objects, which is covered in <<Custom Metadata Collections>>.

== Configuration

Transactions can optionally be configured at the point of creating the `Transactions` object:

[source,csharp]
----
include::example$TransactionsExample.cs[tag=config,indent=0]
----

include::{version-server}@sdk:shared:partial$acid-transactions.adoc[tag=config]


include::{version-server}@sdk:shared:partial$acid-transactions.adoc[tag=creating]

As with the Couchbase .NET Client, you should use the library asynchronusly using the async/await keywords (the exceptions will be explained later in <<Error Handling>>):

[source,csharp]
----
include::example$TransactionsExample.cs[tag=create,indent=0]
----

The asynchronous API allows you to use the thread pool, which can help you scale with excellent efficiency.
However, operations inside an individual transaction should be kept in-order and executed using `await` immediately.
Do not use fire-and-forget tasks under any circumstances.

include::{version-server}@sdk:shared:partial$acid-transactions.adoc[tag=lambda-ctx]

// Examples
include::{version-server}@sdk:shared:partial$acid-transactions.adoc[tag=examples-intro]

[source,csharp]
----
include::example$TransactionsExample.cs[tag=examples,indent=0]
----

include::{version-server}@sdk:shared:partial$acid-transactions.adoc[tags=mechanics;!integrated-sdk-cleanup-process]


== Key-Value Mutations

=== Replacing

Replacing a document requires awaiting a `TransactionGetResult` returned from `ctx.GetAsync()`, `ctx.InsertAsync()`, or another `ctx.ReplaceAsync()` call first.
This is necessary to ensure that the document is not involved in another transaction.
(If it is, then the transaction will handle this, generally by rolling back what has been done so far, and retrying the lambda.)

[source,csharp]
----
include::example$TransactionsExample.cs[tag=replace,indent=0]
----

=== Removing

As with replaces, removing a document requires awaiting a `TransactionGetResult` from a previous transaction operation first.

[source,csharp]
----
include::example$TransactionsExample.cs[tag=remove,indent=0]
----

=== Inserting

[source,csharp]
----
include::example$TransactionsExample.cs[tag=insert,indent=0]
----

== Key-Value Reads

There are two ways to get a document, `GetAsync` and `GetOptionalAsync`:

[source,csharp]
----
include::example$TransactionsExample.cs[tag=get,indent=0]
----

`GetAsync` will cause the transaction to fail with `TransactionFailedException` (after rolling back any changes, of course).
It is provided as a convenience method so the developer does not have to check for `null` if the document must exist for the transaction to succeed.

Gets will 'read your own writes', e.g. this will succeed:

[source,csharp]
----
include::example$TransactionsExample.cs[tag=getReadOwnWrites,indent=0]
----


include::{version-server}@sdk:shared:partial$acid-transactions.adoc[tags=query-intro;!integrated-sdk-begin-transaction]

=== Using N1QL

If you already use N1QL from the .NET SDK, then its use in transactions is very similar.
It returns the same `IQueryResult<T>` you are used to, and takes most of the same options.

You must take care to write `ctx.QueryAsync()` inside the lambda however, rather than `cluster.QueryAsync()` or `scope.QueryAsync()`.

An example of selecting some rows from the `travel-sample` bucket:

[source,csharp]
----
include::example$TransactionsExample.cs[tag=queryExamplesSelect,indent=0]
----

Rather than specifying the full "`travel-sample`.inventory.hotel" name each time, it is easier to pass a reference to the inventory `IScope`:

[source,csharp]
----
include::example$TransactionsExample.cs[tag=queryExamplesSelectScope,indent=0]
----

An example using a `IScope` for an UPDATE:

[source,csharp]
----
include::example$TransactionsExample.cs[tag=queryExamplesUpdate,indent=0]
----

And an example combining SELECTs and UPDATEs.
It's possible to call regular C# methods from the lambda, as shown here, permitting complex logic to be performed.
Just remember that since the lambda may be called multiple times, so may the method.

[source,csharp]
----
include::example$TransactionsExample.cs[tag=queryExamplesComplex,indent=0]
----

=== Read Your Own Writes

As with Key-Value operations, N1QL queries support Read Your Own Writes.

This example shows inserting a document and then selecting it again.

[source,csharp]
----
include::example$TransactionsExample.cs[tag=queryInsert,indent=0]
----

<1> The inserted document is only staged at this point. as the transaction has not yet committed.
Other transactions, and other non-transactional actors, will not be able to see this staged insert yet.
<2> But the SELECT can, as we are reading a mutation staged inside the same transaction.

=== Mixing Key-Value and N1QL

Key-Value operations and queries can be freely intermixed, and will interact with each other as you would expect.

In this example we insert a document with Key-Value, and read it with a SELECT.
[source,csharp]
----
include::example$TransactionsExample.cs[tag=queryRyow,indent=0]
----
<1> As with the 'Read Your Own Writes' example, here the insert is only staged, and so it is not visible to other transactions or non-transactional actors.
<2> But the SELECT can view it, as the insert was in the same transaction.

=== Query Options

Query options can be provided via `TransactionQueryOptions`, which provides a subset of the options in the .NET SDK's `QueryOptions`.

[source,csharp]
----
include::example$TransactionsExample.cs[tag=queryOptions,indent=0]
----

The supported options are:

* Parameter
* ScanConsistency
* FlexIndex
* Serializer
* ClientContextId
* ScanWait
* ScanCap
* PipelineBatch
* PipelineCap
* Readonly
* AdHoc
* Raw

See the xref:howtos:n1ql-queries-with-sdk.adoc#query-options[QueryOptions documentation] for details on these.

include::{version-server}@sdk:shared:partial$acid-transactions.adoc[tag=query-concurrency]

include::{version-server}@sdk:shared:partial$acid-transactions.adoc[tag=query-perf]

include::{version-server}@sdk:shared:partial$acid-transactions.adoc[tag=query-single]

[source,csharp]
----
include::example$TransactionsExample.cs[tag=querySingle,indent=0]
----

You can also run a single query transaction against a particular `IScope` (these examples will exclude the full error handling for brevity):

[source,csharp]
----
include::example$TransactionsExample.cs[tag=querySingleScoped,indent=0]
----

and configure it:

[source,csharp]
----
include::example$TransactionsExample.cs[tag=querySingleConfigured,indent=0]
----

include::{version-server}@sdk:shared:partial$acid-transactions.adoc[tag=n1ql-rbac]


== Committing

Committing is automatic: if there is no explicit call to `ctx.CommitAsync()` at the end of the transaction logic callback, and no exception is thrown, it will be committed.

[source,csharp]
----
include::example$TransactionsExample.cs[tag=commit,indent=0]
----

As described above, as soon as the transaction is committed, all its changes will be atomically visible to reads from other transactions.
The changes will also be committed (or "unstaged") so they are visible to non-transactional actors, in an eventually consistent fashion.

Commit is final: after the transaction is committed, it cannot be rolled back, and no further operations are allowed on it.

An asynchronous cleanup process ensures that once the transaction reaches the commit point, it will be fully committed -- even if the application crashes.


// == A Full Transaction Example
include::{version-server}@sdk:shared:partial$acid-transactions.adoc[tag=example]

A complete version of this example is available on our https://github.com/couchbaselabs/couchbase-transactions-dotnet-examples[GitHub transactions examples page].

[source,csharp]
----
include::example$TransactionsExample.cs[tag=full,indent=0]
----


== Rollback

If an exception is thrown, either by the application from the lambda, or by the transactions library, then that attempt is rolled back.
The transaction logic may or may not be retried, depending on the exception.
//- see link:#error-handling[Error handling and logging].

If the transaction is not retried then it will throw a `TransactionFailedException` exception, and its `Cause` property can be used for more details on the failure.

The application can use this to signal why it triggered a rollback, as so:

[source,csharp]
----
include::example$TransactionsExample.cs[tag=rollback-cause,indent=0]
----

The transaction can also be explicitly rolled back:

[source,csharp]
----
include::example$TransactionsExample.cs[tag=rollback,indent=0]
----

In this case, if `ctx.RollbackAsync()` is reached, then the transaction will be regarded as successfully rolled back and no TransactionFailed will be thrown.

After a transaction is rolled back, it cannot be committed, no further operations are allowed on it, and the library will not try to automatically commit it at the end of the code block.



//  Error Handling
include::{version-server}@sdk:shared:partial$acid-transactions.adoc[tag=error]

There are three exceptions that Couchbase transactions can raise to the application:
`TransactionFailedException`, `TransactionExpiredException` and `TransactionCommitAmbiguousException`.
All exceptions derive from `TransactionFailedException` for backwards-compatibility purposes.

//  txnfailed
include::{version-server}@sdk:shared:partial$acid-transactions.adoc[tag=txnfailed]

[source,csharp]
----
include::example$TransactionsExample.cs[tag=config-expiration,indent=0]
----

include::{version-server}@sdk:shared:partial$acid-transactions.adoc[tag=txnfailed1]

Similar to `TransactionResult`, `SingleQueryTransactionResult` also has an `UnstagingComplete` property.

=== Full Error Handling Example

Pulling all of the above together, this is the suggested best practice for error handling:

[source,csharp]
----
include::example$TransactionsExample.cs[tag=full-error-handling,indent=0]
----


// == Asynchronous Cleanup
include::{version-server}@sdk:shared:partial$acid-transactions.adoc[tags=cleanup;!integrated-sdk-cleanup-collections]

[#tuning-cleanup]
=== Configuring Cleanup

The cleanup settings can be configured as so:

[options="header"]
|===
|Setting|Default|Description
|`CleanupWindow`|60 seconds|This determines how long a cleanup 'run' is; that is, how frequently this client will check its subset of ATR documents.  It is perfectly valid for the application to change this setting, which is at a conservative default.  Decreasing this will cause expiration transactions to be found more swiftly (generally, within this cleanup window), with the tradeoff of increasing the number of reads per second used for the scanning process.
|`CleanupLostAttempts`|true|This is the thread that takes part in the distributed cleanup process described above, that cleans up expired transactions created by any client.  It is strongly recommended that it is left enabled.
|`CleanupClientAttempts`|true|This thread is for cleaning up transactions created just by this client.  The client will preferentially aim to send any transactions it creates to this thread, leaving transactions for the distributed cleanup process only when it is forced to (for example, on an application crash).  It is strongly recommended that it is left enabled.
|===

////
=== Monitoring Cleanup

If the application wishes to monitor cleanup it may subscribe to these events:

[source,csharp]
----
include::example$TransactionsExample.cs[tag=cleanup-events,indent=0]
----

`TransactionCleanupEndRunEvent` is raised whenever a current 'run' is finished, and contains statistics from the run.
(A run is typically around every 60 seconds, with default configuration.)

A `TransactionCleanupAttempt` event is raised when an expired transaction was found by this process, and a cleanup attempt was made.
It contains whether that attempt was successful, along with any logs relevant to the attempt.

In addition, if cleanup fails to cleanup a transaction that is more than two hours past expiry, it will raise the `TransactionCleanupAttempt` event at WARN level (rather than the default DEBUG).
With most default configurations of the event-bus (see <<Logging>> below), this will cause that event to be logged somewhere visible to the application.
If there is not a good reason for the cleanup to be failed (such as a downed node that has not yet been failed-over), then the user is encouraged to report the issue.
////


== Logging

To aid troubleshooting, each transaction maintains a list of log entries, which can be logged on failure like this:

[source,csharp]
----
include::example$TransactionsExample.cs[tag=logging,indent=0]
----

A failed transaction can involve dozens, even hundreds, of lines of logging, so the application may prefer to write failed transactions into a separate file.

////
This will log all lines of any failed transactions, to `WARN` level:
[source,csharp]
----
include::example$TransactionsExample.cs[tag=config_warn,indent=0]
----
////

Please see the xref:howtos:collecting-information-and-logging.adoc[.NET SDK logging documentation] for details.

Here is an example of configuring a `Microsoft.Extensions.Logging.ILoggingFactory`:

[source,csharp]
----
include::example$TransactionsExample.cs[tag=full-logging,indent=0]
----

include::{version-server}@sdk:shared:partial$acid-transactions.adoc[tag=custom-metadata-1]

[source,csharp]
----
include::example$TransactionsExample.cs[tag=custom-metadata,indent=0]
----

include::{version-server}@sdk:shared:partial$acid-transactions.adoc[tag=custom-metadata-2]

== Further Reading

* There's plenty of explanation about how Transactions work in Couchbase in our xref:7.0@server:learn:data/transactions.adoc[Transactions documentation].
* You can find further code examples on our https://github.com/couchbaselabs/couchbase-transactions-dotnet-examples[transactions examples repository].
