= Distributed Transactions from the .NET SDK
:description: A practical guide to using Couchbase’s distributed ACID transactions, via the .NET API.
:navtitle: ACID Transactions
:page-topic-type: howto
:page-aliases: acid-transactions.adoc

include::project-docs:partial$attributes.adoc[]

[abstract]
{description}


include::{version-server}@sdk:shared:partial$acid-transactions.adoc[tag=intro]


Below we show you how to create Transactions, step-by-step.
You may also want to start with our https://github.com/couchbaselabs/couchbase-transactions-dotnet-examples[transactions examples repository],
which features useful downloadable examples of using Distributed Transactions.

API Docs are available https://docs.couchbase.com/sdk-api/couchbase-transactions-dotnet/[online].


== Requirements

* Couchbase Server 6.6.2 or above.
* Couchbase .NET client 3.2.3 or above.
It is recommended you use the package on NuGet.
include::{version-server}@sdk:shared:partial$acid-transactions.adoc[tag=requirements]


== Getting Started

Couchbase transactions require no additional components or services to be configured.
Simply add the transactions library into your project.
Version 1.1.0 was release October 29th, 2021.
See the xref:project-docs:distributed-transactions-dotnet-release-notes.adoc[Release Notes] for the latest version.

With NuGut this can be accomplished by using the NuGet Package Manager in your IDE:

[source]
----
PM > Install-Package Couchbase.Transactions -Version 1.1.0
----

Or via the CLI

[source]
----
dotnet add package Couchbase.Transactions --version 1.1.0
----

Or by using PackageReference in your .csproj file:

[source]
----
<PackageReference Include="Couchbase.Transactions" Version="1.1.0" />
----

A complete simple NuGet example is available on our https://github.com/couchbaselabs/couchbase-transactions-dotnet-examples[transactions examples repository].


== Initializing Transactions

Here are all imports used by the following examples:

[source,csharp]
----
using System;
using System.Linq;
using System.Threading.Tasks;
using Couchbase.KeyValue;
using Couchbase.Query;
using Couchbase.Transactions.Config;
using Couchbase.Transactions.Deferred;
using Couchbase.Transactions.Error;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json.Linq;
----
////
----
include::example$TransactionsExample.cs[tag=imports,indent=0]
----
////

The starting point is the `Transactions` object.
It is very important that the application ensures that only one of these is created per cluster, as it performs automated background clean-up processes that should not be duplicated.
In dependency injection context, this instance should be injected as a singleton.

[source,csharp]
----
include::example$TransactionsExample.cs[tag=init,indent=0]
----

=== Multiple Transactions Objects
Generally an application will need just one `Transactions` object, and in fact the library will usually warn if more are created.
Each `Transactions` object uses some resources, including a thread-pool.

There is one rare exception where an application may need to create multiple `Transactions` objects, which is covered in <<Custom Metadata Collections>>.

== Configuration

Transactions can optionally be configured at the point of creating the `Transactions` object:

[source,csharp]
----
include::example$TransactionsExample.cs[tag=config,indent=0]
----

include::{version-server}@sdk:shared:partial$acid-transactions.adoc[tag=config]


include::{version-server}@sdk:shared:partial$acid-transactions.adoc[tag=creating]

As with the Couchbase .NET Client, you should use the library asynchronusly using the async/await keywords (the exceptions will be explained later in <<Error Handling>>):

[source,csharp]
----
include::example$TransactionsExample.cs[tag=create,indent=0]
----

The asynchronous API allows you to use the thread pool, which can help you scale with excellent efficiency.
However, operations inside an individual transaction should be kept in-order and executed using `await` immediately.
Do not use fire-and-forget tasks under any circumstances.


== Examples

A code example is worth a thousand words, so here is a quick summary of the main transaction operations.
They are described in more detail below.

[source,csharp]
----
include::example$TransactionsExample.cs[tag=examples,indent=0]
----

include::{version-server}@sdk:shared:partial$acid-transactions.adoc[tag=mechanics]


== Key-Value Mutations

=== Inserting

[source,csharp]
----
include::example$TransactionsExample.cs[tag=insert,indent=0]
----

=== Replacing

Replacing a document requires awaiting a `TransactionGetResult` returned from `ctx.GetAsync()`, `ctx.InsertAsync()`, or another `ctx.ReplaceAsync()` call first.
This is necessary to ensure that the document is not involved in another transaction.
(If it is, then the transaction will handle this, generally by rolling back what has been done so far, and retrying the lambda.)

[source,csharp]
----
include::example$TransactionsExample.cs[tag=replace,indent=0]
----

=== Removing

As with replaces, removing a document requires awaiting a `TransactionGetResult` from a previous transaction operation first.

[source,csharp]
----
include::example$TransactionsExample.cs[tag=remove,indent=0]
----

== Key-Value Reads

There are two ways to get a document, `GetAsync` and `GetOptionalAsync`:

[source,csharp]
----
include::example$TransactionsExample.cs[tag=get,indent=0]
----

`GetAsync` will cause the transaction to fail with `TransactionFailedException` (after rolling back any changes, of course).
It is provided as a convenience method so the developer does not have to check for `null` if the document must exist for the transaction to succeed.

Gets will 'read your own writes', e.g. this will succeed:

[source,csharp]
----
include::example$TransactionsExample.cs[tag=getReadOwnWrites,indent=0]
----


include::7.0@sdk:shared:partial$acid-transactions.adoc[tag=query-intro]

=== Using N1QL
If you already use N1QL from the .NET SDK, then its use in transactions is very similar.
it returns the same `IQueryResult<T>` you are used to, and takes most of the same options.

You must take care to write `ctx.QueryAsync()` inside the lambda however, rather than `cluster.QueryAsync()` or `scope.QueryAsync()`.

An example of SELECTing some rows from the `travel-sample` bucket:

[source,csharp]
----
include::example$TransactionsExample.cs[tag=queryExamplesSelect,indent=0]
----

Rather than specifying the full "`travel-sample`.inventory.hotel" name each time, it is easier to pass a reference to the inventory `IScope`:

[source,csharp]
----
include::example$TransactionsExample.cs[tag=queryExamplesSelectScope,indent=0]
----

An example using a `IScope` for an UPDATE:

[source,csharp]
----
include::example$TransactionsExample.cs[tag=queryExamplesUpdate,indent=0]
----

And an example combining SELECTs and UPDATEs.
It's possible to call regular Java methods from the lambda, as shown here, permitting complex logic to be performed.
Just remember that since the lambda may be called multiple times, so may the method.

[source,csharp]
----
include::example$TransactionsExample.cs[tag=queryExamplesComplex,indent=0]
----

=== Read Your Own Writes
As with Key-Value operations, N1QL queries support Read Your Own Writes.

This example shows INSERTing a document and then SELECTing it again.

[source,csharp]
----
include::example$TransactionsExample.cs[tag=queryInsert,indent=0]
----
<1> The inserted document is only staged at this point. as the transaction has not yet committed.
Other transactions, and other non-transactional actors, will not be able to see this staged insert yet.
<2> But the SELECT can, as we are reading a mutation staged inside the same transaction.

=== Mixing Key-Value and N1QL
Key-Value operations and queries can be freely intermixed, and will interact with each other as you would expect.

In this example we insert a document with Key-Value, and read it with a SELECT.
[source,csharp]
----
include::example$TransactionsExample.cs[tag=queryRyow,indent=0]
----
<1> As with the 'Read Your Own Writes' example, here the insert is only staged, and so it is not visible to other transactions or non-transactional actors.
<2> But the SELECT can view it, as the insert was in the same transaction.

=== Query Options
Query options can be provided via `TransactionsQueryOptions`, which provides a subset of the options in the .NET SDK's `QueryOptions`.

[source,csharp]
----
include::example$TransactionsExample.cs[tag=queryOptions,indent=0]
----

include::7.0@sdk:shared:partial$acid-transactions.adoc[tag=query-options]

See the xref:howtos:n1ql-queries-with-sdk.adoc#query-options[QueryOptions documentation] for details on these.

include::7.0@sdk:shared:partial$acid-transactions.adoc[tag=query-perf]

include::7.0@sdk:shared:partial$acid-transactions.adoc[tag=query-single]

[source,csharp]
----
include::example$TransactionsExample.cs[tag=querySingle,indent=0]
----

You can also run a single query transaction against a particular `IScope` (these examples will exclude the full error handling for brevity):

[source,csharp]
----
include::example$TransactionsExample.cs[tag=querySingleScoped,indent=0]
----

and configure it:

[source,csharp]
----
include::example$TransactionsExample.cs[tag=querySingleConfigured,indent=0]
----

== Committing

Committing is automatic: if there is no explicit call to `ctx.CommitAsync()` at the end of the transaction logic callback, and no exception is thrown, it will be committed.

[source,csharp]
----
include::example$TransactionsExample.cs[tag=commit,indent=0]
----

As described above, as soon as the transaction is committed, all its changes will be atomically visible to reads from other transactions.
The changes will also be committed (or "unstaged") so they are visible to non-transactional actors, in an eventually consistent fashion.

Commit is final: after the transaction is committed, it cannot be rolled back, and no further operations are allowed on it.

An asynchronous cleanup process ensures that once the transaction reaches the commit point, it will be fully committed -- even if the application crashes.


// == A Full Transaction Example
include::{version-server}@sdk:shared:partial$acid-transactions.adoc[tag=example]

A complete version of this example is available on our https://github.com/couchbaselabs/couchbase-transactions-dotnet-examples[GitHub transactions examples page].

[source,csharp]
----
include::example$TransactionsExample.cs[tag=full,indent=0]
----


== Rollback

If an exception is thrown, either by the application from the lambda, or by the transactions library, then that attempt is rolled back.
The transaction logic may or may not be retried, depending on the exception.
//- see link:#error-handling[Error handling and logging].

If the transaction is not retried then it will throw a `TransactionFailedException` exception, and its `Cause` property can be used for more details on the failure.

The application can use this to signal why it triggered a rollback, as so:

[source,csharp]
----
include::example$TransactionsExample.cs[tag=rollback-cause,indent=0]
----

The transaction can also be explicitly rolled back:

[source,csharp]
----
include::example$TransactionsExample.cs[tag=rollback,indent=0]
----

In this case, if `ctx.RollbackAsync()` is reached, then the transaction will be regarded as successfully rolled back and no TransactionFailed will be thrown.

After a transaction is rolled back, it cannot be committed, no further operations are allowed on it, and the library will not try to automatically commit it at the end of the code block.



//  Error Handling
// tag::error[]
== Error Handling

As discussed previously, the transactions library will attempt to resolve many errors itself, through a combination of retrying individual operations and the application's lambda.
This includes some transient server errors, and conflicts with other transactions.

But there are situations that cannot be resolved, and total failure is indicated to the application via exceptions.
These errors include:

* Any exception thrown by your transaction lambda, either deliberately or through an application logic bug.
* Attempting to insert a document that already exists.
* Attempting to remove or replace a document that does not exist.
* Calling `ctx.GetAsync()` on a document key that does not exist.

IMPORTANT: Once one of these errors occurs, the current attempt is irrevocably failed (though the transaction may retry the lambda).
It is not possible for the application to catch the failure and continue.
Once a failure has occurred, all other operations tried in this attempt (including commit) will instantly fail.

Transactions, as they are multi-stage and multi-document, also have a concept of partial success/failure.
This is signalled to the application through the `TransactionResult.UnstagingComplete` property, described later.

There are three exceptions that the transactions library can raise to the application: `TransactionFailed`, `TransactionExpired`, and `TransactionCommitAmbiguous`.
All exceptions derive from `TransactionFailed` for backwards-compatibility purposes.
// end::error[]

//  txnfailed
include::{version-server}@sdk:shared:partial$acid-transactions.adoc[tag=txnfailed]

[source,csharp]
----
include::example$TransactionsExample.cs[tag=config-expiration,indent=0]
----

// tag::txnfailed1[]
This will allow the protocol more time to get past any transient failures (for example, those caused by a cluster rebalance).
The tradeoff to consider with longer expiration times, is that documents that have been staged by a transaction are effectively locked from modification from other transactions, until the expiration time has exceeded.

Note that expiration is not guaranteed to be followed precisely.
For example, if the application were to do a long blocking operation inside the lambda (which should be avoided), then expiration can only trigger after this finishes.
Similarly, if the transaction attempts a key-value operation close to the expiration time, and that key-value operation times out, then the expiration time may be exceeded.

=== TransactionCommitAmbiguous

As discussed <<mechanics,previously>>, each transaction has a 'single point of truth' that is updated atomically to reflect whether it is committed.

However, it is not always possible for the protocol to become 100% certain that the operation was successful, before the transaction expires.
That is, the operation may have successfully completed on the cluster, or may succeed soon, but the protocol is unable to determine this (whether due to transient network failure or other reason).
This is important as the transaction may or may not have reached the commit point, e.g. succeeded or failed.

The library raises `TransactionCommitAmbiguous` to indicate this state.
It should be rare to receive this exception.

If the transaction had in fact successfully reached the commit point, then the transaction will be fully completed ("unstaged") by the asynchronous cleanup process at some point in the future.
With default settings this will usually be within a minute, but whatever underlying fault has caused the TransactionCommitAmbiguous may lead to it taking longer.

If the transaction had not in fact reached the commit point, then the asynchronous cleanup process will instead attempt to roll it back at some point in the future.
If unable to, any staged metadata from the transaction will not be visible, and will not cause problems (e.g. there are safety mechanisms to ensure it will not block writes to these documents for long).

==== Handling
This error can be challenging for an application to handle.
As with `TransactionFailed` it is recommended that it at least writes any logs from the transaction, for future debugging.
It may wish to retry the transaction at a later point, or globally extend transactional expiration times to give the protocol additional time to resolve the ambiguity.

=== TransactionResult.UnstagingComplete

As above, there is a 'single point of truth' for a transaction.
After this atomic commit point is reached, the documents themselves will still be individually committed (we also call this "unstaging").
However, transactionally-aware actors will now be returning the post-transaction versions of the documents, and the transaction is effectively fully committed to those actors.

So if the application is solely working with transaction-aware actors, then the unstaging process is optional.
And failures during the unstaging process are not particularly important, in this case.
(Note the asynchronous cleanup process will still complete the unstaging process at a later point.)

Hence, many errors during unstaging will cause the transaction to immediately return success.
That is, successful return simply means that the commit point was reached.

The property `TransactionResult.UnstagingComplete` indicates whether the unstaging process completed successfully or not.
This should be used any time that the application needs all results of the transaction to be immediately available to non-transactional actors (which currently includes N1QL and non-transactional Key-Value reads).

Error handling differs depending on whether a transaction is before or after the point of commit (or rollback).
// end::txnfailed1[]


== Full Error Handling Example

Pulling all of the above together, this is the suggested best practice for error handling:

[source,csharp]
----
include::example$TransactionsExample.cs[tag=full-error-handling,indent=0]
----


// == Asynchronous Cleanup
include::{version-server}@sdk:shared:partial$acid-transactions.adoc[tag=cleanup]

////
=== Monitoring Cleanup

If the application wishes to monitor cleanup it may subscribe to these events:

[source,csharp]
----
include::example$TransactionsExample.cs[tag=cleanup-events,indent=0]
----

`TransactionCleanupEndRunEvent` is raised whenever a current 'run' is finished, and contains statistics from the run.
(A run is typically around every 60 seconds, with default configuration.)

A `TransactionCleanupAttempt` event is raised when an expired transaction was found by this process, and a cleanup attempt was made.
It contains whether that attempt was successful, along with any logs relevant to the attempt.

In addition, if cleanup fails to cleanup a transaction that is more than two hours past expiry, it will raise the `TransactionCleanupAttempt` event at WARN level (rather than the default DEBUG).
With most default configurations of the event-bus (see <<Logging>> below), this will cause that event to be logged somewhere visible to the application.
If there is not a good reason for the cleanup to be failed (such as a downed node that has not yet been failed-over), then the user is encouraged to report the issue.
////


== Logging

To aid troubleshooting, each transaction maintains a list of log entries, which can be logged on failure like this:

[source,csharp]
----
include::example$TransactionsExample.cs[tag=logging,indent=0]
----

A failed transaction can involve dozens, even hundreds, of lines of logging, so the application may prefer to write failed transactions into a separate file.

////
This will log all lines of any failed transactions, to `WARN` level:
[source,csharp]
----
include::example$TransactionsExample.cs[tag=config_warn,indent=0]
----
////

Please see the xref:howtos:collecting-information-and-logging.adoc[.NET SDK logging documentation] for details.

Here is an example of configuring a `Microsoft.Extensions.Logging.ILoggingFactory`:

[source,csharp]
----
include::example$TransactionsExample.cs[tag=full-logging,indent=0]
----

include::{version-server}@sdk:shared:partial$acid-transactions.adoc[tag=custom-metadata-1]

[source,csharp]
----
include::example$TransactionsExample.cs[tag=custom-metadata,indent=0]
----

include::{version-server}@sdk:shared:partial$acid-transactions.adoc[tag=custom-metadata-2]

== Further Reading

* There’s plenty of explanation about how Transactions work in Couchbase in our xref:{version-server}@server:learn:data/transactions.adoc[Transactions documentation].
* You can find further code examples on our https://github.com/couchbaselabs/couchbase-transactions-dotnet-examples[transactions examples repository].
