= Distributed Transactions from the .NET SDK
:navtitle: ACID Transactions
:page-topic-type: howto
:page-aliases: acid-transactions


[abstract]
A practical guide to using Couchbase’s distributed ACID transactions, via the .NET API.


include::6.5@sdk:shared:partial$acid-transactions.adoc[tag=intro]


Below we show you how to create Transactions, step-by-step.
// You may also want to start with our https://github.com/couchbaselabs/couchbase-transactions-java-examples[transactions examples repository],
// which features useful downloadable examples of using Distributed Transactions.

// Javadocs are available https://docs.couchbase.com/sdk-api/couchbase-transactions-java-1.1.0/index.html?overview-summary.html[online].


== Requirements

* Couchbase Server 6.6 or above.
* Couchbase .NET client 3.0.5 or above.  
include::6.5@sdk:shared:partial$acid-transactions.adoc[tag=requirements]


== Getting Started

Couchbase transactions require no additional components or services to be configured. 
Simply add the transactions library into your project.
The latest version, as of October 2020, is 1.0.0-beta.

////
With Gradle this can be accomplished by modifying these sections of your build.gradle file like so:

[source,gradle]
----
dependencies {
    compile group: 'com.couchbase.client', name: 'couchbase-transactions', version: '1.1.0'
}
----

Use the same group, artifact, and version in your Maven-compatible tool of choice.

A complete simple gradle project is available on our https://github.com/couchbaselabs/couchbase-transactions-java-examples[transactions examples repository].
////

== Initializing Transactions

Here are all imports used by the following examples:

[source,java]
----
using System;
using System.Linq;
using System.Threading.Tasks;
using Couchbase.KeyValue;
using Couchbase.Query;
using Couchbase.Transactions.Config;
using Couchbase.Transactions.Error;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json.Linq;
----

The starting point is the `Transactions` object.  
It is very important that the application ensures that only one of these is created, as it performs automated background processes that should not be duplicated.

[source,java]
----
public Program(ICluster cluster, IBucket bucket, ICouchbaseCollection collection, Transactions transactions)
{
    _cluster = cluster;
    _bucket = bucket;
    _collection = collection;
    _transactions = transactions;
}
----


== Configuration

Transactions can optionally be configured at the point of creating the `Transactions` object:

[source,java]
----
include::example$TransactionsExample.cs[tag=config,indent=0]
----

include::6.5@sdk:shared:partial$acid-transactions.adoc[tag=config]


include::6.5@sdk:shared:partial$acid-transactions.adoc[tag=creating]

[source,java]
----
include::example$TransactionsExample.cs[tag=create,indent=0]
----

////
The synchronous mode is the easiest to write and understand.
The asynchronous API allows you to build your application in a reactive style, without large thread pools, which can help you scale with excellent efficiency.
Those new to reactive programming may want to check out https://projectreactor.io/[the Project Reactor site] for more details on this powerful paradigm.

NOTE: Some `AttemptContextReactive` methods, notably `remove`, return `Mono<Void>`.  
Be careful to use `then` rather than `flatMap` or similar on these, 
as `Mono<Void>` will only trigger a completion event, and not the next event, 
so many methods including flatMap will not work as expected.
////

== Examples

A code example is worth a thousand words, so here is a quick summary of the main transaction operations.
They are described in more detail below. 

[source,java]
----
include::example$TransactionsExample.cs[tag=examples,indent=0]
----


include::6.5@sdk:shared:partial$acid-transactions.adoc[tag=mechanics]


== Mutating Documents

=== Replacing

Replacing a document requires a `ctx.get()` call first.
This is necessary to ensure that the document is not involved in another transaction.
(If it is, then the transaction will handle this, generally by rolling back what has been done so far, and retrying the lambda.)

[source,java]
----
include::example$TransactionsExample.cs[tag=replace,indent=0]
----

=== Removing

As with replaces, removing a document requires a `ctx.get()` call first.

[source,java]
----
include::example$TransactionsExample.cs[tag=remove,indent=0]
----

=== Inserting

[source,java]
----
include::example$TransactionsExample.cs[tag=insert,indent=0]
----


== Getting Documents

There are two ways to get a document, `get` and `getOptional`:

[source,java]
----
include::example$TransactionsExample.cs[tag=get,indent=0]
----

`get` will cause the transaction to fail with `TransactionFailed` (after rolling back any changes, of course).
It is provided as a convenience method so the developer does not have to check the `Optional` if the document must exist for the transaction to succeed.

Gets will 'read your own writes', e.g. this will succeed:

[source,java]
----
include::example$TransactionsExample.cs[tag=getReadOwnWrites,indent=0]
----

== Committing

Committing is automatic: if there is no explicit call to `ctx.commit()` at the end of the transaction logic callback, and no exception is thrown, it will be committed.

[source,java]
----
include::example$TransactionsExample.cs[tag=commit,indent=0]
----

As described above, as soon as the transaction is committed, all its changes will be atomically visible to reads from other transactions.
The changes will also be committed (or "unstaged") so they are visible to non-transactional actors, in an eventually consistent fashion.

Commit is final: after the transaction is committed, it cannot be rolled back, and no further operations are allowed on it.

An asynchronous cleanup process ensures that once the transaction reaches the commit point, it will be fully committed -- even if the application crashes.


// == A Full Transaction Example
include::6.5@sdk:shared:partial$acid-transactions.adoc[tag=example]

// A complete version of this example is available on our https://github.com/couchbaselabs/couchbase-transactions-java-examples[GitHub transactions examples page].

[source,java]
----
include::example$TransactionsExample.cs[tag=full,indent=0]
----


// concurrency
include::6.5@sdk:shared:partial$acid-transactions.adoc[tag=concurrency]

[source,java]
----
include::example$TransactionsExample.cs[tag=concurrencyOps,indent=0]
----

These events will be raised in the event of a non-transactional write being detected and overridden.
The event contains the key of the document involved, to aid the application with debugging.


== Rollback

If an exception is thrown, either by the application from the lambda, or by the transactions library, then that attempt is rolled back.
The transaction logic may or may not be retried, depending on the exception.
//- see link:#error-handling[Error handling and logging].

If the transaction is not retried then it will throw a `TransactionFailed` exception, and its `getCause` method can be used for more details on the failure.

The application can use this to signal why it triggered a rollback, as so:

[source,java]
----
include::example$TransactionsExample.cs[tag=rollback-cause,indent=0]
----

The transaction can also be explicitly rolled back:

[source,java]
----
include::example$TransactionsExample.cs[tag=rollback,indent=0]
----

In this case, if `ctx.rollback()` is reached, then the transaction will be regarded as successfully rolled back and no TransactionFailed will be thrown.

After a transaction is rolled back, it cannot be committed, no further operations are allowed on it, and the library will not try to automatically commit it at the end of the code block.


//  Error Handling
include::6.5@sdk:shared:partial$acid-transactions.adoc[tag=error]



//  txnfailed
include::6.5@sdk:shared:partial$acid-transactions.adoc[tag=txnfailed]

[source,java]
----
include::example$TransactionsExample.cs[tag=config-expiration,indent=0]
----

include::6.5@sdk:shared:partial$acid-transactions.adoc[tag=txnfailed1]


=== Full Error Handling Example

Pulling all of the above together, this is the suggested best practice for error handling:

[source,java]
----
include::example$TransactionsExample.cs[tag=full-error-handling,indent=0]
----


include::6.5@sdk:shared:partial$acid-transactions.adoc[tag=cleanup]

////
=== Monitoring Cleanup

If the application wishes to monitor cleanup it may subscribe to these events:

[source,java]
----
include::example$TransactionsExample.cs[tag=cleanup-events,indent=0]
----

`TransactionCleanupEndRunEvent` is raised whenever a current 'run' is finished, and contains statistics from the run.
(A run is typically around every 60 seconds, with default configuration.)

A `TransactionCleanupAttempt` event is raised when an expired transaction was found by this process, and a cleanup attempt was made.
It contains whether that attempt was successful, along with any logs relevant to the attempt.

In addition, if cleanup fails to cleanup a transaction that is more than two hours past expiry, it will raise the `TransactionCleanupAttempt` event at WARN level (rather than the default DEBUG).
With most default configurations of the event-bus (see <<Logging>> below), this will cause that event to be logged somewhere visible to the application.
If there is not a good reason for the cleanup to be failed (such as a downed node that has not yet been failed-over), then the user is encouraged to report the issue.
////


== Logging

To aid troubleshooting, each transaction maintains a list of log entries, which can be logged on failure like this:

[source,java]
----
include::example$TransactionsExample.cs[tag=logging,indent=0]
----

A failed transaction can involve dozens, even hundreds, of lines of logging, so the application may prefer to write failed transactions into a separate file.

////
For convenience there is also a config option that will automatically write this programmatic log to the standard Couchbase Java logging configuration inherited from the SDK if a transaction fails.
This will log all lines of any failed transactions, to `WARN` level:
[source,java]
----
include::example$TransactionsExample.java[tag=config_warn,indent=0]
----

By default the Couchbase Java logging event-bus is setup to look for and use SLF4J/logback, log4j1, and log4j2 on the classpath, and to fallback to java.util.Logging.  
////

Please see the xref:howtos:collecting-information-and-logging.adoc[.NET SDK logging documentation] for details.

Most applications will have their own preferred logging solution in-place already.
For those starting from scratch here is a complete example:

[source,java]
----
include::example$TransactionsExample.cs[tag=full-logging,indent=0]
----

////
== Concurrent Operations with the Async API

The async API allows operations to be performed concurrently inside a transaction, which can assist performance.
There are two rules the application needs to follow:

* The first mutation must be performed alone, in serial.
This is because the first mutation also triggers the creation of metadata for the transaction.
* All concurrent operations must be allowed to complete fully, so the transaction library can track which operations need to be rolled back in the event of failure.
This means the application must 'swallow' the error, but record that an error occurred, and then at the end of the concurrent operations, if an error occurred, throw an error to cause the transaction to retry.

These rules are demonstrated here:

[source,java]
----
include::example$TransactionsExample.java[tag=concurrentOps,indent=0]
----
////


////
== Deferred Commits

NOTE: The deferred commit feature is currently in alpha, and the API may change.

Deferred commits allow a transaction to be paused just before the commit point.
Optionally, everything required to finish the transaction can then be bundled up into a context that may be serialized into a String or byte array, and deserialized elsewhere (for example, in another process).
The transaction can then be committed, or rolled back.

The intention behind this feature is to allow multiple transactions, potentially spanning multiple databases, to be brought to just before the commit point, and then all committed together.

Here's an example of deferring the initial commit and serializing the transaction:

[source,java]
----
include::example$TransactionsExample.java[tag=defer1,indent=0]
----

And then committing the transaction later:

[source,java]
----
include::example$TransactionsExample.java[tag=defer2,indent=0]
----

Alternatively the transaction can be rolled back:

[source,java]
----
include::example$TransactionsExample.java[tag=defer3,indent=0]
----

The transaction expiry timer (which is configurable) will begin ticking once the transaction starts, and is not paused while the transaction is in a deferred state.

////

include::6.5@sdk:shared:partial$acid-transactions.adoc[tag=further]
