= Using Couchbase Transactions
:description: A practical guide to using Couchbase's distributed ACID transactions, via the .NET SDK.
:page-topic-type: howto
:page-aliases: acid-transactions
:page-toclevels: 2
:page-pagination: next

include::project-docs:partial$attributes.adoc[]
include::partial$acid-transactions-attributes.adoc[]

[abstract]
{description}

This guide will show you examples of how to perform multi-document ACID (atomic, consistent, isolated, and durable) database transactions within your application, using the Couchbase .NET SDK and transactions library.

Refer to the xref:concept-docs:transactions.adoc[] page for a high-level overview.

== Prerequisites

[{tabs}]
====
Couchbase Capella::
+
--
* Couchbase Capella account.
* You should know how to perform xref:howtos:kv-operations.adoc[key-value] or xref:howtos:n1ql-queries-with-sdk.adoc[query] operations with the SDK.
* Your application should have the relevant roles and permissions on the required buckets, scopes, and collections, to perform transactional operations.
Refer to the xref:cloud:organizations:organization-projects-overview.adoc[Organizations & Access] page for more details.
* If your application is using xref:concept-docs:xattr.adoc[extended attributes (XATTRs)], you should avoid using the XATTR field `txn` -- this is reserved for Couchbase use.
--

Couchbase Server::
+
--
* Couchbase Server (6.6.2 or above).
* You should know how to perform xref:howtos:kv-operations.adoc[key-value] or xref:howtos:n1ql-queries-with-sdk.adoc[query] operations with the SDK.
* Your application should have the relevant roles and permissions on the required buckets, scopes, and collections, to perform transactional operations.
Refer to the xref:{version-server}@server:learn:security/roles.adoc[Roles] page for more details.
* If your application is using xref:concept-docs:xattr.adoc[extended attributes (XATTRs)], you should avoid using the XATTR field `txn` -- this is reserved for Couchbase use.
* NTP should be configured so nodes of the Couchbase cluster are in sync with time.
--
====

include::{version-common}@sdk:shared:partial$acid-transactions.adoc[tag=requirements]

// TODO: Remove this once the SDK uses integrated transactions, instead of the library.
=== Transactions Library

Couchbase transactions require no additional components or services to be configured.
Simply add the transactions library into your project.
Version `1.1.0` was released October 29th, 2021. +
See the xref:project-docs:distributed-transactions-dotnet-release-notes.adoc[Release Notes] for the latest version.

.Installation
[{tabs}]
====
NuGet::
+
--
With NuGet this can be accomplished by using the NuGet Package Manager in your IDE:

----
PM > Install-Package Couchbase.Transactions -Version 1.1.0
----
--

CLI::
+
--
You can also install the library with the dotnet CLI.

[source,console]
----
$ dotnet add package Couchbase.Transactions --version 1.1.0
----
--

.csproj file::
+
--
If you're using a .csproj file, add this `PackageReference`:

[source,xml]
----
<PackageReference Include="Couchbase.Transactions" Version="1.1.0" />
----
--
====
// End TODO

== Creating a Transaction

// TODO: Remove this once the SDK uses integrated transactions, instead of the library.
The starting point is the `Transactions` object.
It is very important that an application ensures that only one of these is created per cluster, as it performs automated background clean-up processes that should not be duplicated.
In a dependency injection context, this instance should be injected as a singleton.

[source,csharp]
----
include::example$TransactionsExample.cs[tag=init,indent=0]
----
// End TODO

include::{version-common}@sdk:shared:partial$acid-transactions.adoc[tag=creating]

[source,csharp]
----
include::example$TransactionsExample.cs[tag=examples,indent=0]
----

include::{version-common}@sdk:shared:partial$acid-transactions.adoc[tag=lambda-ctx]

[IMPORTANT]
====
As with the Couchbase .NET Client, you should use the transactions library asynchronously using the async/await keywords.
The asynchronous API allows you to use the thread pool, which can help you scale with excellent efficiency.
However, operations inside an individual transaction should be kept in-order and executed using `await` immediately.
Do not use fire-and-forget tasks under any circumstances.
====

include::{version-common}@sdk:shared:partial$acid-transactions.adoc[tag=creating-error]

=== Logging

To aid troubleshooting, each transaction maintains a list of log entries, which can be logged on failure like this:

[source,csharp]
----
include::example$TransactionsExample.cs[tag=logging,indent=0]
----

A failed transaction can involve dozens, even hundreds, of lines of logging, so it may be preferable to write failed transactions into a separate file.

////
This will log all lines of any failed transactions, to `WARN` level:
[source,csharp]
----
include::example$TransactionsExample.cs[tag=config_warn,indent=0]
----
////

Please see the xref:howtos:collecting-information-and-logging.adoc[.NET SDK logging documentation] for details.

Here is an example of configuring a `Microsoft.Extensions.Logging.ILoggingFactory`:

[source,csharp]
----
include::example$TransactionsExample.cs[tag=full-logging,indent=0]
----

== Key-Value Operations

You can perform transactional database operations using familiar key-value CRUD methods:

* **C**reate - `InsertAsync()`

* **R**ead - `GetAsync()` or `GetOptionalAsync()`

* **U**pdate - `ReplaceAsync()`

* **D**elete - `RemoveAsync()`

[IMPORTANT]
====
As mentioned <<lambda-ops,previously>>, make sure your application uses the transactional key-value operations inside the {lambda} -- such as `ctx.InsertAsync()`, rather than `collection.InsertAsync()`.
====

=== Insert

To insert a document within a transaction {lambda}, simply call `ctx.InsertAsync()`.

[source,csharp]
----
include::example$TransactionsExample.cs[tag=insert,indent=0]
----

=== Get

There are two ways to get a document, `GetAsync` and `GetOptionalAsync`:

[source,csharp]
----
include::example$TransactionsExample.cs[tag=get,indent=0]
----

`GetAsync` may return a `TransactionFailedException` if a document doesn't exist, for example.
It is provided as a convenience method, so a developer does not have to check for `null` if the document must exist for the transaction to succeed -- which is the case with `GetAsyncOptional`.

Gets will "Read Your Own Writes", e.g. this will succeed:

[source,csharp]
----
include::example$TransactionsExample.cs[tag=getReadOwnWrites,indent=0]
----

Of course, no other transaction will be able to read that inserted document, until this transaction reaches the commit point.

=== Replace

Replacing a document requires awaiting a `TransactionGetResult` returned from `ctx.GetAsync()`, `ctx.InsertAsync()`, or another `ctx.ReplaceAsync()` call first.
This is necessary to ensure that the document is not involved in another transaction.
If it is, then the transaction will handle this, generally by rolling back what has been done so far, and retrying the lambda.

[source,csharp]
----
include::example$TransactionsExample.cs[tag=replace,indent=0]
----

=== Remove

As with replaces, removing a document requires awaiting a `TransactionGetResult` from a previous transaction operation first.

[source,csharp]
----
include::example$TransactionsExample.cs[tag=remove,indent=0]
----

== {sqlpp} Queries

If you already use https://www.couchbase.com/products/n1ql[{sqlpp} (formerly N1QL)], then its use in transactions is very similar.
A query returns the same `IQueryResult<T>` you are used to, and takes most of the same options.

[IMPORTANT]
====
As mentioned <<lambda-ops,previously>>, make sure your application uses the transactional query operations inside the {lambda} -- such as `ctx.QueryAsync()`, rather than `cluster.QueryAsync()` or `scope.QueryAsync()`.
====

Here is an example of selecting some rows from the `travel-sample` bucket:

[source,csharp]
----
include::example$TransactionsExample.cs[tag=queryExamplesSelectScope,indent=0]
----

An example using a `IScope` for an UPDATE:

[source,csharp]
----
include::example$TransactionsExample.cs[tag=queryExamplesUpdate,indent=0]
----

And an example combining `SELECT` and `UPDATE`.

[source,csharp]
----
include::example$TransactionsExample.cs[tag=queryExamplesComplex,indent=0]
----

As you can see from the snippet above, it is possible to call regular C# methods from the lambda, permitting complex logic to be performed.
Just remember that since the {lambda} may be called multiple times, so may the method.

Like key-value operations, queries support "Read Your Own Writes".
This example shows inserting a document and then selecting it again:

[source,csharp]
----
include::example$TransactionsExample.cs[tag=queryInsert,indent=0]
----

<1> The inserted document is only staged at this point, as the transaction has not yet committed. +
Other transactions, and other non-transactional actors, will not be able to see this staged insert yet.
<2> But the `SELECT` can, as we are reading a mutation staged inside the same transaction.

=== Query Options

Query options can be provided via `TransactionQueryOptions` object:

[source,csharp]
----
include::example$TransactionsExample.cs[tag=queryOptions,indent=0]
----

.Supported Transaction Query Options
|===
| Name | Description

| `Parameter(Object)` | Allows to set positional arguments for a parameterized query.
| `Parameters(Object[])` | Allows you to set named arguments for a parameterized query.
| `ScanConsistency(QueryScanConsistency)` | Sets a different scan consistency for this query.
| `FlexIndex(Boolean)` | Tells the query engine to use a flex index (utilizing the search service).
| `Serializer(ITypeSerializer)` | Allows to use a different serializer for the decoding of the rows.
| `ClientContextId(String)` | Sets a context ID returned by the service for debugging purposes.
| `ScanWait(TimeSpan)` | Allows to specify a maximum scan wait time.
| `ScanCap(Int32)` | Specifies a maximum cap on the query scan size.
| `PipelineBatch(Int32)` | Sets the batch size for the query pipeline.
| `PipelineCap(Int32)` | Sets the cap for the query pipeline.
| `Readonly(Boolean)` | Tells the client and server that this query is readonly.
| `AdHoc(Boolean)` | If set to false will prepare the query and later execute the prepared statement.
| `Raw(String, Object)` | Escape hatch to add arguments that are not covered by these options.
|===

== Mixing Key-Value and {sqlpp}

Key-Value and {sqlpp} query operations can be freely intermixed, and will interact with each other as you would expect.
In this example we insert a document with a key-value operation, and read it with a `SELECT` query.

[source,csharp]
----
include::example$TransactionsExample.cs[tag=queryRyow,indent=0]
----

<1> The key-value insert operation is only staged, and so it is not visible to other transactions or non-transactional actors.
<2> But the `SELECT` can view it, as the insert was in the same transaction.

include::{version-common}@sdk:shared:partial$acid-transactions.adoc[tag=rbac]

== Configuration

The default configuration should be appropriate for most use-cases.
If needed, transactions can optionally be configured at the point of creating the `Transactions` object:

[source,csharp]
----
include::example$TransactionsExample.cs[tag=config,indent=0]
----

include::{version-common}@sdk:shared:partial$acid-transactions.adoc[tag=config]

== Additional Resources

* Learn more about xref:concept-docs:transactions.adoc[Distributed ACID Transactions].

* Check out the Couchbase Transactions library https://docs.couchbase.com/sdk-api/couchbase-transactions-dotnet/[API Reference].
