= Encrypting Your Data
:description: A practical guide for getting started with Field-Level Encryption, showing how to encrypt and decrypt JSON fields using the .NET SDK.
:page-topic-type: howto
:page-edition: Enterprise Edition
// :page-aliases: ROOT:encrypting-using-sdk.adoc

[abstract]
{description}

For a high-level overview of this feature, see the xref:concept-docs:encryption.adoc[Field-Level Encryption discussion doc].



[TIP]
.Native Encryption at Rest
====
Server 8.x (and new Capella Operational clusters) offer xref:server:learn:security/native-encryption-at-rest-overview.adoc[encryption at rest].
It's a comprehensive way of encrypting all data in a non-ephemeral bucket,
as well as logs, configuration data, and audit data.
However, you may prefer the relative simplicity of key management in Field Level Encryption for use cases where there are a limited number of data to be encrypted.
====



[#package]
== Packaging

The Couchbase .NET SDK works together with the https://github.com/couchbase/dotnet-couchbase-encryption[.NET Couchbase Encryption^] library to provide support for encryption and decryption of JSON fields.
This library makes use of the cryptographic algorithms available on your platform, and provides a framework for implementing your own crypto components.

NOTE: The encryption code is packaged as an optional library and is subject to the Couchbase https://www.couchbase.com/LA03012021[License] and https://www.couchbase.com/ESLA08042020[Enterprise Subscription License] agreements.
To use the encryption library, you have to explicitly include this dependency in your project configuration.
Refer to the xref:#maven-coordinates[dependencies section].

[#requirements]
== Requirements

* Couchbase .NET SDK version `3.1.3` or later.
* .NET Couchbase Encryption version `2.0.0-dp.1` or later.

[#nuget-package]
== NuGet Package

[source,xml]
----
<PackageReference Include="Couchbase.Extensions.Encryption" Version="2.0.0-dp.1" />
----

See the https://www.nuget.org/packages/Couchbase.Extensions.Encryption/[NuGet Package Page^] for the latest version.


== Configuration

To enable Field-Level Encryption, create a `CryptoManager` and supply `EncryptedFieldTranscoder` as an `Options` on the K/V operation.

[source,csharp]
----
include::example$EncryptingUsingSdk.csx[tag=encrypting_using_sdk_1,indent=0]
----


== Usage

Two modes of operation are available:

* Transparent encryption/decryption using `EncryptedFieldAttribute` on POCOs on deserialization/serialization.
* Manual field editing using `JObjectExtensions` and the `CryptoManager` itself.

=== Data Binding Example

Sensitive fields of your data classes can be annotated with `EncryptedField`.
Let's use this class as an example:

[source,csharp]
----
include::example$EncryptingUsingSdk.csx[tag=encrypting_using_sdk_2,indent=0]
----

Now let's create an employee record and save it to Couchbase:

[source,csharp]
----
include::example$EncryptingUsingSdk.csx[tag=encrypting_using_sdk_3,indent=0]
----

You can get the document as a `JsonObject` to verify the field was encrypted:

[source,csharp]
----
include::example$EncryptingUsingSdk.csx[tag=encrypting_using_sdk_4,indent=0]
----

Because `contentAsObject()` does not decrypt anything, the expected output is something like:

[source,json]
----
{
  "encrypted$replicant": {
    "alg": "AEAD_AES_256_CBC_HMAC_SHA512",
    "ciphertext": "xwcxyUyZ.....",
    "kid": "myKey"
  }
}
----

Now let's read the employee record using data binding:

[source,csharp]
----
include::example$EncryptingUsingSdk.csx[tag=encrypting_using_sdk_5,indent=0]
----

This prints `true`.

//==== Using a custom ObjectMapper

//The code that enables encryption/decryption during data binding is packaged as a Jackson module called `EncryptionModule`.
//You can register this module with any Jackson `ObjectMapper`.

//You'll need to do this if you want to supply your own customized ObjectMapper for the Java SDK to use when serializing documents.
//Here's how to configure the cluster environment to use a custom JSON serializer backed by your own ObjectMapper with support for Field-Level Encryption:

//[source,csharp]
//----
//include::example$EncryptingUsingSdk.csx[tag=encrypting_using_sdk_6,indent=0]
//----

//=== JObject and CryptoManager

//If you need more control of which fields get decrypted, or if you prefer working with the Couchbase `JsonObject` tree model,
//you can use a `CryptoManager` instance to read and write encrypted field values of a `JObject`.

//[source,csharp]
//----
//include::example$EncryptingUsingSdk.csx[tag=encrypting_using_sdk_7,indent=0]
//----


== Creating Encryption Keys

The AEAD_AES_256_CBC_HMAC_SHA512 algorithm included in this library uses encryption keys that are 64 bytes long.

Here's an example that shows how to create a suitable encryption key:

[source,csharp]
----
include::example$EncryptingUsingSdk.csx[tag=encrypting_using_sdk_8,indent=0]
----

And here's how to use it to create a `Keyring` for use with Couchbase Field-Level Encryption:

[source,csharp]
----
include::example$EncryptingUsingSdk.csx[tag=encrypting_using_sdk_9,indent=0]
----


[#migration-from-sdk2]
== Migrating from SDK 2

SDK 2.x reached end-of-life long ago,
but should you have fields encrypted by SDK 2.x, and the need to read them from SDK 3.x, 
then follow the steps in the 
https://docs-archive.couchbase.com/dotnet-sdk/3.4/howtos/encrypting-using-sdk.html#migration-from-sdk2[archived documents].


IMPORTANT: The encryption algorithms used by SDK 2 are deprecated, and are no longer used for encrypting new data.
Do not rely on the security of outdated encryption algorithms.

