= Field Level Encryption from the .NET SDK
:description: A practical guide for getting started with Field-Level Encryption, showing how to encrypt and decrypt JSON fields using the .NET SDK.
:page-topic-type: howto
:page-edition: Enterprise Edition
// :page-aliases: ROOT:encrypting-using-sdk.adoc

[abstract]
{description}

For a high-level overview of this feature, see the xref:concept-docs:encryption.adoc[Field-Level Encryption discussion doc].

[#package]
== Packaging

The Couchbase .NET SDK works together with the https://github.com/couchbase/dotnet-couchbase-encryption[.NET Couchbase Encryption^] library to provide support for encryption and decryption of JSON fields.
This library includes cryptographic algorithms and keyrings you can use out of the box, and provides a framework for implementing your own crypto components.

NOTE: The encryption code is packaged as an optional library and is subject to the Couchbase https://www.couchbase.com/LA03012021[License] and https://www.couchbase.com/ESLA08042020[Enterprise Subscription License] agreements.
To use the encryption library, you have to explicitly include this dependency in your project configuration.
Refer to the xref:#maven-coordinates[dependencies section].

[#requirements]
== Requirements

* Couchbase .NET SDK version `3.1.3` or later.
* .NET Couchbase Encryption version `2.0.0-dp.1` or later.

[#nuget-package]
== NuGet Package

[source,xml]
----
<PackageReference Include="Couchbase.Extensions.Encryption" Version="2.0.0-dp.1" />
----

See the https://www.nuget.org/packages/Couchbase.Extensions.Encryption/[NuGet Package Page^] for the latest version.


== Configuration

To enable Field-Level Encryption, create a `CryptoManager` and supply `EncryptedFieldTranscoder` as an `Options` on the K/V operation.

[source,csharp]
----
include::example$EncryptingUsingSdk.csx[tag=encrypting_using_sdk_1,indent=0]
----


== Usage

Two modes of operation are available:

* Transparent encryption/decryption using `EncryptedFieldAttribute` on POCOs on deserialization/serialization.
* Manual field editing using `JObjectExtensions` and the `CryptoManager` itself.

=== Data Binding Example

Sensitive fields of your data classes can be annotated with `EncryptedField`.
Let's use this class as an example:

[source,csharp]
----
include::example$EncryptingUsingSdk.csx[tag=encrypting_using_sdk_2,indent=0]
----

Now let's create an employee record and save it to Couchbase:

[source,csharp]
----
include::example$EncryptingUsingSdk.csx[tag=encrypting_using_sdk_3,indent=0]
----

You can get the document as a `JsonObject` to verify the field was encrypted:

[source,csharp]
----
include::example$EncryptingUsingSdk.csx[tag=encrypting_using_sdk_4,indent=0]
----

Because `contentAsObject()` does not decrypt anything, the expected output is something like:

[source,json]
----
{
  "encrypted$replicant": {
    "alg": "AEAD_AES_256_CBC_HMAC_SHA512",
    "ciphertext": "xwcxyUyZ.....",
    "kid": "myKey"
  }
}
----

Now let's read the employee record using data binding:

[source,csharp]
----
include::example$EncryptingUsingSdk.csx[tag=encrypting_using_sdk_5,indent=0]
----

This prints `true`.

//==== Using a custom ObjectMapper

//The code that enables encryption/decryption during data binding is packaged as a Jackson module called `EncryptionModule`.
//You can register this module with any Jackson `ObjectMapper`.

//You'll need to do this if you want to supply your own customized ObjectMapper for the Java SDK to use when serializing documents.
//Here's how to configure the cluster environment to use a custom JSON serializer backed by your own ObjectMapper with support for Field-Level Encryption:

//[source,csharp]
//----
//include::example$EncryptingUsingSdk.csx[tag=encrypting_using_sdk_6,indent=0]
//----

//=== JObject and CryptoManager

//If you need more control of which fields get decrypted, or if you prefer working with the Couchbase `JsonObject` tree model,
//you can use a `CryptoManager` instance to read and write encrypted field values of a `JObject`.

//[source,csharp]
//----
//include::example$EncryptingUsingSdk.csx[tag=encrypting_using_sdk_7,indent=0]
//----


== Creating Encryption Keys

The AEAD_AES_256_CBC_HMAC_SHA512 algorithm included in this library uses encryption keys that are 64 bytes long.

Here's an example that shows how to create a suitable encryption key:

[source,csharp]
----
include::example$EncryptingUsingSdk.csx[tag=encrypting_using_sdk_8,indent=0]
----

And here's how to use it to create a `Keyring` for use with Couchbase Field-Level Encryption:

[source,csharp]
----
include::example$EncryptingUsingSdk.csx[tag=encrypting_using_sdk_9,indent=0]
----


[#migration-from-sdk2]
== Migrating from SDK 2

WARNING: SDK 2 cannot read fields encrypted by SDK 3.

It's inadvisable to have both the old and new versions of your application active at the same time.
The simplest way to migrate is to do an offline upgrade during a scheduled a maintenance window.
For an online upgrade without downtime, consider a https://en.wikipedia.org/wiki/Blue-green_deployment[blue-green deployment^].

SDK 3 requires additional configuration to read fields encrypted by SDK 2.
The rest of this section describes how to configure Field-Level Encryption in SDK 3 for backwards compatibility with SDK 2.

[#configure-field-name-prefix]
=== Changing the field name prefix

In SDK 2, the default prefix for encrypted field names was `\__crypt_`.
This caused problems for Couchbase Sync Gateway, which does not like field names to begin with an underscore.
In SDK 3, the default prefix is `encrypted$`.

For compatibility with SDK 2, you can configure the `CryptoManager` to use the old `\__crypt_` prefix:

[source,csharp]
----
include::example$EncryptingUsingSdk.csx[tag=legacy_field_name_prefix,indent=0]
----

Alternatively, you can https://forums.couchbase.com/t/replacing-field-name-prefix/28786[rename the existing fields using a N1QL statement].

WARNING: In SDK 2, only top-level fields could be encrypted.
SDK 3 allows encrypting fields at any depth.
If you decide to rename the existing fields, make sure to do so _before_ writing any encrypted fields below the top level, otherwise it may be difficult to rename the nested fields using a generic N1QL statement.


[#configure-legacy-decrypters]
=== Enabling decrypters for legacy algorithms

The encryption algorithms used by SDK 2 are deprecated, and are no longer used for encrypting new data.
To enable decrypting fields written by SDK 2, register the legacy decrypters when configuring the `CryptoManager`:

[source,csharp]
----
include::example$EncryptingUsingSdk.csx[tag=legacy_decrypters,indent=0]
----

NOTE: The legacy decrypters require a mapping function.
For AES, this function accepts an encryption key name and returns the corresponding signing key name.
For RSA, this function accepts a public key name and returns the corresponding private key name.
