= Search
:description: You can use the Search service to create queryable search indexes in Couchbase Server.
:page-topic-type: howto
:page-pagination: full

include::project-docs:partial$attributes.adoc[]

[abstract]
{description}



The Search Service allows you to create, manage, and query Search indexes on JSON documents stored in Couchbase buckets.
It uses natural language processing for indexing and querying documents, provides relevance scoring on the results of your queries, and has fast indexes for querying a wide range of possible text searches.

Some of the supported query-types include simple queries like Match and Term queries, range queries like Date Range and Numeric Range and compound queries for conjunctions, disjunctions and/or boolean queries.

The Search Service also supports vector search from Couchbase Server 7.6 onwards.

The .NET SDK exposes an API for performing Search queries which abstracts some of the complexity of using the underlying REST API.

== Getting Started

After familiarizing yourself with how to create and query a Search index in the UI you can query it from the SDK. 

There are two APIs for querying search: `cluster.searchQuery()`, and `cluster.search()`.
Both are also available at the Scope level.

The former API supports Search queries (`SearchQuery`), while the latter additionally supports the `VectorSearch` added in 7.6.
Most of this documentation will focus on the former API, as the latter is in @Stability.Volatile status.

We will perform a Search query here - see the <<vector-search>> section for examples of that.

// As of Couchbase Server 6.5, Search ...

== Examples

Search queries are executed at Cluster level.
As of Couchbase Server 7.6, they can also be executed at the Scope level.

Here is a simple MatchQuery that looks for the text “swanky” using a defined index:

[source,csharp]
----
// as a cluster-level search
include::example$Search.cs[tag=clusterFtsSearch,indent=0]

// as a scope-level search
include::example$Search.cs[tag=scopedFtsSearch,indent=0]
----



All simple query types are created in the same manner, some have additional properties, which can be seen in common query type descriptions.
Couchbase Search Service's xref:{version-server}@server:fts:fts-query-types.adoc[range of query types] enable powerful searching using multiple options, to ensure results are just within the range wanted.
Here is a date range query that looks for dates between 1st January 2021 and 31st January:

[source,csharp]
----
include::example$Search.cs[tag=scopedDateSearch,indent=0]
----

A conjunction query contains multiple child queries; its result documents must satisfy all of the child queries:

[source,csharp]
----
include::example$Search.cs[tag=scopedConjunctionSearch,indent=0]
----

[TIP]
.Search Results Limit
====
By default, the Search Service returns only the first 10 matches (`size: 10`, `from: 0`).
To retrieve more results, you must explicitly define pagination settings such as `size` or `from` in your query.

For information about formatting your Search query and specifying limits, see xref:server:search:search-request-params.adoc[].

For information about pagination in Search responses, see xref:server:fts:fts-search-response.adoc#pagination[Pagination].
====


== Working with Results

The result of a search query has three components: hits, facets, and metdata.
Hits are the documents that match the query.
Facets allow the aggregation of information collected on a particular result set.
Metdata holds additional information not directly related to your query,
such as success total hits and how long the query took to execute in the cluster.

[source,csharp]
.Iterating hits
----
include::example$Search.cs[tag=scopedEnumerateHits,indent=0]
----

[source,csharp]
.Iterating facets
----
include::example$Search.cs[tag=scopedEnumerateFacets,indent=0]
----


== Consistency

Like the Couchbase Query Service,
Search Service allows `RequestPlus` queries -- _Read-Your-Own_Writes (RYOW)_ consistency, ensuring results contain information from updated indexes:

[source,csharp]
----

include::example$Search.cs[tag=scopedConsistentWithSearch,indent=0]
----

== Scoped vs Global Indexes
The Search APIs exist at both the `Cluster` and `Scope` levels.

This is because Search Service supports, as of Couchbase Server 7.6, a new form of "scoped index" in addition to the traditional "global index".

It's important to use the `Cluster.SearchAsync()` for global indexes, and `Scope.SearchAsync()` for scoped indexes.
(`Cluster.SearchQueryAsync()` is still available for compatibility with earlier versions of the SDK)






