= Search
:description: You can use the Full Text Search service (FTS) to create queryable full-text indexes in Couchbase Server, including Vector searches.
:page-topic-type: howto
:page-pagination: full

include::project-docs:partial$attributes.adoc[]

[abstract]
{description}



Full Text Search or FTS allows you to create, manage, and query full text indexes on JSON documents stored in Couchbase buckets.
It uses natural language processing for querying documents, provides relevance scoring on the results of your queries, and has fast indexes for querying a wide range of possible text searches.
Some of the supported query types include simple queries like Match and Term queries; range queries like Date Range and Numeric Range; and compound queries for conjunctions, disjunctions, and/or boolean queries.
The .NET SDK exposes an API for performing FTS queries which abstracts some of the complexity of using the underlying REST API.


// As of Couchbase Server 6.5, FTS...


The Full Text Search service also supports vector search from Couchbase Server 7.6 onwards.


== Examples

There are two APIs for querying search: `cluster.searchQuery()`, and `cluster.search()`.
Both are also available at the Scope level.

The former API supports FTS queries (`SearchQuery`), while the latter additionally supports the `VectorSearch` added in 7.6.
Most of this documentation will focus on the former API, as the latter is in @Stability.Volatile status.

We will perform an FTS query here - see the <<vector search>> section for examples of that.
In this case a simple MatchQuery that looks for the text “swanky” using a defined index at the cluster level:

[source,csharp]
----
var result = cluster.SearchQuery(
    "travel-sample-index-hotel-description",
    new MatchQuery("swanky"),
    options => {
        options.WithLimit(10);
    }
);
----

All simple query types are created in the same manner, some have additional properties, which can be seen in common query type descriptions.
Couchbase FTS's xref:7.1@server:fts:fts-query-types.adoc[range of query types] enable powerful searching using multiple options, to ensure results are just within the range wanted.
Here is a date range query that looks for dates between 1st January 2021 and 31st January:

[source,csharp]
----
var result = cluster.SearchQuery(
    "index-name",
    new DateRangeQuery()
        .Start(DateTime.Parse("2021-01-01"), true) // final parameter is if the range is inclusive
        .End(DateTime.Parse("2021-02-01"), false),
    options => options.Limit(10)
);
----

A conjunction query contains multiple child queries; its result documents must satisfy all of the child queries:

[source,csharp]
----
var result = cluster.SearchQuery(
    "index-name",
    new ConjunctionQuery(
        new DateRangeQuery()
            .Start(DateTime.Parse("2021-01-01"), true)
            .Start(DateTime.Parse("2021-02-01"), false),
        new MatchQuery("Swanky")
);
----

== Working with Results

The result of a search query has three components: hits, facets, and metdata.
Hits are the documents that match the query.
Facets allow the aggregation of information collected on a particular result set.
Metdata holds additional information not directly related to your query,
such as success total hits and how long the query took to execute in the cluster.

[source,csharp]
.Iterating hits
----
foreach (var hit in result.Hits)
{
    string documentId = hit.Id;
    double score = hit.Score;
    ...
}
----

[source,csharp]
.Iterating facets
----
foreach (var facet in result.Facets)
{
    var name = facet.Name;
    var total = facet.Total;
    ...
}
----


== Scoped vs Global Indexes
The FTS APIs exist at both the `Cluster` and `Scope` levels.

This is because FTS supports, as of Couchbase Server 7.6, a new form of "scoped index" in addition to the traditional "global index".

It's important to use the `Cluster.searchQuery()` / `Cluster.search()` for global indexes, and `Scope.searchQuery()` / `Scope.search()` for scoped indexes.

== Vector Search
As of Couchbase Server 7.6, the FTS service supports vector search in additional to traditional full text search queries.
// todo link to the server docs when available

=== Examples
==== Single vector query
In this first example we are performing a single vector query:
[source,java]
----
SearchRequest request = SearchRequest
        .create(VectorSearch.create(VectorQuery.create("vector_field", vectorQuery)));

SearchResult result = scope.search("travel-sample-index", request);
----

Let's break this down.
We create a `SearchRequest`, which can contain a traditional FTS query `SearchQuery` and/or the new `VectorSearch`.
Here we are just using the latter.

The `VectorSearch` allows us to perform one or more `VectorQuery` s.

The `VectorQuery` itself takes the name of the document field that contains embedded vectors ("vector_field" here), plus actual vector query in the form of a `float[]`.

(Note that Couchbase itself is not involved in generating the vectors, and these will come from an external source such as an embeddings API.)

Finally we execute the `SearchRequest` against the FTS index "travel-sample-index", which has previously been setup to vector index the "vector_field" field.

This happens to be a scoped index so we are using `scope.search()`.
If it was a global index we would use `cluster.search()` instead - see <<Scoped vs Global Indexes>>.

It returns the same `SearchResult` detailed earlier.

==== Multiple vector queries
You can run multiple vector queries together:

[source,java]
----
SearchRequest request = SearchRequest
        .create(VectorSearch.create(List.of(
                        VectorQuery.create("vector_field", vectorQuery).numCandidates(2).boost(0.3),
                        VectorQuery.create("vector_field", anotherVectorQuery).numCandidates(5).boost(0.7)));

SearchResult result = scope.search("travel-sample-index", request);
----

How the results are combined (ANDed or ORed) can be controlled with `vectorSearchOptions().vectorQueryCombination()`.

==== Combining FTS and vector queries
You can combine a traditional FTS query with vector queries:

[source,java]
----
SearchRequest request = SearchRequest.create(SearchQuery.matchAll())
        .vectorSearch(VectorSearch.create(VectorQuery.create("vector_field", vectorQuery)));

SearchResult result = scope.search("travel-sample-index", request);
----

How the results are combined (ANDed or ORed) can be controlled with `vectorSearchOptions().vectorQueryCombination()`.

==== FTS queries
And note that traditional FTS queries, without vector search, are also supported with the new `cluster.search()` / `scope.search()` APIs:

[source,java]
----
SearchRequest request = SearchRequest.create(SearchQuery.matchAll());

SearchResult result = scope.search("travel-sample-index", request);
----

The `SearchQuery` is created in the same way as detailed earlier.


== Consistency

Like the Couchbase Query Service,
FTS allows `RequestPlus` queries -- _Read-Your-Own_Writes (RYOW)_ consistency, ensuring results contain information from updated indexes:

[source,csharp]
----
var result = cluster.SearchQuery(
    "travel-sample-index-hotel-description",
    new MatchQuery("swanky"),
    options => {
        options.WithConsistency(ScanConsistency.RequestPlus);
    }
);
----
