= Data Operations
:description: Data service offers the simplest way to retrieve or mutate data where the key is known. Here we cover CRUD operations, document expiration, and optimistic locking with CAS.
:page-topic-type: howto
:page-aliases: document-operations.adoc,durability.adoc
:page-toclevels: 2
:page-pagination: full

include::project-docs:partial$attributes.adoc[]

[abstract]
{description}


// The complete code sample used on this page can be downloaded from
//  xref::example$document.cs[here]
// - from which you can see in context how to authenticate and connect to a Couchbase Cluster, then perform these Bucket operations.


== Documents

A _document_ refers to an entry in the database (other databases may refer to the same concept as a _row_).
A document has an ID (_primary key_ in other databases), which is unique to the document and by which it can be located.
The document also has a value which contains the actual application data.
See xref:concept-docs:documents.adoc[the concept guide to _Documents_] for a deeper dive into documents in the Couchbase Data Platform.
Or read on, for a hands-on introduction to working with documents from the .NET SDK.

== CRUD Operations

The core interface to Couchbase Server is simple KV operations on full documents.
Make sure you're familiar with the basics of authorization and connecting to a Cluster from the xref:hello-world:start-using-sdk.adoc[Start Using the SDK section].
We're going to expand on the short _Upsert_ example we used there, adding options as we move through the various CRUD operations.
Here is the _Insert_ operation at its simplest:

.Insert
[source,csharp]
----
include::example$KvOperations.csx[tag=insert,indent=0]
----

Options may be added to operations:

.Insert (with options)
[source,csharp]
----
include::example$KvOperations.csx[tag=insertwithoptions,indent=0]
----

Setting a Compare and Swap (CAS) value is a form of optimistic locking - dealt with in depth in the xref:concurrent-document-mutations.adoc[CAS page].
Here we just note that the CAS is a value representing the current state of an item; each time the item is modified, its CAS changes.
The CAS value is returned as part of a document’s metadata whenever a document is accessed.
Without explicitly setting it, a newly-created document would have a CAS value of _0_.

_Timeout_ is an optional parameter which in the .NET SDK has a type value of `TimeSpan`.
Timeout sets the timeout value for the underlying network connection.
We will add to these options for the _Replace_ example:

[source,csharp]
----
include::example$KvOperations.csx[tag=replacewithcas,indent=0]
----

Expiration sets an explicit time to live (TTL) for a document.
We'll discuss modifying `Expiration` in more details xref:#expiration-ttl[below].
For a discussion of item (Document) _vs_ Bucket expiration, see the
xref:7.1@server:learn:buckets-memory-and-storage/expiration.adoc#expiration-ttl[Expiration Overview page].

[source,csharp]
----
include::example$KvOperations.csx[tag=upsertwithtimeout,indent=0]
----

Here, we have add _Durability_ options, namely `PersistTo` and `ReplicateTo`.

== Durability

In Couchbase Server releases before 6.5, Durability was set with these two options -- see the xref:https://docs.couchbase.com/dotnet-sdk/2.7/durability.html[6.0 Durability documentation] -- covering  how many replicas the operation must be propagated to and how many persisted copies of the modified record must exist.
If 6.5 or above is being used, you can take advantage of the xref:concept-docs:durability-replication-failure-considerations.adoc#durable-writes[Durable Write] feature,
in which Couchbase Server will only return success to the SDK after the requested replication level has been achieved.
The three replication levels are:

 * `Majority` - The server will ensure that the change is available in memory on the majority of configured replicas.
 * `MajorityAndPersistToActive` - Majority level, plus persisted to disk on the active node.
 * `PersistToMajority` - Majority level, plus persisted to disk on the majority of configured replicas.

The options are in increasing levels of safety.
Note that nothing comes for free - for a given node, waiting for writes to storage is considerably slower than waiting for it to be available in-memory.
These trade offs, as well as which settings may be tuned, are discussed in the xref:concept-docs:durability-replication-failure-considerations.adoc#durable-writes[durability page].

The following example demonstrates using the newer durability features available in Couchbase server 6.5 onwards.

[source,csharp]
----
include::example$KvOperations.csx[tag=upsertwithdurability,indent=0]
----

If a version of Couchbase Server earlier than 6.5 is being used then the application can fall-back to xref:concept-docs:durability-replication-failure-considerations.adoc#older-server-versions['client verified' durability].
Here the SDK will do a simple poll of the replicas and only return once the requested durability level is achieved.

////
This can be achieved like this:

[source,golang]
----
// Durability observed snippet
----
////

To stress, durability is a useful feature but should not be the default for most applications, as there is a performance consideration,
and the default level of safety provided by Couchbase will be reasonable for the majority of situations.


[TIP]
.Sub-Document Operations
====
All of these operations involve fetching the complete document from the Cluster.
Where the number of operations or other circumstances make bandwidth a significant issue, the SDK can work on just a specific _path_ of the document with xref:subdocument-operations.adoc[Sub-Docunent Operations].
====

== Retrieving full documents

Using the `GetAsync()` method with the document key can be done in a similar fashion to the other operations:

[source,csharp]
----
include::example$KvOperations.csx[tag=get,indent=0]
----

Timeout can also be set - as in the earlier `Insert` example:

.Get (with options)
[source,csharp]
----
include::example$KvOperations.csx[tag=getwithtimeout,indent=0]
----

== Removing

When removing a document, you will have the same concern for durability as with any additive modification to the Bucket:

.Remove (with options)
[source,csharp]
----
include::example$KvOperations.csx[tag=remove,indent=0]
----

== Expiration / TTL

By default, Couchbase documents do not expire, but transient or temporary data may be needed for user sessions, caches, or other temporary documents.
Using `Touch()`, you can set expiration values on documents to handle transient data:

[source,csharp]
----
include::example$KvOperations.csx[tag=touch,indent=0]
----

A network timeout can be set with the optional `TouchOptions()`, in the same fashion as earlier examples on this page:

[source,csharp]
----
include::example$KvOperations.csx[tag=touchwithtimeout,indent=0]
----

include::{version-common}@sdk:shared:partial$documents.adoc[tag=exp-note]

IMPORTANT: If you are using the overloads that take `IDocument`, note that the `IDocument.Expiry` property assumes ms (milli-seconds), and is converted to seconds before being sent to the server.
All other overloads take a `TimeSpan` or an `uint`, and assume an expiry in seconds
A time of zero will set the document to never expire
(a negative number will set expiry to immediate -- creating a xref:7.1@server:learn:buckets-memory-and-storage/storage.adoc#tombstones[tombstone]).
Values above 0ms but below 1000ms are rounded up to one second before being sent to the server -- _if you are using .NET SDK 3.0.4 or later_.


== Atomic Counters

The value of a document can be increased or decreased atomically using `Binary.Increment()` and `Binary.Decrement()`.

NOTE: Increment & Decrement are considered part of the ‘binary’ API and as such may still be subject to change

.Increment
[source,csharp]
----
include::example$KvOperations.csx[tag=binaryincrement,indent=0]
----

.Increment (with options)
[source,csharp]
----
include::example$KvOperations.csx[tag=binaryincrementwithoptions,indent=0]
----

.Decrement
[source,csharp]
----
include::example$KvOperations.csx[tag=binarydecrement,indent=0]
----

.Decrement (with options)
[source,csharp]
----
include::example$KvOperations.csx[tag=binarydecrementwithoptions,indent=0]
----

TIP: Setting the document expiry time only works when a document is created, and it is not possible to update the expiry time of an existing counter document with the Increment method -- to do this during an increment, use with the `Touch()` method.

include::{version-common}@sdk:shared:partial$atomic.adoc[tag=xdcr]


== Scoped KV Operations

It is possible to perform scoped key value operations on named xref:7.1@server:learn:data/scopes-and-collections.adoc[`Collections`] with _Couchbase Server release 7.0_ onwards.

Here is an example showing an upsert in the `users` collection, which lives in the `travel-sample.tenant_agent_00` keyspace:

[source,csharp]
----
include::example$KvOperations.csx[tag=named-collection-upsert,indent=0]
----


[#kv-range-scan]
== KV Range Scan

A range scan gives you documents from a collection, even if you don't know the document IDs.
This feature requires Couchbase Server 7.6 or newer.

TIP: KV range scan is suitable for use cases that require relatively low concurrency and tolerate relatively high latency.
If your application does many scans at once, or requires low latency results, we recommend using {sqlpp} (with a primary index on the collection) instead of KV range scan.


[#kv-range-scan-range]
=== Range scan

Here's an example of a KV range scan that gets all documents in a collection:

.KV Range Scan for all documents in a collection
[source,csharp]
----
include::example$Couchbase.Examples.KV/RangeScan/RangeScan/Program.cs[tag=rangeScanAllDocuments,indent=0]
----
<1> The `RangeScan()` constructor has two optional nullable parameters: `from` and `to`.
If you pass null like in this example, you'll get all documents in the collection.
These parameters are for advanced use cases; you probably won't need to specify them.
Instead, it's more common to use the "prefix" scan type shown in the next example.

[#kv-range-scan-prefix]
=== Prefix scan

KV range scan can also give you all documents whose IDs start with the same prefix.

Imagine you have a collection where documents are named like this: `<username>::<uuid>`.
In other words, the document ID starts with the name of the user associated with the document, followed by a delimiter, and then a UUID.
If you use this document naming scheme, you can use a prefix range scan to get all documents associated with a user.

For example, to get all documents associated with user "alice", you would write:

.KV Range Scan for all documents in a collection whose IDs start with "alice::"
[source,csharp]
----
include::example$Couchbase.Examples.KV/RangeScan/RangeScan/Program.cs[tag=rangeScanPrefix,indent=0]
----
<1> Note the scan type is *prefixScan*.

[#kv-range-scan-sample]
=== Sample scan

If you want to get random documents from a collection, use a sample scan.

.KV Range Scan for 100 random documents
[source,csharp]
----
include::example$Couchbase.Examples.KV/RangeScan/RangeScan/Program.cs[tag=rangeScanSample,indent=0]
----
<1> In this example, no more than `100` documents are returned.

[#kv-range-scan-only-ids]
=== Get IDs instead of full document

If you only want the document IDs, set the `idsOnly` option to true, like this:

.KV Range Scan for all document IDs in a collection
[source,csharp]
----
include::example$Couchbase.Examples.KV/RangeScan/RangeScan/Program.cs[tag=rangeScanAllDocumentIds,indent=0]
----
<1> The returned `ScanResult` objects throw `NoSuchElementException` if you try to access any property other than `Id`.

Setting `IdsOnly` to true also works with the other scan types described above.


== Additional Resources

Working on just a specific path within a JSON document will reduce network bandwidth requirements - see the xref:subdocument-operations.adoc[Sub-Document] pages.

Another way of increasing network performance is to _pipeline_ operations with xref:concurrent-async-apis.adoc#batching[Batching Operations].

As well as various xref:concept-docs:data-model.adoc[Formats] of JSON, Couchbase can work directly with xref:concept-docs:nonjson.adoc[arbitary bytes, or binary format].

Our xref:n1ql-queries-with-sdk.adoc[Query Engine] enables retrieval of information using the SQL-like syntax of {sqlpp} (formerly N1QL).
