= Managing Connections using the .NET SDK with Couchbase Server
:navtitle: Managing Connections
:page-topic-type: howto
:page-aliases: ROOT:managing-connections,howtos:multi-network,ROOT:connecting,ROOT:connection-advanced

[abstract]
This section describes how to connect the .NET SDK to a Couchbase cluster.
It contains best practices as well as information on TLS/SSL and other advanced connection options.

== Connecting to a Cluster

A connection to a Couchbase Server cluster is represented by a `Cluster` object.
A `Cluster` provides access to Buckets, Scopes, and Collections, as well as various Couchbase services and management interfaces.
The simplest way to create a `Cluster` object is to call `Cluster.ConnectAsync()` with a <<connection-strings, connection string>>, username, and password:

[source,c#]
----
include::example$ManagingConnections.cs[tag=simpleconnect,indent=0]
----

NOTE: If you are connecting to a version of Couchbase Server older than 6.5, it will be more efficient if the addresses are those of data (KV) nodes.
You will in any case, with 6.0 and earlier, need to open a ``Bucket` instance before connecting to any other HTTP services (such as _Query_ or _Search_.

In a production environment, your connection string should include the addresses of multiple server nodes in case some are currently unavailable.
Multiple addresses may be specified in a connection string by delimiting them with commas:

[source,c#]
----
include::example$ManagingConnections.cs[tag=multinodeconnect,indent=0]
----

TIP: You don't need to include the address of every node in the cluster.
The client fetches the full address list from the first node it is able to contact.

[#connection-strings]
== Connection Strings

A Couchbase connection string is a comma-delimited list of IP addresses and/or hostnames, optionally followed by a list of parameters.

The parameter list is just like the query component of a URI; name-value pairs have an equals sign (`=`) separating the name and value, with an ampersand (`&`) between each pair.
Just as in a URI, the first parameter is prefixed by a question mark (`?`).

.Simple connection string with one seed node
----
127.0.0.1
----

.Connection string with two seed nodes
----
nodeA.example.com,nodeB.example.com
----

.Connection string with two parameters
----
127.0.0.1?io.networkResolution=external&timeout.kvTimeout=10s
----

Currently, as of .NET SDK Version 3.0.2 there is only partial mapping of query parameters to options properties. 
This will change in future versions and the entire list of mappings will be found in the client settings reference.

A connection string may optionally be prefixed by either `"couchbase://"` or `"couchbases://"`. If `"couchbases://"` is used, the client will use secure connections (TLS/SSL) if a valid certificate is configured or you can use the `ClusterOptions.EnableTls` flag.
// as described in <<ssl>> to do the same.

[#connection-lifecycle]
== Connection Lifecycle

Most of the high-level classes in the .NET SDK are designed to be safe for concurrent use by multiple threads.
You will get the best performance if you share and reuse instances of `Cluster`, `Bucket`, `Scope`, and `Collection`, all of which are thread-safe.

We recommend creating a single `Cluster` instance when your application starts up, and sharing this instance throughout your application.
If you know at startup time which buckets, scopes, and collections your application will use, we recommend obtaining them from the `Cluster` at startup time and sharing those instances throughout your application as well.

Before your application stops, gracefully shut down the client by calling the `Dispose` method of each `Cluster` you created. 
In older applications this can be done in Application_Start and Application_End in your Global.asax file. 
For newer applictions we suggest using Dependency Injection and Startup.cs file.


[#connection-di]
== Dependency Injection

There is a special .NET Core style Dependency Injection (DI) framework for Cluster and Buckets. 
It simplifies cluster configuration, lifetime management, and bucket injection. 
You can find it on NuGet.org: https://www.nuget.org/packages/Couchbase.Extensions.DependencyInjection/[NuGet package^]. 
Or using the NuGet Package Manager, add the dependency directly to your project:

NOTE: Install-Package Couchbase.Extensions.DependencyInjection -Version 3.0.0

=== Adding Couchbase To The Services Collection

The easiest way to get started in a Web application is to use the `ConfigureService` method in the Services.cs:

[source,c#]
----
include::example$WebStartupDI.cs[tag=configureservices,indent=0]
----

=== Injecting Couchbase Buckets

To get a couchbase bucket, simply inject `IBucketNamedProvider` and call `GetBucketAsync`. 
Be sure that you don't dispose the IBucket, it's a singleton that will be reused through the application.

[source,c#]
----
include::example$HomeControllerDI.cs[tag=namedbucketprovider,indent=0]
----

=== Simplifying Injecting Bucket Names

[source,c#]
----
include::example$mybucketproviderDI.cs[tag=mybucketprovider,indent=0]
----

To further simplify dependency injection, you can setup to inject specific buckets. 
First, create an interface for each bucket that inherits from `INamedBucketProvider`. 
This interface must be public and left empty.

You can then configure your bucket interfaces during IServiceCollection setup.

[source,c#]
----
include::example$WebStartupDI-IMyBucketProvider.cs[tag=configureservices,indent=0]
----

The interface you created can now be injected into controllers or business logic, and the `GetBucketAsync` method will return the specified bucket. 
You are no longer required to know the name of the bucket in the controller, improving separation of concerns in your application.

[source,c#]
----
include::example$HomeControllerDI.cs[tag=IMybucketprovider,indent=0]
----

=== Shutdown

During application shutdown it's best to close the Couchbase connections gracefully. 
You can do this using the `ICouchbaseLifetimeService`.` 
For Asp.Net Core, you can call this service from the `ApplicationStopped` cancellation token of `IHostApplicationLifetime`.

[source,c#]
----
include::example$WebStartupDI.cs[tag=configure,indent=0]
----

// Connecting to Couchbase cloud requires that `ClusterOptions.EnableTls` be set to true along with the `"couchbases://"` connection string pre-fix. Additionally, in certain situations `ClusterOptions.IgnoreRemoteCertificateNameMismatch` may also need to be true. Additionally, in certain situations `ClusterOptions.IgnoreRemoteCertificateNameMismatch` may also need to be true. 

== Waiting for Bootstrap Completion

Depending on the environment and network latency, bootstrapping the SDK fully might take a little longer than the default key-value timeout of 2.5 seconds, so you may see timeouts during bootstrap. 
To prevent those early timeouts from happening, you can use the `waitUntilReady` method.

If you are working at the _Cluster_ level, then add to the `cluster()` in the xref:#connecting-to-a-cluster[earlier example]:

[source,c#]
----
include::example$ManagingConnections.cs[tag=waitUntilReady,indent=0]
----

Or more fully:

[source,c#]
----
include::example$ClusterExample.cs[tag=waitUntilReady,indent=0]
----

If you are working at the _Bucket_ level, then the https://docs.couchbase.com/sdk-api/couchbase-net-client/html/M_Couchbase_IBucket_WaitUntilReadyAsync.htm-[Bucket-level `waitUntilReady`] does the same as the Cluster-level version,
_plus_ it waits for the K-V (data) sockets to be ready.

[source,c#]
----
include::example$ClusterExample.cs[tag=waitUntilReadyBucket,indent=0]
----

Other timeout issues may occur when using the SDK located geographically separately from the Couchbase Server cluster -- this is xref:project-docs:compatibility#network-requirements[not recommended].
See the xref:#working-in-the-cloud[Cloud section] below for some suggestions of settings adjustments.

// ******** cloud ********
include::6.5@sdk:shared:partial$managing-connections.adoc[tag=cloud]
