= Managing Connections using the .NET SDK with Couchbase Server
:navtitle: Managing Connections
:page-topic-type: howto
:page-aliases: ROOT:managing-connections,howtos:multi-network,ROOT:connecting,ROOT:connection-advanced,ROOT:cluster-helper

include::project-docs:partial$attributes.adoc[]

[abstract]
This section describes how to connect the .NET SDK to a Couchbase cluster.
It contains best practices as well as information on TLS/SSL and other advanced connection options.

== Connecting to a Cluster

A connection to a Couchbase Server cluster is represented by a `Cluster` object.
A `Cluster` provides access to Buckets, Scopes, and Collections, as well as various Couchbase services and management interfaces.
The simplest way to create a `Cluster` object is to call `Cluster.ConnectAsync()` with a <<connection-strings, connection string>>, username, and password:

[source,csharp]
----
include::example$ManagingConnections.cs[tag=simpleconnect,indent=0]
----

NOTE: If you are connecting to a version of Couchbase Server older than 6.5, it will be more efficient if the addresses are those of data (KV) nodes.
You will in any case, with 6.0 and earlier, need to open a ``Bucket` instance before connecting to any other HTTP services (such as _Query_ or _Search_.

In a production environment, your connection string should include the addresses of multiple server nodes in case some are currently unavailable.
Multiple addresses may be specified in a connection string by delimiting them with commas:

[source,csharp]
----
include::example$ManagingConnections.cs[tag=multinodeconnect,indent=0]
----

TIP: You don't need to include the address of every node in the cluster.
The client fetches the full address list from the first node it is able to contact.

[#connection-strings]
== Connection Strings

A Couchbase connection string is a comma-delimited list of IP addresses and/or hostnames, optionally followed by a list of parameters.

The parameter list is just like the query component of a URI; name-value pairs have an equals sign (`=`) separating the name and value, with an ampersand (`&`) between each pair.
Just as in a URI, the first parameter is prefixed by a question mark (`?`).

.Simple connection string with one seed node
----
127.0.0.1
----

.Connection string with two seed nodes
----
nodeA.example.com,nodeB.example.com
----

.Connection string with two parameters
----
127.0.0.1?io.networkResolution=external&timeout.kvTimeout=10s
----

Currently, as of .NET SDK Version 3.0.2 there is only partial mapping of query parameters to options properties.
This will change in future versions and the entire list of mappings will be found in the client settings reference.

A connection string may optionally be prefixed by either `"couchbase://"` or `"couchbases://"`. If `"couchbases://"` is used, the client will use secure connections (TLS/SSL) if a valid certificate is configured or you can use the `ClusterOptions.EnableTls` flag.
// as described in <<ssl>> to do the same.

[#connection-lifecycle]
== Connection Lifecycle

Most of the high-level classes in the .NET SDK are designed to be safe for concurrent use by multiple threads.
You will get the best performance if you share and reuse instances of `Cluster`, `Bucket`, `Scope`, and `Collection`, all of which are thread-safe.

We recommend creating a single `Cluster` instance when your application starts up, and sharing this instance throughout your application.
If you know at startup time which buckets, scopes, and collections your application will use, we recommend obtaining them from the `Cluster` at startup time and sharing those instances throughout your application as well.

Before your application stops, gracefully shut down the client by calling the `Dispose` method of each `Cluster` you created.
In older applications this can be done in Application_Start and Application_End in your Global.asax file.
For newer applictions we suggest using Dependency Injection and Startup.cs file.


[#connection-di]
== Dependency Injection

There is a special .NET Core style Dependency Injection (DI) framework for Cluster and Buckets.
It simplifies cluster configuration, lifetime management, and bucket injection.
You can find it on NuGet.org: https://www.nuget.org/packages/Couchbase.Extensions.DependencyInjection/[NuGet package^].
Or using the NuGet Package Manager, add the dependency directly to your project:

NOTE: Install-Package Couchbase.Extensions.DependencyInjection -Version 3.0.0

=== Adding Couchbase To The Services Collection

The easiest way to get started in a Web application is to use the `ConfigureService` method in the Services.cs:

[source,csharp]
----
include::example$WebStartupDI.cs[tag=configureservices,indent=0]
----

=== Injecting Couchbase Buckets

To get a couchbase bucket, simply inject `IBucketNamedProvider` and call `GetBucketAsync`.
Be sure that you don't dispose the IBucket, it's a singleton that will be reused through the application.

[source,csharp]
----
include::example$HomeControllerDI.cs[tag=namedbucketprovider,indent=0]
----

=== Simplifying Injecting Bucket Names

[source,csharp]
----
include::example$mybucketproviderDI.cs[tag=mybucketprovider,indent=0]
----

To further simplify dependency injection, you can setup to inject specific buckets.
First, create an interface for each bucket that inherits from `INamedBucketProvider`.
This interface must be public and left empty.

You can then configure your bucket interfaces during IServiceCollection setup.

[source,csharp]
----
include::example$WebStartupDI-IMyBucketProvider.cs[tag=configureservices,indent=0]
----

The interface you created can now be injected into controllers or business logic, and the `GetBucketAsync` method will return the specified bucket.
You are no longer required to know the name of the bucket in the controller, improving separation of concerns in your application.

[source,csharp]
----
include::example$HomeControllerDI.cs[tag=IMybucketprovider,indent=0]
----

=== Shutdown

During application shutdown it's best to close the Couchbase connections gracefully.
You can do this using the `ICouchbaseLifetimeService`.`
For Asp.Net Core, you can call this service from the `ApplicationStopped` cancellation token of `IHostApplicationLifetime`.

[source,csharp]
----
include::example$WebStartupDI.cs[tag=configure,indent=0]
----



////

[#alternate-addresses]
== Alternate Addresses and Custom Ports

If your Couchbase Server cluster is running in a containerized, port mapped, or otherwise NAT'd environment like Docker or Kubernetes, a client running outside that environment may need additional information in order to connect the cluster.
Both the client and server require special configuration in this case.

On the server side, each server node must be configured to advertise its external address as well as any custom port mapping.
This is done with the `setting-alternate-address` CLI command introduced in Couchbase Server 6.5.
A node configured in this way will advertise two addresses: one for connecting from the same network, and another for connecting from an external network.
// todo link to https://docs.couchbase.com/server/{version-server}/cli/cbcli/couchbase-cli-setting-alternate-address.html

On the client side, the externally visible ports must be used when connecting.
If the external ports are not the default, you can specify custom ports using the overloaded `Cluster.connect()` method that takes a set of `SeedNode` objects instead of a connection string.

// todo use the include (and uncomment in ManageingConnections.java) after next client snapshot is published
// include::example$ManagingConnections.java[tag=seednodes,indent=0]
[source,java]
----
int customKvPort = 1234;
int customManagerPort = 2345;
Set<SeedNode> seedNodes = new HashSet<>(Arrays.asList(
  SeedNode.create("127.0.0.1",
      Optional.of(customKvPort),
      Optional.of(customManagerPort))));

Cluster cluster = Cluster.connect(seedNodes, "username", "password");
----

TIP: In a deployment that uses multi-dimensional scaling, a custom KV port is only applicable for nodes running the KV service.
A custom manager port may be specified regardless of which services are running on the node.

In many cases the client is able to automatically select the correct set of addresses to use when connecting to a cluster that advertises multiple addresses.
If the detection heuristic fails in your environment, you can override it by setting the `io.networkResolution` client setting to `default` if the client and server are on the same network, or `external` if they're on different networks.

NOTE: Any TLS certificates must be set up at the point where the connections are being made.
// todo what does that mean in practice? Also, should this be in the TLS docs section instead?


////


[#ssl]
== Secure Connections

Couchbase Server Enterprise Edition supports full encryption of client-side traffic using Transport Layer Security (TLS). That includes key-value type operations, queries, and configuration communication. Make sure you have the Enterprise Edition of Couchbase Server before proceeding with configuring encryption on the client side.

To configure encryption for the .NET SDK:

 . Get the CA certificate from the cluster and save it in a text file.

 . Enable encryption on the client side and point it to the file containing the certificate.

It is important to make sure you are transferring the certificate in an encrypted manner from the server to the client side, so either copy it through SSH or through a similar secure mechanism.

If you are running on `localhost` and just want to enable TLS for a development machine, just copying and pasting it suffices
-- _so long as you use `127.0.0.1` rather than `localhost` in the connection string_.
This is because the certificate will not match the name _localhost_.
Setting `TLSSkipVerify` is a workaround if you need to use `couchbases://localhost`.

Navigate in the admin UI to menu:Settings[Cluster] and copy the input box of the TLS certificate into a file on your machine (which we will refer to as cluster.cert).
It looks similar to this:

----
-----BEGIN CERTIFICATE-----
MIICmDCCAYKgAwIBAgIIE4FSjsc3nyIwCwYJKoZIhvcNAQEFMAwxCjAIBgNVBAMT
ASowHhcNMTMwMTAxMDAwMDAwWhcNNDkxMjMxMjM1OTU5WjAMMQowCAYDVQQDEwEq
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzz2I3Gi1XcOCNRVYwY5R
................................................................
mgDnQI8nw2arBRoseLpF6WNw22CawxHVOlMceQaGOW9gqKNBN948EvJJ55Dhl7qG
BQp8sR0J6BsSc86jItQtK9eQWRg62+/XsgVCmDjrB5owHPz+vZPYhsMWixVhLjPJ
mkzeUUj/kschgQ0BWT+N+pyKAFFafjwFYtD0e5NwFUUBfsOyQtYV9xu3fw+T2N8S
itfGtmmlEfaplVGzGPaG0Eyr53g5g2BgQbi5l5Tt2awqhd22WOVbCalABd9t2IoI
F4+FjEqAEIr1mQepDaNM0gEfVcgd2SzGhC3yhYFBAH//8W4DUot5ciEhoBs=
-----END CERTIFICATE-----
----

The next step is to enable encryption and import the certificate.

[source,csharp]
----
include::example$ManagingConnections.cs[tag=enableTls,indent=0]
----

=== Importing the Certificate into Windows

For development, do the following steps to install the certificate:

 . Open Notepad or your favorite text editor using "Run as administrator".

 . Copy the contents of the certificate into the editor.

 . Save as type "All files" and specify the ".crt" file extension.

 . Right click on the file after saving it and click "Install Certificate".

 . Select "Current User" or "Local Machine" depending upon who you want to access the certificate.

 . Select "Next" and then store it as "Trusted Root Certificate Authority".


=== Importing the Certificate into MacOS

 . Copy the certificate into a text file with the extension ".crt".

 . Double click on the file and add it to "system" and approve with your password or fingerprint.

 . Double click on the file and expand the "trust" area, mark it as trusted instead of system default.

 . Exit and approve.



=== Importing the Certificate into GNU/Linux

Although different distributions differ slightly in the details of their certificate handling, they will be similar to one of the two patterns below.
Refer to your distribution's documentation for precise instructions.

[{tabs}]
====
Debian and Ubuntu::
+
--
[source,console]
----
$ cd /usr/local/share/ca-certificates/
----

Name a sub-directory to hold the Couchbase certificate:

[source,console]
----
$ mkdir couchbase-cert
----

[source,console]
----
$ cp /path/to/my-certificate.crt couchbase-cert/
----

.Ensure that the permissions are correct
[source,console]
----
$ chmod 755 couchbase-cert ; chmod 644 couchbase-cert/my-certificate.crt
----


.Update ca-certificates configuration to include the newly imported certificate
[source,console]
----
sudo dpkg-reconfigure ca-certificates
----

.Commit the changes
[source,console]
----
$ sudo update-ca-certificates
----
--

RHEL and CentOS::
+
--
[source,console]
----
$ sudo cp my-certificate.crt /etc/pki/ca-trust/source/anchors/
----

[source,console]
----
$ sudo update-ca-trust extract
----
--
====


=== Certificate Verification

If you want to verify it’s actually working, you can use a tool like *tcpdump*.
For example, an unencrypted upsert request looks like this (using `sudo tcpdump -i lo0 -A -s 0 port 11210`):

----
E..e..@.@.............+......q{...#..Y.....
.E...Ey........9........................id{"key":"value"}

After enabling encryption, you cannot inspect the traffic in cleartext (same upsert request, but watched on port 11207 which is the default encrypted port):

E.....@.@.............+....Z.'yZ..#........
..... ...xuG.O=.#.........?.Q)8..D...S.W.4.-#....@7...^.Gk.4.t..C+......6..)}......N..m..o.3...d.,.	...W.....U..
.%v.....4....m*...A.2I.1.&.*,6+..#..#.5
----



include::{version-server}@sdk:shared:partial$dnssrv-pars.adoc[tag=dnssrv]


== DNS SRV Bootstrapping

DNS SRV bootstrapping is available in the .NET SDK from version 2.1.0.
In order to make the SDK actually use the SRV records, you just need to pass in the host name from your records (here example.com):

[source,csharp]
----
include::example$ManagingConnections.cs[tag=dnssrv,indent=0]
----

If the DNS SRV records could not be loaded properly you’ll get the exception logged and the given host name will be used as a A record lookup.

----
    [INF] Error trying to retrieve DNS SRV entries. (addddf06)
    DnsClient.DnsResponseException: Query 63320 => _couchbase._tcp.10.143.200.101 IN SRV on 2001:4860:4860::8888:53 failed with an error.
----

Also, if you pass in more than one node, DNS SRV bootstrap will not be initiated and regular bootstrapping will occur.

// Connecting to Couchbase cloud requires that `ClusterOptions.EnableTls` be set to true along with the `"couchbases://"` connection string pre-fix. Additionally, in certain situations `ClusterOptions.IgnoreRemoteCertificateNameMismatch` may also need to be true. Additionally, in certain situations `ClusterOptions.IgnoreRemoteCertificateNameMismatch` may also need to be true.


== Waiting for Bootstrap Completion

Depending on the environment and network latency, bootstrapping the SDK fully might take a little longer than the default key-value timeout of 2.5 seconds, so you may see timeouts during bootstrap.
To prevent those early timeouts from happening, you can use the `waitUntilReady` method.

If you are working at the _Cluster_ level, then add to the `cluster()` in the xref:#connecting-to-a-cluster[earlier example]:

[source,csharp]
----
include::example$ManagingConnections.cs[tag=waitUntilReady,indent=0]
----

Or more fully:

[source,csharp]
----
include::example$ClusterExample.cs[tag=waitUntilReady,indent=0]
----

If you are working at the _Bucket_ level, then the https://docs.couchbase.com/sdk-api/couchbase-net-client/html/M_Couchbase_IBucket_WaitUntilReadyAsync.htm[Bucket-level `waitUntilReady`] does the same as the Cluster-level version,
_plus_ it waits for the K-V (data) sockets to be ready.

[source,csharp]
----
include::example$ClusterExample.cs[tag=waitUntilReadyBucket,indent=0]
----

Other timeout issues may occur when using the SDK located geographically separately from the Couchbase Server cluster -- this is xref:project-docs:compatibility#network-requirements[not recommended].
See the xref:#working-in-the-cloud[Cloud section] below for some suggestions of settings adjustments.

// ******** cloud ********
include::{version-server}@sdk:shared:partial$managing-connections.adoc[tag=cloud]


== Additional Resources

* Our xref:howtos:sdk-authentication.adoc[Authentication] page covers connecting with LDAP and Certificate Authentication.
* Connecting from SDK to Couchbase Server is best done wih both being in the same LAN-like environment or Cloud _Availability Zone_.
This is not always possible at the development stage, where you may be using a local laptop for SDK development against a Couchbase Cloud Server, so help is available for timeout issues in such unsupported configurations in our xref:howtos:troubleshooting-cloud-connections.adoc[Troubleshooting Cloud Connections] page.
