= Provisioning Cluster Resources
:description: Provisioning cluster resources is managed at the collection or bucket level, depending upon the service affected.
:navtitle: Provisioning Cluster Resources
:page-aliases: ROOT:managing-clusters
:page-toclevels: 2

// API refs
:bucket-api-reference: pass:q[IBucketManager -- https://docs.couchbase.com/sdk-api/couchbase-net-client/api/Couchbase.Cluster.html#Couchbase_Cluster_Buckets[`Cluster.Buckets`]]
:user-api-reference: pass:q[IUserManager -- https://docs.couchbase.com/sdk-api/couchbase-net-client/api/Couchbase.Cluster.html#Couchbase_Cluster_Users[`Cluster.Users`]]
:query-api-reference: pass:q[IQueryIndexManager -- https://docs.couchbase.com/sdk-api/couchbase-net-client/api/Couchbase.Cluster.html#Couchbase_Cluster_QueryIndexes[`Cluster.QueryIndexes`]]
:analytics-api-reference: pass:q[IAnalyticsIndexManager -- https://docs.couchbase.com/sdk-api/couchbase-net-client/api/Couchbase.Cluster.html#Couchbase_Cluster_AnalyticsIndexes[`Cluster.AnalyticsIndexes`]]
:search-api-reference: pass:q[ISearchIndexManager -- https://docs.couchbase.com/sdk-api/couchbase-net-client/api/Couchbase.Cluster.html#Couchbase_Cluster_SearchIndexes[`Cluster.SearchIndexes`]]
:collection-api-reference: pass:q[ICouchbaseCollectionManager -- https://docs.couchbase.com/sdk-api/couchbase-net-client/api/Couchbase.IBucket.html#Couchbase_IBucket_Collections[`Bucket.Collections`]]
:view-api-reference: pass:q[IViewIndexManager -- https://docs.couchbase.com/sdk-api/couchbase-net-client/api/Couchbase.IBucket.html#Couchbase_IBucket_ViewIndexes[`Bucket.ViewIndexes`]]

// one-view-update-warning common partial
:upsertDesignDocument: pass:q[`UpsertDesignDocumentAsync` method]
:getDesignDocument: pass:q[`GetDesignDocumentAsync`]

include::project-docs:partial$attributes.adoc[]

[abstract]
{description}
Common use cases are outlined here, less common use cases are covered in the https://docs.couchbase.com/sdk-api/couchbase-net-client/api/index.html[API docs].

include::{version-common}@sdk:shared:partial$flush-info-pars.adoc[tag=management-intro]

The .NET SDK also comes with some convenience functionality for common Couchbase management requests.

Management operations in the SDK may be performed through several interfaces depending on the object:

* {bucket-api-reference}
* {user-api-reference}
* {query-api-reference}
* {analytics-api-reference}
* {search-api-reference}
* {collection-api-reference}
* {view-api-reference}

NOTE: When using a Couchbase version earlier than 6.5, you must create a valid Bucket connection using `Cluster.Bucket(name)` before you can use cluster level managers.


== Bucket Management

The `IBucketManager` interface may be used to create and delete buckets from the Couchbase cluster.
It is referenced via the `Cluster.Buckets` property.

[source,golang]
----
include::example$/ProvisioningResourcesBuckets.csx[tag=creatingBucketMgr,indent=0]
----

The `BucketSettings` object is used for creating or updating buckets, and for exposing information about existing buckets.

include::{version-common}@sdk:shared:partial$flush-info-pars.adoc[tag=update-bucket-warning]

Here is the list of parameters available:

|====
| Name | Description | Can be updated
| `Name string` | The name of the bucket, required for creation. | false
| `FlushEnabled boolean` | Enables flushing to be performed on this bucket (see the <<Flushing Buckets>> section below). | true
| `ReplicaIndexes boolean` | Whether or not to replicate indexes. | false
| `RamQuotaMB Int64` | How much memory should each node use for the bucket, required for creation. | true
| `NumReplicas Int32` | The number of replicas to use for the bucket. | true
| `BucketType BucketType` | The type of the bucket, required for creation. | false
| `EvictionPolicy EvictionPolicyType` | The type of the eviction to use for the bucket, defaults to `ValueOnly`. | true (note: changing will cause the bucket to restart causing temporary inaccessibility)
| `MaxTTL Int32` | The default maximum time-to-live to apply to documents in the bucket. (note: This option is only available for Couchbase and Ephemeral buckets in Couchbase Enterprise Edition.) | true
| `CompressionMode CompressionMode` | The compression mode to apply to documents in the bucket. (note: This option is only available for Couchbase and Ephemeral buckets in Couchbase Enterprise Edition.) | true
| `ConflictResolutionType ConflictResolutionType` | The conflict resolution type to apply to conflicts on the bucket, defaults to `SequenceNumber` | false
|====

The following example creates a "hello" bucket:

[source,csharp]
----
include::example$ProvisioningResourcesBuckets.csx[tag=createBucket,indent=0]
----

We can now get this bucket and update it to enable Flush:

[source,csharp]
----
include::example$ProvisioningResourcesBuckets.csx[tag=updateBucket,indent=0]
----

Once you no longer need to use the bucket, you can remove it:

[source,csharp]
----
include::example$ProvisioningResourcesBuckets.csx[tag=removeBucket,indent=0]
----

=== Flushing Buckets

include::{version-common}@sdk:shared:partial$flush-info-pars.adoc[tag=flush-intro]

You can flush a bucket in the SDK by using `FlushBucketAsync()`.

[source,csharp]
----
include::example$ProvisioningResourcesBuckets.csx[tag=flushBucket,indent=0]
----

The `Flush` operation may fail if the bucket does not have flush enabled, in that case it will return a `BucketIsNotFlushableException`.

== Collection Management

The CollectionManager interface may be used to create and delete scopes and collections from the Couchbase cluster.
It can be referenced via the `Bucket.Collections` property.
Refer to the https://docs.couchbase.com/sdk-api/couchbase-net-client/api/Couchbase.Management.Collections.ICouchbaseCollectionManager.html[`CollectionManager` API documentation]
for further details.

[source,csharp]
----
include::example$Couchbase.Examples/CollectionManager.cs[tag=create-collection-manager,indent=0]
----

You can create a scope:

[source,csharp]
----
include::example$Couchbase.Examples/CollectionManager.cs[tag=create-scope,indent=0]
----

You can then create a collection within that scope:

[source,csharp]
----
include::example$Couchbase.Examples/CollectionManager.cs[tag=create-collection,indent=0]
----

Finally, you can drop unneeded collections and scopes:

[source,csharp]
----
include::example$Couchbase.Examples/CollectionManager.cs[tag=drop-collection,indent=0]

include::example$Couchbase.Examples/CollectionManager.cs[tag=drop-scope,indent=0]

----

Note that the most minimal permissions to create and drop a Scope or Collection is
xref:server:learn:security/roles.adoc#manage-scopes[Manage Scopes]
along with xref:server:learn:security/roles.adoc#data-reader[Data Reader].

You can create users with the appropriate RBAC programmatically:

[source,csharp]
----
include::example$Couchbase.Examples/CollectionManager.cs[tag=scopeAdmin, indent=0]
----

You can enumerate Scopes and Collections using
the `CollectionManager` and the properties of the
`ScopeSpec` and `CollectionSpec` objects retrieved.

[source,csharp]
----
include::example$Couchbase.Examples/CollectionManager.cs[tag=listing-scope-collection,indent=0]
----

== Index Management

include::{version-common}@sdk:shared:partial$flush-info-pars.adoc[tag=index-management-intro]

=== QueryIndexManager

The `IQueryIndexManager` interface contains the means for managing indexes used for queries.
It can be referenced through the `Cluster.QueryIndexes` property.

[source,csharp]
----
include::example$QueryIndexManagerExample.csx[tag=creating-index-mgr,indent=0]
----

include::{version-common}@sdk:shared:partial$flush-info-pars.adoc[tag=query-index-manager-intro]

The example below shows how to create a simple primary index, restricted to a named scope and collection, by calling the `CreatePrimaryIndexAsync()` method.
Note that you cannot provide a named scope or collection separately, both must be set for the `IQueryIndexManager` to create an index on the relevant keyspace path. 

.Creating a primary index

[source,csharp]
----
include::example$QueryIndexManagerExample.csx[tag=primary,indent=0]
----

When a primary index name is not specified, the SDK will create the index as `#primary` by default.
However, if you wish to provide a custom name, you can simply set an `IndexName` property in the `CreatePrimaryQueryIndexOptions` class.

You may have noticed that the example also sets the `IgnoreIfExists` boolean flag. 
When set to `true`, this optional argument ensures that an error is not thrown if an index under the same name already exists.

Creating a _secondary_ index follows a similar approach, with some minor differences:

.Creating a secondary index

[source,csharp]
----
include::example$QueryIndexManagerExample.csx[tag=secondary,indent=0]
----

The `CreateIndexAsync()` method requires an index name to be provided, along with the fields to create the index on.
Like the _primary_ index, you can restrict a _secondary_ index to a named scope and collection by passing some options.

Indexes can easily take a long time to build if they contain a lot of documents.
In these situations, it is more ideal to build indexes in the background.
To achieve this we can use the `Deferred` boolean option, and set it to `true`.

.Deferring index creation

[source,csharp]
----
include::example$QueryIndexManagerExample.csx[tag=defer-indexes,indent=0]
----

To delete a query index you can use the `DropIndexAsync()` or `DropPrimaryIndexAsync()` methods. 
Which one you use depends on the type of query index you wish to drop from the database.

.Deleting an index

[source,csharp]
----
include::example$QueryIndexManagerExample.csx[tag=drop-primary-or-secondary-index,indent=0]
----

// * Search - note & link to FTS page & API?

== View Management

include::{version-common}@sdk:shared:partial$flush-info-pars.adoc[tag=view-management]

In the SDK, design documents are represented by the `DesignDocument` and `View` classes.
All operations on design documents are performed on the `ViewIndexManager` instance:

[source,csharp]
----
include::example$ProvisioningResourcesViews.csx[tag=viewmgr,indent=0]
----

The following example upserts a design document with two views:

[source,csharp]
----
include::example$ProvisioningResourcesViews.csx[tag=createView,indent=0]
----

include::{version-common}@sdk:shared:partial$flush-info-pars.adoc[tag=one-view-update-warning]

Note the use of `DesignDocumentNamespace.Development`, the other option is `DesignDocumentNamespace.Production`.
This parameter specifies whether the design document should be created as development, or as production -- with the former running over only a small fraction of the documents.

Now that we've created a design document we can fetch it:

[source,csharp]
----
include::example$ProvisioningResourcesViews.csx[tag=getView,indent=0]
----

We've created the design document using `DesignDocumentNamespace.Development` and now want to push it to production, we can do this with:

[source,csharp]
----
include::example$ProvisioningResourcesViews.csx[tag=publishView,indent=0]
----

To remove this design document:

[source,csharp]
----
include::example$ProvisioningResourcesViews.csx[tag=removeView,indent=0]
----
