= Provisioning Cluster Resources
:navtitle: Provisioning Cluster Resources
:page-aliases: ROOT:managing-clusters

[abstract]
Provisioning cluster resources is managed at the collection or bucket level, depending upon the service affected.
Common use cases are outlined here, more recherché use cases are covered in the https://pkg.go.dev/github.com/couchbase/gocb/v2?tab=doc[API docs].

include::6.5@sdk:shared:partial$flush-info-pars.adoc[tag=management-intro]

The .NET SDK also comes with some convenience functionality for common Couchbase management requests.
////
Management operations in the SDK may be performed through several interfaces depending on the object:

* BucketManager -- `	IBucketManager`
* UserManager -- `IUserManager`
* QueryIndexManager -- `IQueryIndexManager`
* AnalyticsIndexManager -- `IAnalyticsIndexManager`
* SearchIndexManager -- `ISearchIndexManager`
* CollectionManager -- `ICouchbaseCollectionManager`
* ViewIndexManager -- `IViewIndexManager`.
////
NOTE: When using a Couchbase version earlier than 6.5, you must create a valid Bucket connection using `cluster.Bucket(name)` before you can use cluster level managers.


== Creating and Removing Buckets

The `ClusterManager` interface may be used to create and delete buckets from the Couchbase cluster.
It is instantiated through the `Cluster.Buckets()` method.
Refer to the https://docs.couchbase.com/sdk-api/couchbase-net-client/html/M_Couchbase_Cluster_BucketAsync.htm[API documentation] for details.

////
[source,golang,indent=0]
----
include::devguide:example$go/provisioning-resources-buckets.go[tag=creatingbucketmgr]
----
////

The `CreateBucketSettings` and `BucketSettings` structs are used for creating and updating buckets, `BucketSettings` is also used for exposing information about existing buckets.

include::6.5@sdk:shared:partial$flush-info-pars.adoc[tag=update-bucket-warning]

////
Here is the list of parameters available:

|====
| Name | Description | Can be updated
| `Name string` | The name of the bucket, required for creation. | false
| `FlushEnabled boolean` | Enables flushing to be performed on this bucket (see the <<go-flushing>> section below). | true
| `ReplicaIndexDisabled boolean` | Whether or not to replicate indexes. | false
| `RAMQuotaMB uint64` | How much memory should each node use for the bucket, required for creation. | true
| `NumReplicas uint32` | The number of replicas to use for the bucket. | true
| `BucketType BucketType` | The type of the bucket, required for creation. | false
| `EvictionPolicy EvictionPolicyType` | The type of the eviction to use for the bucket, defaults to `valueOnly`. | true (note: changing will cause the bucket to restart causing temporary inaccessibility)
| `MaxTTL time.Duration` | The default maximum time-to-live to apply to documents in the bucket. (note: This option is only available for Couchbase and Ephemeral buckets in Couchbase Enterprise Edition.) | true
| `CompressionMode CompressionMode` | The compression mode to apply to documents in the bucket. (note: This option is only available for Couchbase and Ephemeral buckets in Couchbase Enterprise Edition.) | true
| `ConflictResolutionType ConflictResolutionType` | The conflict resolution type to apply to conflicts on the bucket, defaults to `seqno` | false
|====

The following example creates a "hello" bucket:

[source,golang,indent=0]
----
include::devguide:example$go/provisioning-resources-buckets.go[tag=createBucket]
----

We can now get this bucket and update it to enable Flush:

[source,golang,indent=0]
----
include::devguide:example$go/provisioning-resources-buckets.go[tag=updateBucket]
----

Once you no longer need to use the bucket, you can remove it:

[source,golang,indent=0]
----
include::devguide:example$go/provisioning-resources-buckets.go[tag=removeBucket]
----
////

[#go-flushing]
== Flushing Buckets

include::6.5@sdk:shared:partial$flush-info-pars.adoc[tag=flush-intro]

You can flush a bucket in the SDK by using `FlushBucketAsync()`.

////
[source,golang,indent=0]
----
include::devguide:example$go/provisioning-resources-buckets.go[tag=flushBucket]
----

The `Flush` operation may fail if the bucket does not have flush enabled, in that case it will return an `ErrBucketNotFlushable`.
////

== Collection Management

[.status]#Developer Preview#

The CollectionManager interface may be used to create and delete scopes and collections from the Couchbase cluster.
It is instantiated through the `Bucket.collections()` method.
Refer to the https://docs.couchbase.com/sdk-api/couchbase-net-client/html/N_Couchbase_Management_Collections.htm[`CollectionManager` API documentation]
for further details.

[source,csharp]
----
include::example$Couchbase.Examples/CollectionManager.cs[tag=create-collection-manager,indent=0]
----

You can create a scope:

[source,csharp]
----
include::example$Couchbase.Examples/CollectionManager.cs[tag=create-scope,indent=0]
----

You can then create a collection within that scope:

[source,csharp]
----
include::example$Couchbase.Examples/CollectionManager.cs[tag=create-collection,indent=0]
----

Finally, you can drop unneeded collections and scopes:

[source,csharp]
----
include::example$Couchbase.Examples/CollectionManager.cs[tag=drop-collection,indent=0]

include::example$Couchbase.Examples/CollectionManager.cs[tag=drop-scope,indent=0]
----

Note that the most minimal permissions to create and drop a Scope or Collections is
xref:server:learn:security/roles.adoc#manage-scopes[Manage Scopes]
along with
xref:server:learn:security/roles.adoc#data-reader[Data Reader]

You can create users with the appropriate RBAC programmatically:

[source,csharp]
----
include::example$Couchbase.Examples/CollectionManager.cs[tag=scopeAdmin, indent=0]
----

////
== Index Management

In general,you will rarely need to work with Index Managers from the SDK.
For those occasions when you do, please see the relevant API docs:

* QueryIndexManager -- https://docs.couchbase.com/sdk-api/couchbase-net-client/html/N_Couchbase_Management_Query.htm[`IQueryIndexManager`];
* AnalyticsIndexManager -- https://docs.couchbase.com/sdk-api/couchbase-net-client/html/N_Couchbase_Management_Analytics.htm[`IAnalyticsIndexManager`];
* SearchIndexManager -- https://docs.couchbase.com/sdk-api/couchbase-net-client/html/N_Couchbase_Management_Search.htm[`ISearchIndexManager`];
* ViewIndexManager -- https://docs.couchbase.com/sdk-api/couchbase-net-client/html/N_Couchbase_Management_Views.htm[`IViewIndexManager`].
////

// * Query

// * Search - note & link to FTS page & API?

== View Management

include::6.5@sdk:shared:partial$flush-info-pars.adoc[tag=view-management]

In the SDK, design documents are represented by the `DesignDocument` and `View` structs.
All operations on design documents are performed on the `ViewIndexManager` instance:

////
[source,golang,indent=0]
----
include::devguide:example$go/provisioning-resources-views.go[tag=viewmgr]
----

The following example upserts a design document with two views:

[source,golang,indent=0]
----
include::devguide:example$go/provisioning-resources-views.go[tag=createView]
----

include::6.5@sdk:shared:partial$flush-info-pars.adoc[tag=one-view-update-warning]

Note the use of `DesignDocumentNamespaceDevelopment`, the other option is `DesignDocumentNamespaceProduction`.
This parameter specifies whether the design document should be created as development, or as production -- with the former running over only a small fraction of the documents.

Now that we've created a design document we can fetch it:

[source,golang,indent=0]
----
include::devguide:example$go/provisioning-resources-views.go[tag=getView]
----

We've created the design document using `DesignDocumentNamespaceDevelopment` and now want to push it to production, we can do this with:

[source,golang,indent=0]
----
include::devguide:example$go/provisioning-resources-views.go[tag=publishView]
----

To remove this design document:

[source,golang,indent=0]
----
include::devguide:example$go/provisioning-resources-views.go[tag=removeView]
----
////
