= Compatibility
:description: Features available in different SDK versions, and compatibility between Server and SDK. \
Plus notes on Cloud, networks, and AWS Lambda.
:page-aliases: ROOT:overview,ROOT:compatibility-versions-features,compatibility-versions-features
:page-toclevels: 2
:page-topic-type: reference

include::partial$attributes.adoc[]

[abstract]
{description}


== Couchbase Version/SDK Version Matrix

Couchbase SDKs are tested against a variety of different environments to ensure both backward and forward compatibility with different versions of Couchbase Server.
The matrix below denotes the version of Couchbase Server, the version of the .NET SDK and whether the SDK is:

* ✖ *Unsupported*: This combination is not tested, and is not within the scope of technical support if you have purchased a support agreement.
* ◎ *Compatible*: This combination has been tested previously, and should be compatible.
This combination is not recommended by our technical support organization.
It is best to upgrade either the SDK or the Couchbase version you are using.
* ✔ *Supported*: This combination is subject to ongoing quality assurance, and is fully supported by our technical support organization.

.Recommended SDK per Server Version Matrix
[#table_sdk_versions]
[cols="40,20,25,20"]
|===
| | SDK 3.0, 3.1 | SDK 3.2 | SDK 3.3, 3.4

| *Server 6.6*
| *✔*
| *✔*
| *✔*

| *Server 7.0 - 7.2*
| *◎*
| *✔*
| *✔*
|===

Note the https://www.couchbase.com/support-policy[End of Life dates^] for Couchbase Server and SDK versions.
See the notes there for Support details.

=== Capella Compatibility

The Couchbase .NET SDK is fully compatible with Couchbase Capella, our fully-hosted database-as-a-service.
To make development easier, the SDK includes the Capella client certificate ready installed.

include::{version-common}@sdk:shared:partial$capella.adoc[tag=cloud]


== Platform Compatibility

Microsoft's CLR eliminates many of the compatibility problems found in other languages, but occasional problems can be caused by the underlying Operating System (OS).
The Couchbase .NET SDK is tested and supported on the following platforms:

****
[discrete]
=== GNU/Linux

* Amazon Linux 2.
* Red Hat Enterprise Linux 7 & 8;
* CentOS 7 & 8.
* Ubuntu (LTS) 16.04 (_Xenial_), 18.04 (_Bionic_), & 20.04 (_Focal_).
* Debian 9 (_Stretch_) & 10 (_Buster_).
* Alpine Linux

[discrete]
=== Microsoft Windows

Microsoft Windows 10 / All LTS releases from Windows Server 2016.

[discrete]
=== Mac OS X

The current and previous two releases of OS X.
At time of writing (October 2022): 13 (Ventura), 12 (Monterey), and 11 (Big Sur).
M1 ARM  architecture is fully supported in the .NET SDK.
****

Although installable or compilable on many other platforms, we cannot provide support for untested combinations.

=== ARM Processor Support

AWS Amazon Graviton2, Apple M1 ARM processors, and ARMv8 on Ubuntu 20.04 (from SDK 3.4).


== Couchbase New Feature Availability Matrix

.Couchbase Server and SDK Supported Version Matrix
[.table-merge-cells]
[cols="7,5,6,5"]
|===
| | Server 6.6 | Server 7.0 | Server 7.1 - 7.2

| Enhanced Durability
3+| All SDK versions

| Durable Writes
3+| Since 3.0

| Analytics
3+| Since 2.7

| Distributed ACID Transactions
3+| Since 3.0 & Server 6.6footnote:[3.1.4 or more recent required for 1.0.0GA; preferably, use the latest SDK release.]

| Collections
| Developer Preview in 6.6, SDK 3.0
2+| Since 3.0.1

| Scope-Level {sqlpp} (formerly N1QL) Queries & all Collections features
| Not Supported
2+| Since SDK 3.2.0

| Field Level Encryption v2
3+| Since SDK 3.1.3footnote:[Field Level Encryption distributed as separate library.]

| Request Tracing
3+| Since SDK 3.0.3
|===

== .NET Framework Version Compatibility [[dotnet-compatibility]]

include::hello-world:partial$supported.adoc[]

.Recommended .NET Versions per SDK
[#table_sdk_versions]
[cols="40,20,25,20"]
|===
| | SDK 3.0 - 3.2 | SDK 3.3  | SDK 3.4

| .NET 5.0
| *✔*
| *✔*
| *✖*

| .NET 6.0 (Recommended)
| *✔*
| *✔*
| *✔*

| .NET 7.0
| *✖*
| *✖*
| *✖*

| .NET Framework 4.6.2+
| *✔*
| *✔*
| *✔*

| .NET Core 3.1 (Long Term Support)
| *✔*
| *✔*
| *✔*

| .NET Core 2.2, 3.0
| *◎* 
| *✖*
| *✖*
|===



include::{version-common}@sdk:shared:partial$network-requirements.adoc[]

include::{version-common}@sdk:shared:partial$interface-stability-pars.adoc[tag=interface-stability-section]

include::{version-common}@sdk:shared:partial$api-version.adoc[tag=api-version]

include::{version-common}@sdk:shared:partial$archive.adoc[tag=link]
