= Compatibility of Couchbase Features, Couchbase Server Versions, and the Couchbase .NET SDK
:description: Features available in different SDK versions, and compatibility between Server and SDK. \
Plus notes on Cloud, networks, and AWS Lambda.
:navtitle: Compatibility
:page-aliases: ROOT:overview,ROOT:compatibility-versions-features,compatibility-versions-features
:page-toclevels: 2

include::partial$attributes.adoc[]

[abstract]
{description}


== Couchbase Version/SDK Version Matrix

Couchbase SDKs are tested against a variety of different environments to ensure both backward and forward compatibility with different versions of Couchbase Server.
The matrix below denotes the version of Couchbase Server, the version of the .NET SDK and whether the SDK is:

* ✖ *Unsupported*: This combination is not tested, and is not within the scope of technical support if you have purchased a support agreement.
* ◎ *Compatible*: This combination has been tested previously, and should be compatible.
This combination is not recommended by our technical support organization.
It is best to upgrade either the SDK or the Couchbase version you are using.
* ✔ *Supported*:This combination is subject to ongoing quality assurance, and is fully supported by our technical support organization.

.Recommended SDK per Server Version Matrix
[#table_sdk_versions]
[cols="40,20,25,20"]
|===
| | SDK 3.0, 3.1 | SDK 3.2 | SDK 3.3

| *Server 6.0*
| *✔*
| *✔*
| *◎*


| *Server 6.5-6.6*
| *✔*
| *✔*
| *✔*

| *Server 7.0*
| *◎*
| *✔*
| *✔*


| *Server 7.1*
| *◎*
| *✔*
| *✔*
|===

Note the https://www.couchbase.com/support-policy[End of Life dates^] for Couchbase Server and SDK versions.
See the notes there for Support details.

=== Capella Compatibility

At time of release, the Couchbase 3.3 .NET SDK is fully compatible with Couchbase Capella, our fully-hosted database-as-a-service.
To make development easier, the 3.3 SDK includes the Capella client certificate ready installed.


== Platform Compatibility

Microsoft's CLR eliminates many of the compatibility problems found in other languages, but occasional problems can be caused by the underlying Opiratoeg System (OS).
The Couchbase .NET SDK is tested and supported on the following platforms:

****
[discrete]
=== GNU/Linux

* Amazon Linux 2.
* Red Hat Enterprise Linux 7 & 8;
* CentOS 7 & 8.
* Ubuntu (LTS) 16.04 (_Xenial_), 18.04 (_Bionic_), & 20.04 (_Focal_).
* Debian 9 (_Stretch_) & 10 (_Buster_).
* Alpine Linux

[discrete]
=== Microsoft Windows

Microsoft Windows 10 / All LTS releases from Windows Server 2016.

[discrete]
=== Mac OS X

The current and previous two releases of OS X.
At time of writing (April 2022): 10.15 (_Catalina_), 11 (_Big Sur_), and 12 (_Monterey_).
M1 ARM  architecture is fully supported in the 3.3 .NET SDK.
****

Although installable or compilable on many other platforms, we cannot provide support for untested combinations.

=== ARM Processor Support

The .NET 3.3 SDK supports AWS Amazon Graviton2 and Apple M1 ARM processors.


== Couchbase New Feature Availability Matrix

.Couchbase Server and SDK Supported Version Matrix
[.table-merge-cells]
[cols="7,7,5,6,5"]
|===
| | Server 6.0 | Server 6.5 & 6.6 | Server 7.0 | Server 7.1

| Enhanced Durability
4+| All SDK versions

| Durable Writes
| Not Supported
3+| Since 3.0

| Analytics
4+| Since 2.7

| Distributed ACID Transactions
| Not Supported
3+| Since 3.0 & Server 6.6footnote:[3.1.4 or more recent required for 1.0.0GA; preferably, use the latest SDK release.]

| Default Collections
| Not Supported
| Developer Preview in 6.5-6.6, SDK 3.0
2+| Since 3.0.1

| Scope-Level N1QL Queries & all Collections features
2+| Not Supported
2+| Since SDK 3.2.0

| Field Level Encryption v2
| Not Supported
3+| Since SDK 3.1.3footnote:[Field Level Encryption distributed as separate library.]

| Request Tracing
| Not Supported
3+| Since SDK 3.0.3
|===




== .NET Framework Version Compatibility [[dotnet-compatibility]]

include::hello-world:partial$supported.adoc[]

.Recommended .NET Versions per SDK
[#table_sdk_versions]
[cols="40,20,25,20"]
|===
| | SDK 3.0, 3.1 | SDK 3.2 | SDK 3.3

| .NET Core 3.1 (Long Term Support)
| *✔*
| *✔*
| *✔*

| .NET 5.0, 6.0 (Recommended)
| *✔*
| *✔*
| *✔*

| .NET Core 2.0, 2.1, 2.2, 3.0
| *◎*
| *◎* +
except *✖* 2.0, 2.1 xref:project-docs:sdk-release-notes.adoc#version-3-2-5-10-december-2021[from 3.2.5]
| *◎* +
except *✖* 2.0, 2.1 xref:project-docs:sdk-release-notes.adoc#version-3-2-5-10-december-2021[from 3.2.5]

| .NET Framework 4.6.2+
| *◎*
| *◎*
| *◎*

| .NET Core 1.0, 1.1
| *✖*
| *✖*
| *✖*

| .NET Framework 4.5.x, 4.6.0, 4.6.1
| *✖*
| *✖*
| *✖*

|===



include::{version-server}@sdk:shared:partial$network-requirements.adoc[]

include::{version-server}@sdk:shared:partial$interface-stability-pars.adoc[tag=interface-stability-section]

include::{version-server}@sdk:shared:partial$api-version.adoc[tag=api-version]

