= Compatibility
:description: Platform compatibility, and features available in different SDK versions, and compatibility between Server and SDK. \
Plus notes on Cloud, networks, and AWS Lambda.
:page-aliases: ROOT:overview,ROOT:compatibility-versions-features,compatibility-versions-features
:page-toclevels: 3
:table-caption!:


[abstract]
{description}


The Couchbase .NET SDK is compatible with https://docs.microsoft.com/en-us/dotnet/standard/net-standard[.NET Standard] 2.0 and .NET Standard 2.1, via the currently supported Microsoft .NET SDKs.


== Platform Compatibility




=== .NET Framework Version Compatibility [[dotnet-compatibility]]

include::hello-world:partial$supported.adoc[]

.Recommended .NET Versions per SDK
[#table_sdk_versions]
[cols="40,20,25"]
|===
| | SDK 3.0 - 3.3 | SDK 3.4

| .NET 6.0 (Long-Term Support)
| *✔*
| *✔*

| .NET 7.0
| *✖*
| *✖*

| .NET 8.0 (Recommended, Long-Term Support)
| *✖*
| *✔* From 3.4.14

| .NET Framework 4.6.2+
| *✔*
| *✔*
|===




=== OS Compatibility

Microsoft's CLR eliminates many of the compatibility problems found in other languages, but occasional problems can be caused by the underlying Operating System (OS).
The Couchbase .NET 3.4 SDK is tested and supported on the following platforms:

****
[discrete]
=== GNU/Linux

* Amazon Linux 2.
* Red Hat Enterprise Linux 7 & 8;
* CentOS 7 & 8.
* Ubuntu (LTS): 16.04 (_Xenial_), 18.04 (_Bionic_), 20.04 (_Focal_), & 22.04 (_Jammy_).
* Debian 9 (_Stretch_) & 10 (_Buster_).
* Alpine Linux

[discrete]
=== Microsoft Windows

Microsoft Windows 10 / All LTS releases from Windows Server 2016.

[discrete]
=== Mac OS X

The current and previous two releases of OS X.
At time of writing (October 2022): 13 (Ventura), 12 (Monterey), and 11 (Big Sur).
M1 ARM  architecture is fully supported in the .NET SDK as of .NET 6.0.
****

Although installable or compilable on many other platforms, we cannot provide support for untested combinations.

=== ARM Processor Support

AWS Amazon Graviton2, Apple M1 ARM processors, and ARMv8 on Ubuntu 20.04 (from SDK 3.4).

The .NET SDK should also be expected to run on other commonly-available GNU/Linux distributions which support an appropriate .NET Standard, but not all combinations can be tested -- notable exceptions are listed below.

////
==== Alpine Linux Compatibility

The https://netty.io[Netty] I/O library used by our JVM SDKs supports native optimizations to achieve higher throughput and lower latency 
-- which the SDK enables by default. 
Those modules are compiled against `glibc` and Alpine Linux uses `musl` instead --
so the {name-sdk} is unable to complete bootstrapping on this platform.

Because Alpine Linux does not have the `glibc` support needed,
we highly recommend that you seek an alternative distribution where possible. 
If that is not a option, then a possible workaround that can be applied is as follows:

* Disable the native IO:
+
[source,toml]
====
ClusterEnvironment env = ClusterEnvironment.builder().ioEnvironment(IoEnvironment.enableNativeIo(false)).build();
====

* Disable it in Netty itself via the following system property:
`-Dcom.couchbase.client.core.deps.io.netty.transport.noNative=true`

The downside of these workarounds is potentially reduced performance, which can be determined through benchmarking and profiling.
////



// Network Requirements
// uncomment include after 3.5
// include::7.5@sdk:shared:partial$network-requirements.adoc[]
// and remove below:


=== Network Requirements

Couchbase SDKs are developed to be run in an environment with local area network (LAN) like throughput and latencies.
While there is no technical issue that prevents the use across a wide area network (WAN), SDKs have certain thresholds around timeouts and behaviors to recover that will not be the same once the higher latency and possible bandwidth constraints and congestion of a WAN is introduced.
Couchbase tests for correctness under LAN like conditions.
For this reason, only LAN-like network environments are officially supported.

Couchbase does document, for purposes of convenience when developing and performing basic operational work, what may need to be tuned when network throughputs and latencies are higher.
If you encounter issues, even with these tune-ables, you should attempt the same workload from a supported, LAN-like environment.

==== Serverless Environments

SDK API 3.4 introduces better resilience in handling errors that may occur when running your application in serverless environments, in particular when processes are frozen or thawed, and a rebalance is required.
This means official support for AWS Lambda, Azure Functions, and GCP Functions.

NOTE: When *DNS SRV* records are used to connect to the SDK it is possible for the underlying addresses to change (i.e. the cluster could move).
The SDK will detect this and react accordingly so that your application can continue to work correctly.


// above^



== Couchbase Server Compatibility


Couchbase SDKs are tested against a variety of different environments to ensure both backward and forward compatibility with different versions of Couchbase Server.

=== Couchbase Version/SDK Version Matrix

The matrix below denotes the version of Couchbase Server, the version of the Scala SDK and whether the SDK is:

* ✖ *Unsupported*: This combination is not tested, and is not within the scope of technical support if you have purchased a support agreement.
* ◎ *Compatible*: This combination has been tested previously, and should be compatible.
This combination is not recommended by our technical support organization.
It is best to upgrade either the SDK or the Couchbase version you are using.
* ✔ *Supported*: This combination is subject to ongoing quality assurance, and is fully supported by our technical support organization.

.Recommended SDK per Server Version Matrix
[#table_sdk_versions]
|===
| | 3.2 | 3.3 | 3.4

| *Server 6.6*
| *✔*
| *✔*
| *✔*

| *Server 7.0 - 7.2*
| *✔*
| *✔*
| *✔*

| *Server 7.6*
| *✔*
| *✔*
| *3.4.9* ①
|===

<1> 3.4.9 is the recommended version to use with Server 7.6 (and newer instances of Capella, using 7.6).
Although it does not contain new APIs, such as vector search and support for 7.6 feature set, it is most compatible with Server 7.6.0. until SDK 3.5.x is released in the near future.
For compatibility of 3.4.11 - 3.4.15, please see https://issues.couchbase.com/browse/NCBC-3716[NCBC-3716].


If you are on SDK versions 3.4.11 - 3.4.15, we strongly encourage you to upgrade to .NET SDK v3.5.1+.
While these versions will continue be compatible and supported with server 7.6.0, you may encounter timeout exceptions during rebalances under KV high workload.
A workaround is to disable fast failover by setting `EnablePushConfig` to false in the `ExperimentalOptions` of the `ClusterOptions`:

+
[source,csharp]
----
var options = new ClusterOptions
{
    ConnectionString = "localhost"
    UserName = "Administrator",
    Password = "password",
};
options.Experiments.EnablePushConfig = false;
----

Note the https://www.couchbase.com/support-policy[End of Life dates^] for Couchbase Server and SDK versions.
See the notes there for Support details.

=== Capella Compatibility

The Couchbase Scala SDK is fully compatible with Couchbase Capella, our fully-hosted database-as-a-service.
To make development easier, the SDK includes the Capella client certificate ready installed.

include::{version-common}@sdk:shared:partial$capella.adoc[tag=cloud]


=== Couchbase New Feature Availability Matrix


.Couchbase Server and SDK Supported Version Matrix
[.table-merge-cells]
[cols="7,5,6,5"]
|===
| | Server 6.6 | Server 7.0 | Server 7.1 - 7.2

| Enhanced Durability
3+| All SDK versions

| Durable Writes
3+| Since 3.0

| Analytics
3+| Since 2.7

| Distributed ACID Transactions
3+| Since 3.0 & Server 6.6 ②

| Collections
| Developer Preview in 6.6, SDK 3.0
2+| Since 3.0.1

| Scope-Level {sqlpp} (formerly N1QL) Queries & all Collections features
| Not Supported
2+| Since SDK 3.2.0

| Field Level Encryption v2
3+| Since SDK 3.1.3 ③

| Request Tracing
3+| Since SDK 3.0.3
|===

② 3.1.4 or more recent required for 1.0.0GA; preferably, use the latest SDK release.

③ Field Level Encryption is distributed as a separate library.

=== API Version

include::{version-common}@sdk:shared:partial$api-version.adoc[tag=api-version]




== SDK API Stability


=== Interface Stability

include::{version-common}@sdk:shared:partial$interface-stability-pars.adoc[tag=interface-stability-section]


=== Older SDK Versions

include::{version-common}@sdk:shared:partial$archive.adoc[tag=link]
