= Compatibility
:description: Platform compatibility, and features available in different SDK versions, and compatibility between Server and SDK. \
Plus notes on Cloud, networks, and AWS Lambda.
:page-aliases: ROOT:overview,ROOT:compatibility-versions-features,compatibility-versions-features
:page-toclevels: 3
:table-caption!:


[abstract]
{description}


The Couchbase .NET SDK is compatible with https://docs.microsoft.com/en-us/dotnet/standard/net-standard[.NET Standard] 2.0 and .NET Standard 2.1, via the currently supported Microsoft .NET SDKs.


== Platform Compatibility




=== .NET Framework Version Compatibility [[dotnet-compatibility]]

include::hello-world:partial$supported.adoc[]

.Recommended .NET Versions per SDK
[#table_sdk_versions]
[cols="40,23,20,20,20"]
|===
| | SDK 3.5, 3.6 | SDK 3.7 | SDK 3.8 | SDK 3.9

| .NET 6.0 (Long-Term Support)
| *✔*
| *✖*
| *✖*
| *✖*

| .NET 7.0
| *✖*
| *✖*
| *✖*
| *✖*

| .NET 8.0
| *✔* 
| *✔*
| *✔*
| *✔*

| .NET 9.0
| *✖*
| *✖*
| *✖*
| *✖*

| .NET 10.0 (Recommended, Long-Term Support)
| *✖*
| *✖*
| *✖*
| *✔*

| .NET Framework 4.6.2+
| *✔*
| *✔*
| *✔*
| *✔*
|===


=== OS Compatibility

In general, the Common Language Runtime (CLR) eliminates concerns about underlying OS compatibility, 
and the Couchbase .NET SDK can be expected to run on all of the Operating Systems supported by xref:{version-server}@server:install:install-platforms.adoc[Couchbase Server].


// The {name-sdk} is tested and supported on the following OSs and platforms:
include::{version-common}@sdk:shared:partial$compat.adoc[tag=os-compat]


The .NET SDK should also be expected to run on other commonly-available GNU/Linux distributions which support an appropriate .NET Standard, but not all combinations can be tested -- notable exceptions are listed below.

////
==== Alpine Linux Compatibility

The https://netty.io[Netty] I/O library used by our JVM SDKs supports native optimizations to achieve higher throughput and lower latency 
-- which the SDK enables by default. 
Those modules are compiled against `glibc` and Alpine Linux uses `musl` instead --
so the {name-sdk} is unable to complete bootstrapping on this platform.

Because Alpine Linux does not have the `glibc` support needed,
we highly recommend that you seek an alternative distribution where possible. 
If that is not a option, then a possible workaround that can be applied is as follows:

* Disable the native IO:
+
[source,toml]
====
ClusterEnvironment env = ClusterEnvironment.builder().ioEnvironment(IoEnvironment.enableNativeIo(false)).build();
====

* Disable it in Netty itself via the following system property:
`-Dcom.couchbase.client.core.deps.io.netty.transport.noNative=true`

The downside of these workarounds is potentially reduced performance, which can be determined through benchmarking and profiling.
////



// Platforms, Chipsets, and Virtual Environments.
include::{version-common}@sdk:shared:partial$compat.adoc[tag=virtual]





// Network Requirements
include::{version-common}@sdk:shared:partial$compat[tag=network-requirements]



// Serverless Environments
include::{version-common}@sdk:shared:partial$compat[tag=serverless]








== Couchbase Server Compatibility


Couchbase SDKs are tested against a variety of different environments to ensure both backward and forward compatibility with different versions of Couchbase Server.

=== Couchbase Version/SDK Version Matrix

The matrix below denotes the version of Couchbase Server, the version of the .NET SDK and whether the SDK is:

* ✖ *Unsupported*: This combination is not tested, and is not within the scope of technical support if you have purchased a support agreement.
* ◎ *Compatible*: This combination has been tested previously, and should be compatible.
This combination is not recommended by our technical support organization.
It is best to upgrade either the SDK or the Couchbase version you are using.
* ✔ *Supported*: This combination is subject to ongoing quality assurance, and is fully supported by our technical support organization.

.Recommended SDK per Server Version Matrix
[#table_sdk_versions]
|===
| | 3.4 | 3.5 | 3.6 - 3.7 | 3.8 - 3.10'

| *Server 7.0 - 7.2*
| *✔*
| *✔*
| *✔*
| *✔*

| *Server 7.6*
| *✔* ①
| *✔*
| *✔*
| *✔*

| *Server 8.0*
| *◎* ①
| *◎*
| *✔*
| *✔*
|===

<1> If you are on SDK versions 3.4.11 - 3.4.15, we strongly encourage you to upgrade to .NET SDK v3.5.1+.
While these versions will continue be compatible and supported with server 7.6.0+, you may encounter timeout exceptions during rebalances under KV high workload.
3.6.1+ is recommended for Server 7.6.0+ --
more information is on the xref:sdk-release-notes.adoc[Release Notes page].

Note the https://www.couchbase.com/support-policy/EOL/[End of Life dates^] for Couchbase Server and SDK versions.
See the notes there for Support details.

=== Capella Compatibility

// The Couchbase .NET SDK is fully compatible with Couchbase Capella, our fully-hosted database-as-a-service.
// To make development easier, the SDK includes the Capella client certificate ready installed.

include::{version-common}@sdk:shared:partial$compat.adoc[tag=cloud]


=== Couchbase New Feature Availability Matrix

.Couchbase Server and SDK Supported Version Matrix
[.table-merge-cells]
[cols="7,6,6,6"]
|===
| | Server 7.2 | Server 7.6  | Server 8.0


| KV Range Scan
| N/A
2+| All supported SDK versions

| Vector Search
| N/A
2+| From SDK 3.5.1 (includes base64-encoded from SDK 3.6.1)

| Preferred Server Group Replica Reads
| N/A
2+| From SDK 3.8.0 (with Server 7.6.2 onwards)

| Vector Query using GSI
2+| N/A
| From SDK 3.9.0 ①
|===

include::{version-common}@sdk:shared:partial$compat[tag=feature-notes]


=== API Version

include::{version-common}@sdk:shared:partial$compat.adoc[tag=api-version]




== SDK API Stability


=== Interface Stability

include::{version-common}@sdk:shared:partial$compat.adoc[tag=interface-stability-section]


=== Older SDK Versions


include::{version-common}@sdk:shared:partial$compat.adoc[tag=archive-link]
