= Couchbase .NET SDK Release Notes and Archives
:description: Release notes, installation instructions, and download archive for the Couchbase .NET Client.
:navtitle: Release Notes
:page-topic-type: project-doc
:page-aliases: relnotes-dotnet-sdk
:page-partial:

// tag::all[]
[abstract]
{description}

include::hello-world:partial$supported.adoc[]

These pages cover the 3._x_ versions of the Couchbase .NET SDK.
For release notes, download links, and installation methods for 2.7 and earlier releases of the Couchbase .NET Client,  please see the xref:2.7@dotnet-sdk::sdk-release-notes.adoc[2.x .NET Release Notes & Download Archive].


== Installation

=== Quick Installation Using NuGet

For every release, we currently package the binaries and store the latest version in https://www.nuget.org/packages/CouchbaseNetClient/[NuGet].
If you are not familiar with NuGet, it's the official and most widely supported package manager for Microsoft Visual Studio and .NET in general.

==== NuGet from Visual Studio

Using Visual Studio 2013 or later, follow these steps to get started with the Couchbase .NET SDK:

. From the IDE, right-click the project you want to add the dependency to.
. In the context menu, click *Manage NuGet Packages*. The NuGet package manager modal dialog opens.
. From the Tree View menu on the left, select *Online > nuget.org*.
. In the search box at the top right-hand side of the dialog, type CouchbaseNetClient and then press enter on your keyboard.
. In the search results, select the CouchbaseNetClient package and then click *Install*.

==== NuGet from the Package Manager Console

From the Package Manager Console within your project:

. From the Visual Studio menu bar, click *Tools*.
. Select *NuGet Package Manager > Package Manager Console*.
. In the console, enter the package installation command:
 ** To install the latest version:

[source,console]
----
 Install-Package CouchbaseNetClient
----

 ** To install a specific version, include the version parameter.
For example:

[source,console]
----
 Install-Package CouchbaseNetClient -Version 3.1.3
----

=== Downloading and referencing the binaries

If you do not want to use NuGet to include the Couchbase .NET SDK in your project, you can download and reference the binaries directly. If you chose this route, you'll also be responsible for including and resolving dependencies used internally by the SDK.

To download and reference the binaries directly:

. Download the version of the SDK you want to install.
. In Visual Studio, right-click the project you want to include the SDK in and then click *Add*.
. Click *Reference* to open the Reference Manager.
. On the left side, click *Browse* and select the binaries you downloaded.
. Click *OK*.

After you have referenced the Couchbase .NET SDK binaries, you need to locate and reference the dependencies it uses in a similar fashion. At the time of this writing, the dependencies are:

* Apache Common Infrastructure Libraries for .NET
v3.3.1: https://www.nuget.org/packages/Common.Logging/3.3.1
* Json.NET
v9.0.1: https://www.nuget.org/packages/Newtonsoft.Json/8.0.3[https://www.nuget.org/packages/Newtonsoft.Json/9.0.1]

Other versions might not be compatible with the current SDK version.

=== Building from source

If none of the other installation options suffice or if you want to debug the source or perhaps contribute, building directly from the source is the best option for you. All source is located on GitHub.

NOTE: The software provided via NuGet and S3 are the official releases that have been through a rigorous testing process.
Code on GitHub that is not tagged as an official release is still in development.

To build the .NET SDK from source:

. (Optional) Fork the GitHub repository:
https://github.com/couchbase/couchbase-net-client/fork
. Using a Git console, enter the command to clone the repository:


[source,console]
----
git clone https://github.com/couchbase/couchbase-net-client.git
----

. Enter the command to retrieve the latest code from GitHub:

[source,console]
----
git pull origin master
----

. Navigate to the directory that the source was cloned to and open the solution.
. Build the solution.

After you have successfully built the source, it's then just a matter of referencing the binaries (.DLL files) from your consuming project.
_Note that you can checkout a specific tag for each release as well._


include::3.3@dotnet-sdk:project-docs:page$sdk-release-notes.adoc[tag=all]
