= Couchbase .NET SDK Release Notes and Archives
:navtitle: Release Notes
:page-topic-type: project-doc
:page-aliases: relnotes-dotnet-sdk
:page-partial:

// tag::all[]
[abstract]
Release notes, installation instructions, and download archive for the Couchbase .NET Client.

include::hello-world:partial$supported.adoc[]

These pages cover the 3._x_ versions of the Couchbase .NET SDK. 
For release notes, download links, and installation methods for 2.7 and earlier releases of the Couchbase .NET Client,  please see the xref:2.7@dotnet-sdk::sdk-release-notes.adoc[2.x .NET Release Notes & Download Archive].


== Installation

=== Quick Installation Using NuGet

For every release, we currently package the binaries and store the latest version in https://www.nuget.org/packages/CouchbaseNetClient/[NuGet].
If you are not familiar with NuGet, it's the official and most widely supported package manager for Microsoft Visual Studio and .NET in general.

==== NuGet from Visual Studio

Using Visual Studio 2013 or later, follow these steps to get started with the Couchbase .NET SDK:

. From the IDE, right-click the project you want to add the dependency to.
. In the context menu, click *Manage NuGet Packages*. The NuGet package manager modal dialog opens.
. From the Tree View menu on the left, select *Online > nuget.org*.
. In the search box at the top right-hand side of the dialog, type CouchbaseNetClient and then press enter on your keyboard.
. In the search results, select the CouchbaseNetClient package and then click *Install*.

==== NuGet from the Package Manager Console

From the Package Manager Console within your project:

. From the Visual Studio menu bar, click *Tools*.
. Select *NuGet Package Manager > Package Manager Console*.
. In the console, enter the package installation command:
 ** To install the latest version:

[source,console]
----
 Install-Package CouchbaseNetClient
----

 ** To install a specific version, include the version parameter.
For example:

[source,console]
----
 Install-Package CouchbaseNetClient -Version 2.7.0
----

=== Downloading and referencing the binaries

If you do not want to use NuGet to include the Couchbase .NET SDK in your project, you can download and reference the binaries directly. If you chose this route, you'll also be responsible for including and resolving dependencies used internally by the SDK.

To download and reference the binaries directly:

. Download the version of the SDK you want to install.
. In Visual Studio, right-click the project you want to include the SDK in and then click *Add*.
. Click *Reference* to open the Reference Manager.
. On the left side, click *Browse* and select the binaries you downloaded.
. Click *OK*.

After you have referenced the Couchbase .NET SDK binaries, you need to locate and reference the dependencies it uses in a similar fashion. At the time of this writing, the dependencies are:

* Apache Common Infrastructure Libraries for .NET
v3.3.1: https://www.nuget.org/packages/Common.Logging/3.3.1
* Json.NET
v9.0.1: https://www.nuget.org/packages/Newtonsoft.Json/8.0.3[https://www.nuget.org/packages/Newtonsoft.Json/9.0.1]

Other versions might not be compatible with the current SDK version.

=== Building from source

If none of the other installation options suffice or if you want to debug the source or perhaps contribute, building directly from the source is the best option for you. All source is located on GitHub.

NOTE: The software provided via NuGet and S3 are the official releases that have been through a rigorous testing process.
Code on GitHub that is not tagged as an official release is still in development.

To build the .NET SDK from source:

. (Optional) Fork the GitHub repository:
https://github.com/couchbase/couchbase-net-client/fork
. Using a Git console, enter the command to clone the repository:


[source,console]
----
git clone https://github.com/couchbase/couchbase-net-client.git
----

. Enter the command to retrieve the latest code from GitHub:

[source,console]
----
git pull origin master
----

. Navigate to the directory that the source was cloned to and open the solution.
. Build the solution.

After you have successfully built the source, it's then just a matter of referencing the binaries (.DLL files) from your consuming project.
_Note that you can checkout a specific tag for each release as well._

== Version 3.1.2 (4 February 2021)

Version 3.1.2 is the third release of the 3.1 series, bringing enhancements and bugfixes over the last stable release.

https://packages.couchbase.com/clients/net/3.1/Couchbase-Net-Client-3.1.2.zip[Download] |
https://docs.couchbase.com/sdk-api/couchbase-net-client-3.1.2[API Reference] |
https://www.nuget.org/packages/CouchbaseNetClient/3.1.2[Nuget]

=== Fixed Issues

* https://issues.couchbase.com/browse/NCBC-2763[NCBC-2763]: MutationToken throwing ArgumentNullException on static initialization.
* https://issues.couchbase.com/browse/NCBC-2766[NCBC-2766]: CreateScopeAsync not creating collections in ScopeSpec
* https://issues.couchbase.com/browse/NCBC-2767[NCBC-2767]: ScopeNotFoundException when trying to get Scope after creating it
* https://issues.couchbase.com/browse/NCBC-2784[NCBC-2784]: Getting a collection right after creating it throws CollectionNotFoundException
* https://issues.couchbase.com/browse/NCBC-2794[NCBC-2794]: PackageIconUrl is still being used and blocks package creation
* https://issues.couchbase.com/browse/NCBC-2797[NCBC-2797]: Hot upgrade failure from 6.6.0 to 6.6.1 using SDK v3.1.2
* https://issues.couchbase.com/browse/NCBC-2798[NCBC-2798]: ThrowIfBootstrapFailed called twice in GetAsync
* https://issues.couchbase.com/browse/NCBC-2804[NCBC-2804]: Non-JSON transcoders cannot be mixed with requests for document expiry
* https://issues.couchbase.com/browse/NCBC-2810[NCBC-2810]: On pre-7.0 clusters default scopes/collections may not load

=== New Features and Behavioral Changes.

* https://issues.couchbase.com/browse/NCBC-2791[NCBC-2791]: GetResult uses AddMilliseconds instead of AddSeconds for expiry
* https://issues.couchbase.com/browse/NCBC-2796[NCBC-2796]: SUBDOC_MULTI_PATH_FAILURE_DELETED throwing PathInvalid
* https://issues.couchbase.com/browse/NCBC-2770[NCBC-2770]: Add experimental connection pool based on System.Threading.Channels
* https://issues.couchbase.com/browse/NCBC-2772[NCBC-2772]: Cleanup key/value cancellation token and timeout handling
* https://issues.couchbase.com/browse/NCBC-2776[NCBC-2776]: Change SlicedMemoryOwner to a structure
* https://issues.couchbase.com/browse/NCBC-2789[NCBC-2789]: Unable to override the remote name mismatch error with custom validation 
* https://issues.couchbase.com/browse/NCBC-2793[NCBC-2793]: Address misc compiler warnings
* https://issues.couchbase.com/browse/NCBC-2802[NCBC-2802]: Port sub-doc lambda extensions from SDK 2.x
* https://issues.couchbase.com/browse/NCBC-2805[NCBC-2805]: Optimize in-flight operation cleanup method
* https://issues.couchbase.com/browse/NCBC-2808[NCBC-2808]: Use ValueTask and IValueTaskSource for OperationBase.Completed
* https://issues.couchbase.com/browse/NCBC-2809[NCBC-2809]: Use ValueTask for new ScopeAsync/CollectionAsync methods

== Version 3.1.1 (13 January 2021)

Version 3.1.1 is the second release of the 3.1 series, bringing enhancements and bugfixes over the last stable release.

https://packages.couchbase.com/clients/net/3.1/Couchbase-Net-Client-3.1.1.zip[Download] |
https://docs.couchbase.com/sdk-api/couchbase-net-client-3.1.1[API Reference] |
https://www.nuget.org/packages/CouchbaseNetClient/3.1.1[Nuget]

=== Fixed Issues

* https://issues.couchbase.com/browse/NCBC-2565[NCBC-2565]:
WaitUntilReady failure for 6.5.
* https://issues.couchbase.com/browse/NCBC-2660[NCBC-2660]:
Operations are not retried if they hit an open circuit breaker.
* https://issues.couchbase.com/browse/NCBC-2693[NCBC-2693]:
MutationToken.GetHashCode() implementation looks suspect.
* https://issues.couchbase.com/browse/NCBC-2694[NCBC-2694]:
Removed unnecessary linked CancellationToken.
* https://issues.couchbase.com/browse/NCBC-2726[NCBC-2726]:
Cannot read empty response bodies.
* https://issues.couchbase.com/browse/NCBC-2741[NCBC-2741]:
If the send queue is full when requeuing after connection cleanup, the operation is dropped.
* https://issues.couchbase.com/browse/NCBC-2746[NCBC-2746]:
using mutate in to update an existing value to null causes an IllegalArgumentException.
* https://issues.couchbase.com/browse/NCBC-2751[NCBC-2751]:
Use ConfigureAwait(false) on awaited task  in DnsClientDnsResolver.
* https://issues.couchbase.com/browse/NCBC-2756[NCBC-2756]:
Do not allow empty hosts in ConnectionString.
* https://issues.couchbase.com/browse/NCBC-2760[NCBC-2760]:
MultiMutation duplicates specs on Retry, causing SUBDOC_INVALID_COMBO.
* https://issues.couchbase.com/browse/NCBC-2761[NCBC-2761]:
MutateIn is not setting Cas, ignoring MutateInOptions.CasValue, resulting in a default of 0 which always overwrites.
* https://issues.couchbase.com/browse/NCBC-2762[NCBC-2762]:
Threshold trace logging leaks memory.
* https://issues.couchbase.com/browse/NCBC-2764[NCBC-2764]:
Expiration of TimeSpan.Zero is being sent to server as 1 second expiration.
* https://issues.couchbase.com/browse/NCBC-2778[NCBC-2778]:
Throw CasMismatchException when CAS mismatch occurs.
* https://issues.couchbase.com/browse/NCBC-2780[NCBC-2780]:
Fix unit tests relying on obsolete Expiry method.
* https://issues.couchbase.com/browse/NCBC-2781[NCBC-2781]:
Make replica commands use CancellationToken.
* https://issues.couchbase.com/browse/NCBC-2782[NCBC-2782]:
Replica methods randomly completed with NotMyVBucket.

=== New Features and Behavioral Changes.

* https://issues.couchbase.com/browse/NCBC-2716[NCBC-2716]:
Collections Analytics Test Changes.
* https://issues.couchbase.com/browse/NCBC-2747[NCBC-2747]:
Add KvSendQueueCapacity to ClusterOptions for tuning.
* https://issues.couchbase.com/browse/NCBC-2748[NCBC-2748]:
netcore3.0 target id deprecated and cannot be used with `dotnet pack`.
* https://issues.couchbase.com/browse/NCBC-2785[NCBC-2785]:
ArgumentOutOfRangeException if GetResult.Expiry called on GET operation.
* https://issues.couchbase.com/browse/NCBC-2788[NCBC-2788]:
`UserManagerTests.Test_UserInheritsCollectionAwareRoles` fails in combi tests.
* https://issues.couchbase.com/browse/NCBC-2653[NCBC-2653]:
Unnecessary allocation in classes implementing IOperation.
* https://issues.couchbase.com/browse/NCBC-2661[NCBC-2661]:
CouchbaseBucket is doing ad hoc retrying if CollectionOutdatedException.
* https://issues.couchbase.com/browse/NCBC-2677[NCBC-2677]:
Docs: Threshold Logging and Orphan Response Logging.
* https://issues.couchbase.com/browse/NCBC-2722[NCBC-2722]:
Improve performance of `WriteKey` using `stackalloc`.
* https://issues.couchbase.com/browse/NCBC-2723[NCBC-2723]:
Reduce async/await around circuit breakers on K/V ops.
* https://issues.couchbase.com/browse/NCBC-2724[NCBC-2724]:
Reduce task continuations related to K/V timeouts.
* https://issues.couchbase.com/browse/NCBC-2725[NCBC-2725]:
Improve logic around ITypeTranscoder instantiations.
* https://issues.couchbase.com/browse/NCBC-2727[NCBC-2727]:
Improve log redaction performance.
* https://issues.couchbase.com/browse/NCBC-2728[NCBC-2728]:
Improve LEB128 encoding performance.
* https://issues.couchbase.com/browse/NCBC-2729[NCBC-2729]:
Reduce task continuations on k/v GET operations.
* https://issues.couchbase.com/browse/NCBC-2731[NCBC-2731]:
Reduce JSON serialization heap allocations.
* https://issues.couchbase.com/browse/NCBC-2732[NCBC-2732]:
ConfigHandler processing is blocking a thread from the thread pool.
* https://issues.couchbase.com/browse/NCBC-2733[NCBC-2733]:
Improve efficiency of ErrorCode lookup in ErrorMap.
* https://issues.couchbase.com/browse/NCBC-2734[NCBC-2734]:
Improve CancellationTokenSource handling in RetryOrchestrator.
* https://issues.couchbase.com/browse/NCBC-2735[NCBC-2735]:
Optimize OperationBuilder performance.
* https://issues.couchbase.com/browse/NCBC-2736[NCBC-2736]:
Optimize key/value operation flag handling.
* https://issues.couchbase.com/browse/NCBC-2737[NCBC-2737]:
Use a static client description for spans.
* https://issues.couchbase.com/browse/NCBC-2738[NCBC-2738]:
Improve performance building connection tags for K/V operation spans.
* https://issues.couchbase.com/browse/NCBC-2740[NCBC-2740]:
Optimize performance when request tracing is disabled.
* https://issues.couchbase.com/browse/NCBC-2742[NCBC-2742]:
Reduce debug logging heap allocations on critical K/V path.
* https://issues.couchbase.com/browse/NCBC-2743[NCBC-2743]:
Reduce Task ContingentProperties heap allocations.
* https://issues.couchbase.com/browse/NCBC-2744[NCBC-2744]:
Enable reporting of test results in Jenkins.
* https://issues.couchbase.com/browse/NCBC-2745[NCBC-2745]:
Reduce lambda-related heap allocations for K/V operation completions.
* https://issues.couchbase.com/browse/NCBC-2749[NCBC-2749]:
Use Stopwatch to track connection idle time.
* https://issues.couchbase.com/browse/NCBC-2750[NCBC-2750]:
Use spans in MultiplexingConnection.ParseReceivedData.
* https://issues.couchbase.com/browse/NCBC-2752[NCBC-2752]:
Improve ToTtl performance.
* https://issues.couchbase.com/browse/NCBC-2753[NCBC-2753]:
Allow BucketBase.RetryAsync to be inlined.
* https://issues.couchbase.com/browse/NCBC-2754[NCBC-2754]:
Use Span&lt;byte&gt; for VBucketKeyMapper.GetIndex
* https://issues.couchbase.com/browse/NCBC-2755[NCBC-2755]:
Use ThrowHelper to improve inlining.
* https://issues.couchbase.com/browse/NCBC-2757[NCBC-2757]:
SkipLocalsInit when writing document keys to operations.
* https://issues.couchbase.com/browse/NCBC-2758[NCBC-2758]:
Use .NET provided encoding of strings to spans when available.
* https://issues.couchbase.com/browse/NCBC-2765[NCBC-2765]:
Improve buffer handling in MultiplexingConnection receive.
* https://issues.couchbase.com/browse/NCBC-2768[NCBC-2768]:
Improve precision of UnixMillisecondsConverter.
* https://issues.couchbase.com/browse/NCBC-2769[NCBC-2769]:
Avoid heap allocations for default K/V operations.
* https://issues.couchbase.com/browse/NCBC-2773[NCBC-2773]:
Simplify AsyncState handling of Opaque.
* https://issues.couchbase.com/browse/NCBC-2774[NCBC-2774]:
Make OperationBuilderPool tunable.
* https://issues.couchbase.com/browse/NCBC-2775[NCBC-2775]:
Improve array handling performance throughout the SDK.


== Version 3.1.0 (2 December 2020)

This is the first GA release of the 3.1 series, bringing enhancements and bugfixes over the 3.0 releases, 
and adding features to support Couchbase Server 6.6.

https://packages.couchbase.com/clients/net/3.0/Couchbase-Net-Client-3.1.0.zip[Download] |
https://docs.couchbase.com/sdk-api/couchbase-net-client-3.1.0[API Reference] |
https://www.nuget.org/packages/CouchbaseNetClient/3.1.0[Nuget]

=== Fixed Issues

* https://issues.couchbase.com/browse/NCBC-2643[NCBC-2643]: 
`DataFlowConnectionPool` was creating unbounded connections in certain situations, such as pinging for a buckets which had not yet been created.
This fix resolves the issue, although the number of connections will go up still but then trend back down, as they are in a `TIME_WAIT` state and it takes a little time for them to be reclaimed.
* https://issues.couchbase.com/browse/NCBC-2660[NCBC-2660]: 
Operations were not retried if they hit an open circuit breaker (`CircuitBreakerException`); 
the retry orchestrator will now retry these failures.
* https://issues.couchbase.com/browse/NCBC-2686[NCBC-2686]: 
Facet result missing fields added to Search.
* https://issues.couchbase.com/browse/NCBC-2705[NCBC-2705]: 
`RawBinaryTranscoder` was using invalid DataFormat.
It will now simply pass the body of the packet back to the consumer as it should.
* https://issues.couchbase.com/browse/NCBC-2706[NCBC-2706]: 
A JSON string stored in Couchbase was generating an error when read as a string via `result.ContentAs<string>()`.
The packet is now converted into a UTF8 string if the type of T is a string in `JsonTranscoder`,
so if you write a POCO to Couchbase reading it as a string now works as expected.
* https://issues.couchbase.com/browse/NCBC-2708[NCBC-2708]: 
Sub-Document API Transcoder `InvalidOperationExceptions` are no longer thrown when a DataFormat mismatch occurs.


=== New Features and Behavioral Changes.

* https://issues.couchbase.com/browse/NCBC-2386[NCBC-2386]: 
Non-JSON & transcoders code samples added to developer documentation.
* https://issues.couchbase.com/browse/NCBC-2418[NCBC-2418]: 
`maxTTL` can now be set via the `CollectionSpec.MaxExpiry` property.
* https://issues.couchbase.com/browse/NCBC-2572[NCBC-2572]: 
Durability can now be set on the bucket, for Couchbase Server 6.6 and up.
* https://issues.couchbase.com/browse/NCBC-2589[NCBC-2589]: 
Document Expiry Duration works as expected with offsets and with absolute time stamps.
* https://issues.couchbase.com/browse/NCBC-2622[NCBC-2622]: 
GetResult.expiry() is deprecated.
Please use `GetResult.ExpiryTime` over `Expiry` as it accurately depicts the `TTL` of the document.
* https://issues.couchbase.com/browse/NCBC-2627[NCBC-2627], https://issues.couchbase.com/browse/NCBC-2631[NCBC-2631]: 
FTS _Score_ parameter added to allow avoidance of scoring from Server 6.6.
* https://issues.couchbase.com/browse/NCBC-2679[NCBC-2679]: 
A better opcode is used for basic Get scenarios, which will allow the server to return compressed documents once compression support is added to the .NET SDK.
* https://issues.couchbase.com/browse/NCBC-2709[NCBC-2709]: 
A minor optimization in all key-value operations following improved performance of bootstrap test.
* https://issues.couchbase.com/browse/NCBC-2715[NCBC-2715]: 
Added `InterfaceStabilityAttribute` for API interface stability.


== Version 3.0.7 (3 November 2020)

Version 3.0.7 is the eighth release of the 3.0 series, bringing enhancements and bugfixes over the last stable release.

https://packages.couchbase.com/clients/net/3.0/Couchbase-Net-Client-3.0.7.zip[Download] |
https://docs.couchbase.com/sdk-api/couchbase-net-client-3.0.7[API Reference] |
https://www.nuget.org/packages/CouchbaseNetClient/3.0.7[Nuget]

=== Fixed Issues

* https://issues.couchbase.com/browse/NCBC-2641[NCBC-2641]:
ConfigHandler has already been started.
* https://issues.couchbase.com/browse/NCBC-2651[NCBC-2651]:
IncrementOptions and DecrementOptions are missing Expiry.
* https://issues.couchbase.com/browse/NCBC-2655[NCBC-2655]:
Bucket WaitUntilReadyAsync running into NullReferenceException.
* https://issues.couchbase.com/browse/NCBC-2656[NCBC-2656]:
Serialization/Transcoding Errors Are Unhandled.
* https://issues.couchbase.com/browse/NCBC-2660[NCBC-2660]:
Operations are not retried if they hit an open circuit breaker.
* https://issues.couchbase.com/browse/NCBC-2669[NCBC-2669]:
Upsert/Insert null with MutateIn fails with Invalid arguments (0x0004).
* https://issues.couchbase.com/browse/NCBC-2685[NCBC-2685]:
AccessDeleted not supported properly on MutateIn.

=== New Features and Behavioral Changes.

* https://issues.couchbase.com/browse/NCBC-2670[NCBC-2670]:
Collections - RBAC Collections - .net tests
* https://issues.couchbase.com/browse/NCBC-2569[NCBC-2569]:
.NET Logging page
* https://issues.couchbase.com/browse/NCBC-2580[NCBC-2580]:
Add Ephemeral Bucket Management Support
* https://issues.couchbase.com/browse/NCBC-2664[NCBC-2664]:
Operations are silently ignored if the send queue is full
* https://issues.couchbase.com/browse/NCBC-2668[NCBC-2668]:
Add RawBinaryTranscoder
* https://issues.couchbase.com/browse/NCBC-2675[NCBC-2675]:
Optimize VBucketKeyMapper.GetIndex
* https://issues.couchbase.com/browse/NCBC-2680[NCBC-2680]:
Share ServerFeatures on IConnection
* https://issues.couchbase.com/browse/NCBC-2688[NCBC-2688]:
Make synchronous Analytics query methods obsolete


= Version 3.0.6 (13 October 2020)
Version 3.0.6 is the seventh release of the 3.0 series, bringing enhancements and bugfixes over the last stable release.


https://packages.couchbase.com/clients/net/3.0/Couchbase-Net-Client-3.0.6.zip[Download] |
https://docs.couchbase.com/sdk-api/couchbase-net-client-3.0.6[API Reference] |
https://www.nuget.org/packages/CouchbaseNetClient/3.0.6[Nuget]

=== Fixed Issues

* https://issues.couchbase.com/browse/NCBC-2187[NCBC-2187]: 
CollectionManager  - 400: Not allowed on this version of cluster (verify).
* https://issues.couchbase.com/browse/NCBC-2604[NCBC-2604]: 
exception.IsRetryable() in docs.
* https://issues.couchbase.com/browse/NCBC-2619[NCBC-2619]: 
Update KV samples.
* https://issues.couchbase.com/browse/NCBC-2638[NCBC-2638]: 
Intermittent InvalidOperationException in Dependency Injection.
* https://issues.couchbase.com/browse/NCBC-2639[NCBC-2639]: 
Upsert-and-remove doesn't work.
* https://issues.couchbase.com/browse/NCBC-2652[NCBC-2652]: 
Operations gets stuck in retry loop until timeout.
* https://issues.couchbase.com/browse/NCBC-2657[NCBC-2657]: 
Exceptions Aren't Thrown For N1QL Errors After Results.
* https://issues.couchbase.com/browse/NCBC-2659[NCBC-2659]: 
Fix strong naming for Couchbase.Extensions.DependencyInjection.
* https://issues.couchbase.com/browse/NCBC-2662[NCBC-2662]: 
Correct DI security for named buckets on .NET Core.
* https://issues.couchbase.com/browse/NCBC-2671[NCBC-2671]: 
KV Throughput drop after failover-rebalance

=== New Features and Behavioral Changes.

* https://issues.couchbase.com/browse/NCBC-2033[NCBC-2033]: 
3.0 API Query snippets in concept doc.
* https://issues.couchbase.com/browse/NCBC-2321[NCBC-2321]: 
Update documents to SDK 3.0 Beta interface.
* https://issues.couchbase.com/browse/NCBC-2472[NCBC-2472]: 
Ensure connection string supports options table defined in RFC.
* https://issues.couchbase.com/browse/NCBC-2298[NCBC-2298]: 
CancellationToken and CancellationTokenSource management needed.
* https://issues.couchbase.com/browse/NCBC-2557[NCBC-2557]: 
Improve cancellation and timeouts.
* https://issues.couchbase.com/browse/NCBC-2573[NCBC-2573]: 
Add support for CreateAsDeleted.
* https://issues.couchbase.com/browse/NCBC-2576[NCBC-2576]: 
Geopolygon search support.
* https://issues.couchbase.com/browse/NCBC-2577[NCBC-2577]: 
Add Options To Use FTS Hints (Flex Index).


= Version 3.0.5 (1 September 2020)

Version 3.0.5 is the sixth release of the 3.0 series, bringing enhancements and bugfixes over the last stable release.

https://packages.couchbase.com/clients/net/3.0/Couchbase-Net-Client-3.0.5.zip[Download] |
https://docs.couchbase.com/sdk-api/couchbase-net-client-3.0.5[API Reference] |
https://www.nuget.org/packages/CouchbaseNetClient/3.0.5[Nuget]

=== Fixed Issues

* https://issues.couchbase.com/browse/NCBC-2504[NCBC-2504]: 
Intermittent ViewQuery failures after rebound Rb2OutEpt-HYBRID
* https://issues.couchbase.com/browse/NCBC-2559[NCBC-2559]: 
Test_BootStrap_Error_Propagates_To_View_Operations fails w/BucketNotFoundException
* https://issues.couchbase.com/browse/NCBC-2561[NCBC-2561]: 
CreateAndDropIndex and Test_QueryManager conflict
* https://issues.couchbase.com/browse/NCBC-2625[NCBC-2625]: 
Ensure new NodeAdapter is assigned to ClusterNode on change
* https://issues.couchbase.com/browse/NCBC-2634[NCBC-2634]: 
Expiry returned with entire document when ContentAs invoked
* https://issues.couchbase.com/browse/NCBC-2405[NCBC-2405]: 
SDK3 DOC on User Auth options
* https://issues.couchbase.com/browse/NCBC-2541[NCBC-2541]: 
WaitUntilReady() doc code sample
* https://issues.couchbase.com/browse/NCBC-2603[NCBC-2603]: 
Missing snippets & sections in Managing Connections doc
* https://issues.couchbase.com/browse/NCBC-2623[NCBC-2623]: 
Implement Threshold Logging features of RTO
* https://issues.couchbase.com/browse/NCBC-2636[NCBC-2636]: 
Test max limitations of collections and scopes
* https://issues.couchbase.com/browse/NCBC-2637[NCBC-2637]: 
Split Couchbase.IntegrationTests into seperate projects for Management and main API
* https://issues.couchbase.com/browse/NCBC-2427[NCBC-2427]: 
Verify that out-of-order K/V request/responses are supported
* https://issues.couchbase.com/browse/NCBC-2584[NCBC-2584]: 
Add N1QL Support for Collections
* https://issues.couchbase.com/browse/NCBC-2630[NCBC-2630]: 
Enhance User Management for Collections/RBAC


= Version 3.0.4 (5 August 2020)

Version 3.0.4 is the fifth release of the 3.0 series, bringing enhancements and bugfixes over the last stable release.

https://packages.couchbase.com/clients/net/3.0/Couchbase-Net-Client-3.0.4.zip[Download] |
https://docs.couchbase.com/sdk-api/couchbase-net-client-3.0.4[API Reference] |
https://www.nuget.org/packages/CouchbaseNetClient/3.0.4[Nuget]

=== Known Issues
* https://issues.couchbase.com/browse/NCBC-2187[NCBC-2187]: 
CollectionManager -- 400: Not allowed on this version of cluster.

=== Fixed Issues

* https://issues.couchbase.com/browse/NCBC-2605[NCBC-2605]: 
Expiration less than 1000ms creates a doc with an infinite lifespan
* https://issues.couchbase.com/browse/NCBC-2608[NCBC-2608]: 
Connection fails if first node in connection string array is unavailable.
* https://issues.couchbase.com/browse/NCBC-2620[NCBC-2620]: 
Expiry not being set by MutateIn
* https://issues.couchbase.com/browse/NCBC-2621[NCBC-2621]: 
Ensure the CName field is set per operation
* https://issues.couchbase.com/browse/NCBC-2601[NCBC-2601]: 
SUBDOC_XATTR_INVALID_FLAG_COMBO when mixing MutationMacro and XAttr

=== New Features and Behavioral Changes.

* https://issues.couchbase.com/browse/NCBC-2441[NCBC-2441]: 
Implement tracing using OpenTelemetry for FTS
* https://issues.couchbase.com/browse/NCBC-2442[NCBC-2442]: 
Implement tracing using OpenTelemetry for KV
* https://issues.couchbase.com/browse/NCBC-2443[NCBC-2443]: 
Implement tracing using OpenTelemetry for Analytics
* https://issues.couchbase.com/browse/NCBC-2444[NCBC-2444]: 
Implement tracing using OpenTelemetry for Views
* https://issues.couchbase.com/browse/NCBC-2579[NCBC-2579]: 
Implement tracing of spans for all services towards Response Time Observability for SDK 3.0
* https://issues.couchbase.com/browse/NCBC-2583[NCBC-2583]: 
Add support for looking up certificates via Cert Store
* https://issues.couchbase.com/browse/NCBC-2602[NCBC-2602]: 
Add Support for MutateIn.SetDocument
* https://issues.couchbase.com/browse/NCBC-2609[NCBC-2609]: 
Add PublicKey to AssemblyInfo for DI when building release packages
* https://issues.couchbase.com/browse/NCBC-2617[NCBC-2617]: 
When signing make friend assemblies use public key


= Version 3.0.3 (14 July 2020)

Version 3.0.3 is the fourth release of the 3.0 series, bringing enhancements and bugfixes over the last stable release.

https://packages.couchbase.com/clients/net/3.0/Couchbase-Net-Client-3.0.3.zip[Download] |  
https://docs.couchbase.com/sdk-api/couchbase-net-client-3.0.3[API Reference] | 
https://www.nuget.org/packages/CouchbaseNetClient/3.0.3[Nuget]

=== Known Issues
* https://issues.couchbase.com/browse/NCBC-2187[NCBC-2187]: 
CollectionManager -- 400: Not allowed on this version of cluster.

=== Fixed Issues

* https://issues.couchbase.com/browse/NCBC-2588[NCBC-2588]: 
LookupIn should re-order subdoc requests so that XATTRs come first.
* https://issues.couchbase.com/browse/NCBC-2450[NCBC-2450]: 
KV failure after removing entry point node for pre-MH server
* https://issues.couchbase.com/browse/NCBC-2501[NCBC-2501]: 
latency detected in FoEptRb-SubDoc after rebound never recovers
* https://issues.couchbase.com/browse/NCBC-2502[NCBC-2502]: 
latency detected in FoEptEject-SUBDOC after rebound never recovers
* https://issues.couchbase.com/browse/NCBC-2503[NCBC-2503]: 
Latency detected for FoRbAnalytics-CBAS after rebound never recovers
* https://issues.couchbase.com/browse/NCBC-2545[NCBC-2545]: 
Hello World example in the docs repo doesn&#39;t build.
* https://issues.couchbase.com/browse/NCBC-2553[NCBC-2553]: 
Remove authzid from Sasl Negotiation
* https://issues.couchbase.com/browse/NCBC-2563[NCBC-2563]: 
StreamingQueryResult fails to populate errors on InternalServerError
* https://issues.couchbase.com/browse/NCBC-2587[NCBC-2587]: 
LookupInSpecBuilder allows only a single XATTR per request.
* https://issues.couchbase.com/browse/NCBC-2592[NCBC-2592]: 
Fix custom circuit breaker not being injected
* https://issues.couchbase.com/browse/NCBC-1836[NCBC-1836]: 
CAS samples

=== New Features and Behavioral Changes.

* https://issues.couchbase.com/browse/NCBC-2542[NCBC-2542]: 
OpenTelemetry tracing extension
* https://issues.couchbase.com/browse/NCBC-2593[NCBC-2593]: 
Update install and start docs to reflect .NET Standard/Core support
* https://issues.couchbase.com/browse/NCBC-2594[NCBC-2594]: 
Update version number on release notes
* https://issues.couchbase.com/browse/NCBC-2595[NCBC-2595]: 
Indent code on error handling page so that it is readable.
* https://issues.couchbase.com/browse/NCBC-2227[NCBC-2227]: 
Author Managing Connections documentation
* https://issues.couchbase.com/browse/NCBC-2170[NCBC-2170]: 
Implement tracing using OpenTelemetry for Query
* https://issues.couchbase.com/browse/NCBC-2519[NCBC-2519]: 
Review docs for update items, identify/file issues
* https://issues.couchbase.com/browse/NCBC-2598[NCBC-2598]: 
Misc SDK improvements for Transactions
* https://issues.couchbase.com/browse/NCBC-2591[NCBC-2591]: 
Allow registration of custom services


= Version 3.0.2 (20 June 2020)

Version 3.0.2 is the third release of the 3.0 series, bringing enhancements and bugfixes over the last stable release.

https://packages.couchbase.com/clients/net/3.0/Couchbase-Net-Client-3.0.2.zip[Download] |  
https://docs.couchbase.com/sdk-api/couchbase-net-client-3.0.2[API Reference] | 
https://www.nuget.org/packages/CouchbaseNetClient/3.0.2[Nuget]

=== Known Issues
* https://issues.couchbase.com/browse/NCBC-2187[NCBC-2187]: 
CollectionManager -- 400: Not allowed on this version of cluster.

=== Fixed Issues
* https://issues.couchbase.com/browse/NCBC-2436[NCBC-2436]: 
User connstr example in migration guide
* https://issues.couchbase.com/browse/NCBC-2459[NCBC-2459]: 
Remove QueryOptions from StartUsing.cs in docs
* https://issues.couchbase.com/browse/NCBC-2487[NCBC-2487]: 
NRE when bootstrapping - BucketConfigExtensions.ReplacePlaceholderWithBootstrapHost
* https://issues.couchbase.com/browse/NCBC-2506[NCBC-2506]: 
Connection attempt failed / timeout exception with Cloud and .NET SDK 3.0.1
* https://issues.couchbase.com/browse/NCBC-2508[NCBC-2508]: 
Alternate Addresses are not handled correctly in sdk3
* https://issues.couchbase.com/browse/NCBC-2512[NCBC-2512]: 
Additional debug logging and improvements
* https://issues.couchbase.com/browse/NCBC-2525[NCBC-2525]: 
Connection pool does not scale up to minimum connections after a temporary network failure.
* https://issues.couchbase.com/browse/NCBC-2526[NCBC-2526]: 
requests wait forever while cluster is unreachable
* https://issues.couchbase.com/browse/NCBC-2537[NCBC-2537]: 
Orphaned nodes when bootstrapping with a Memcached and a Couchbase bucket
* https://issues.couchbase.com/browse/NCBC-2538[NCBC-2538]: 
Analytics failures after failover/rebalance of the ept node
* https://issues.couchbase.com/browse/NCBC-2540[NCBC-2540]: 
Enumerating query results from SELECT RAW queries throws an exception
* https://issues.couchbase.com/browse/NCBC-2546[NCBC-2546]: 
Retry all exceptions with the IRetriable marker interface
* https://issues.couchbase.com/browse/NCBC-2548[NCBC-2548]: 
Ensure all operations attempt retrys when NMVB status is returned by server
* https://issues.couchbase.com/browse/NCBC-2549[NCBC-2549]: 
Subdoc failures after restarting CB server
* https://issues.couchbase.com/browse/NCBC-2552[NCBC-2552]: 
Intermittent cluster connection failures with CB Server &lt;6.5
* https://issues.couchbase.com/browse/NCBC-2555[NCBC-2555]: 
Memcached and SSL results in &quot;The handshake failed due to an unexpected packet format.&quot;
* https://issues.couchbase.com/browse/NCBC-2556[NCBC-2556]: 
Capture thrown exception and log the error when bootstrapping
* https://issues.couchbase.com/browse/NCBC-2558[NCBC-2558]: 
Couchbase.Extensions.DependencyInjection Failing On .NET Core 3.1

=== New Features and Behavioral Changes.
* https://issues.couchbase.com/browse/NCBC-2202[NCBC-2202]: 
Integration tests need to configure tests to run based on server version
* https://issues.couchbase.com/browse/NCBC-2237[NCBC-2237]: 
PLAIN must not be enabled by default on non-tls connections
* https://issues.couchbase.com/browse/NCBC-2404[NCBC-2404]: 
ConnectAsync throws ArgumentNullException when cluster cannot be reached
* https://issues.couchbase.com/browse/NCBC-2530[NCBC-2530]: 
Provide navigation properties to get from ICouchbaseCollection back to ICluster
* https://issues.couchbase.com/browse/NCBC-2533[NCBC-2533]: 
Provide access to ITypeSerializer on ICluster for Linq2Couchbase
* https://issues.couchbase.com/browse/NCBC-2544[NCBC-2544]: 
Add additional DEBUG logging info and ContextIds
* https://issues.couchbase.com/browse/NCBC-2463[NCBC-2463]: 
Document documentation .NET
* https://issues.couchbase.com/browse/NCBC-2469[NCBC-2469]: 
Make nightly Jenkins builds work
* https://issues.couchbase.com/browse/NCBC-2495[NCBC-2495]: 
Update NuGet API Key in deployment pipeline on Jenkins
* https://issues.couchbase.com/browse/NCBC-2509[NCBC-2509]: 
CreateAndConnectAsync ONLY creates CouchbaseBuckets (not MemCache or Ephemeral)
* https://issues.couchbase.com/browse/NCBC-2517[NCBC-2517]: 
DependencyInjection project refactoring
* https://issues.couchbase.com/browse/NCBC-2523[NCBC-2523]: 
Port ClusterVersion from sdk2 to sdk3
* https://issues.couchbase.com/browse/NCBC-2527[NCBC-2527]: 
Update DnsClient to 1.3.2
* https://issues.couchbase.com/browse/NCBC-2529[NCBC-2529]: 
CB Cloud:  non-KV nodes fail when used for bootstraping
* https://issues.couchbase.com/browse/NCBC-2534[NCBC-2534]: 
.NET Collections Functional Testing
* https://issues.couchbase.com/browse/NCBC-2539[NCBC-2539]: 
Port UnixMillisecondsConverter from sdk2 to sdk3
* https://issues.couchbase.com/browse/NCBC-2482[NCBC-2482]: 
Couchbase.IntegrationTests.Services.Search.SearchIndexManagerTests.TestSearchManager 
* https://issues.couchbase.com/browse/NCBC-2483[NCBC-2483]: 
Couchbase.IntegrationTests.UserManagerTests.Test_UserManager 
* https://issues.couchbase.com/browse/NCBC-2484[NCBC-2484]: 
Couchbase.IntegrationTests.BucketManagerTests.Test_BucketManager 
* https://issues.couchbase.com/browse/NCBC-2485[NCBC-2485]: 
Couchbase.IntegrationTests.Diagnostics.PingReportTests.Can_Get_PingReport_With_ReportId 
* https://issues.couchbase.com/browse/NCBC-2486[NCBC-2486]: 
Couchbase.IntegrationTests.CollectionManagerTests.Test_CollectionManager 
* https://issues.couchbase.com/browse/NCBC-2489[NCBC-2489]: 
Couchbase.IntegrationTests.ClusterTests.Test_Open_More_Than_One_Bucket 
* https://issues.couchbase.com/browse/NCBC-2490[NCBC-2490]: 
Couchbase.ServiceNotAvailableException :  Service views not available.
* https://issues.couchbase.com/browse/NCBC-2518[NCBC-2518]: 
HttpStreamingConfigListener should continue running after all streams break.
* https://issues.couchbase.com/browse/NCBC-2524[NCBC-2524]: 
Couchbase.IntegrationTests.ClusterTests.Test_WaitUntilReadyAsync 
* https://issues.couchbase.com/browse/NCBC-2531[NCBC-2531]: 
Implement OpenTelemetry Stub in CouchbaseNetClient
* https://issues.couchbase.com/browse/NCBC-2532[NCBC-2532]: 
Remove existing OpenTracing dependency


= Version 3.0.1 (13 May 2020)

Version 3.0.1 is the second release of the 3.0 series, bringing enhancements and bugfixes over the last stable release.

https://packages.couchbase.com/clients/net/3.0/Couchbase-Net-Client-3.0.1.zip[Download] |  
https://docs.couchbase.com/sdk-api/couchbase-net-client-3.0.1[API Reference] | 
https://www.nuget.org/packages/CouchbaseNetClient/3.0.1[Nuget]

=== Known Issues
* https://issues.couchbase.com/browse/NCBC-2187[NCBC-2187]: 
CollectionManager -- 400: Not allowed on this version of cluster.

=== Fixed Issues
* https://issues.couchbase.com/browse/NCBC-2033[NCBC-2033]: 
3.0 API Query snippets in concept doc
* https://issues.couchbase.com/browse/NCBC-2204[NCBC-2204]: 
Improve exception when bootstrapping fails
* https://issues.couchbase.com/browse/NCBC-2301[NCBC-2301]: 
3.0 Logging / Collecting Info page
* https://issues.couchbase.com/browse/NCBC-2303[NCBC-2303]: 
Client Settings page for SDK 3.0
* https://issues.couchbase.com/browse/NCBC-2388[NCBC-2388]: 
Ensure that prepared statements that are previously created are not retried
* https://issues.couchbase.com/browse/NCBC-2435[NCBC-2435]: 
Connstr not taking username properly
* https://issues.couchbase.com/browse/NCBC-2439[NCBC-2439]: 
improve formatting on exception context
* https://issues.couchbase.com/browse/NCBC-2451[NCBC-2451]: 
QueryPreparedStatementFailure in situational tests with MH
* https://issues.couchbase.com/browse/NCBC-2454[NCBC-2454]: 
EndPoint may be null during SendAsync
* https://issues.couchbase.com/browse/NCBC-2456[NCBC-2456]: 
Transient NodeNotAvailableException rebalance under kv load
* https://issues.couchbase.com/browse/NCBC-2458[NCBC-2458]: 
QueryAsync(String statement) does not exist
* https://issues.couchbase.com/browse/NCBC-2460[NCBC-2460]: 
.NET Core App 3.x targets require consumers add reference to Microsoft.Bcl.AsyncInterfaces
* https://issues.couchbase.com/browse/NCBC-2462[NCBC-2462]: 
ConnectAsync is failing "Cannot resolve DNS for localhost"
* https://issues.couchbase.com/browse/NCBC-2466[NCBC-2466]: 
Ensure TaskCancelationExceptions are rethrown
* https://issues.couchbase.com/browse/NCBC-2467[NCBC-2467]: 
CLONE - Ensure TaskCancelationExceptions are rethrown
* https://issues.couchbase.com/browse/NCBC-2468[NCBC-2468]: 
System.ArgumentException: ReadResult does not contain valid MutationToken
* https://issues.couchbase.com/browse/NCBC-2473[NCBC-2473]: 
Incorrect Verbiage for NuGet Package
* https://issues.couchbase.com/browse/NCBC-2475[NCBC-2475]: 
GetNodes() sometimes returns no results, incorrectly.
* https://issues.couchbase.com/browse/NCBC-2479[NCBC-2479]: 
Point config.json for combination tests back at localhost
* https://issues.couchbase.com/browse/NCBC-2480[NCBC-2480]: 
SocketException:  Cannot bind to address in SslConnectionTests
* https://issues.couchbase.com/browse/NCBC-2481[NCBC-2481]: 
KV operations don't respect IgnoreCertificateNameMismatch
* https://issues.couchbase.com/browse/NCBC-2488[NCBC-2488]: 
Couchbase.IntegrationTests.BootstrapFailedTests.Test_BootStrap_Error_Propagates_To_View_Operations [FAIL]
* https://issues.couchbase.com/browse/NCBC-2493[NCBC-2493]: 
Improve error logging and handling for Query
* https://issues.couchbase.com/browse/NCBC-2497[NCBC-2497]: 
SetKeepAlive fails on Windows

=== New Features and Behavioral Changes.

* https://issues.couchbase.com/browse/NCBC-2304[NCBC-2304]: 
Managing Connections - SDK3
* https://issues.couchbase.com/browse/NCBC-2464[NCBC-2464]: 
Build/deploy the .NET Dependency Injection extension for SDK 3.0
* https://issues.couchbase.com/browse/NCBC-2478[NCBC-2478]: 
Cluster.ConnectAsync throws PlatformNotSupportedException
* https://issues.couchbase.com/browse/NCBC-2492[NCBC-2492]: 
Log warning when TCPKeepAlive cannot be enabled
* https://issues.couchbase.com/browse/NCBC-2494[NCBC-2494]: 
Fix TCPKeepAlive to work on non Windows Platform


= Version 3.0.0 (31 March 2020)

This is the first GA release of the third generation .NET SDK.

https://packages.couchbase.com/clients/net/3.0/Couchbase-Net-Client-3.0.0.zip[Download] |  
https://docs.couchbase.com/sdk-api/couchbase-net-client-3.0.0[API Reference] | 
https://www.nuget.org/packages/CouchbaseNetClient/3.0.0[Nuget]

This is the first GA release of the third generation .NET SDK.

This release features significant changes to the API, simplifies the programming model, adds support for newer Durability Requirements and enables simple extension for features coming in future Couchbase Server releases.
See the xref:project-docs:migrating-sdk-code-to-3.n.adoc[Migration Guide] for help with migrating from .NET SDK 2.x.


=== Known Issues
* https://issues.couchbase.com/browse/NCBC-2187[NCBC-2187]: 
CollectionManager -- 400: Not allowed on this version of cluster.

=== Fixed Issues
* https://issues.couchbase.com/browse/NCBC-2149[NCBC-2149]: 
ConfigConext throws NullReferenceException when processing new cluster maps
* https://issues.couchbase.com/browse/NCBC-2153[NCBC-2153]: 
Fix failing integration tests for SDK3
* https://issues.couchbase.com/browse/NCBC-2166[NCBC-2166]: 
Authentication Errors after adding nodes to cluster
* https://issues.couchbase.com/browse/NCBC-2168[NCBC-2168]: 
QueryException does not provide textual details coming from the server 
* https://issues.couchbase.com/browse/NCBC-2199[NCBC-2199]: 
Missing string interpolation sign in CouchbaseBucket
* https://issues.couchbase.com/browse/NCBC-2213[NCBC-2213]: 
N1QL situational test failure - Rb1SwapQuery
* https://issues.couchbase.com/browse/NCBC-2214[NCBC-2214]: 
N1QL situational test failure - SvcRestartQuery
* https://issues.couchbase.com/browse/NCBC-2217[NCBC-2217]: 
Deserialization issues with GetAsync<T>
* https://issues.couchbase.com/browse/NCBC-2219[NCBC-2219]: 
Cluster instantiation using ClusterOptions ignores WithServers servers
* https://issues.couchbase.com/browse/NCBC-2222[NCBC-2222]: 
AuthenticationFailure thrown when accessing bucket while combination testing
* https://issues.couchbase.com/browse/NCBC-2230[NCBC-2230]: 
QueryException missing XxxxContext
* https://issues.couchbase.com/browse/NCBC-2241[NCBC-2241]: 
Defer bootstrapping errors on buckets to first operation
* https://issues.couchbase.com/browse/NCBC-2266[NCBC-2266]: 
UserManager#AvailableRolesAsync must be called getRoles
* https://issues.couchbase.com/browse/NCBC-2268[NCBC-2268]: 
CollectionManager does not align with RFC
* https://issues.couchbase.com/browse/NCBC-2273[NCBC-2273]: 
Incorrect ScopeMissingException
* https://issues.couchbase.com/browse/NCBC-2274[NCBC-2274]: 
Can't connect to two buckets from one cluster object
* https://issues.couchbase.com/browse/NCBC-2277[NCBC-2277]: 
SearchOptions does not map query parameters
* https://issues.couchbase.com/browse/NCBC-2282[NCBC-2282]: 
fix test and implementation of positional params
* https://issues.couchbase.com/browse/NCBC-2286[NCBC-2286]: 
Make all options have no "With" prefix
* https://issues.couchbase.com/browse/NCBC-2288[NCBC-2288]: 
MutateIn ContentAs() functionality missing
* https://issues.couchbase.com/browse/NCBC-2290[NCBC-2290]: 
 Add Timeout to all options classes in BucketManager
* https://issues.couchbase.com/browse/NCBC-2306[NCBC-2306]: 
Match RFC requirement for Rows property for query services
* https://issues.couchbase.com/browse/NCBC-2307[NCBC-2307]: 
Cannot query using any type other than dynamic
* https://issues.couchbase.com/browse/NCBC-2308[NCBC-2308]: 
N1QL query situational failure
* https://issues.couchbase.com/browse/NCBC-2309[NCBC-2309]: 
Hybrid/view query errors with situational testing
* https://issues.couchbase.com/browse/NCBC-2316[NCBC-2316]: 
Ensure view request get default timeout if not supplied
* https://issues.couchbase.com/browse/NCBC-2324[NCBC-2324]: 
Random KeyNotFoundException in LogManagerTests.Test_LogLevel_Debug
* https://issues.couchbase.com/browse/NCBC-2350[NCBC-2350]: 
SearchOptions.Raw is unused, and throws an NRE
* https://issues.couchbase.com/browse/NCBC-2351[NCBC-2351]: 
View timeout is not applied to view query string
* https://issues.couchbase.com/browse/NCBC-2352[NCBC-2352]: 
Cleanup Service Exceptions Hiding Context
* https://issues.couchbase.com/browse/NCBC-2353[NCBC-2353]: 
Cleanup .NET SDK 3 Build Warnings
* https://issues.couchbase.com/browse/NCBC-2354[NCBC-2354]: 
Most Integration Tests Failing
* https://issues.couchbase.com/browse/NCBC-2365[NCBC-2365]: 
Ensure Exists checks if deleted is true then exists returns false
* https://issues.couchbase.com/browse/NCBC-2366[NCBC-2366]: 
AnalyticsManager does not exist
* https://issues.couchbase.com/browse/NCBC-2367[NCBC-2367]: 
Methods in ClusterNode have unused "connections" parameter
* https://issues.couchbase.com/browse/NCBC-2369[NCBC-2369]: 
Ping diagnostics are not accurately reporting ping times
* https://issues.couchbase.com/browse/NCBC-2372[NCBC-2372]: 
NRE thrown while initializing cluster
* https://issues.couchbase.com/browse/NCBC-2384[NCBC-2384]: 
SSL connections cannot find node for K/V operations
* https://issues.couchbase.com/browse/NCBC-2389[NCBC-2389]: 
ClusterNode must be associated with a bucket once a bucket has been opened
* https://issues.couchbase.com/browse/NCBC-2397[NCBC-2397]: 
OPS pulses between zero and the expected performance
* https://issues.couchbase.com/browse/NCBC-2402[NCBC-2402]: 
Add ConfigureAwait(false) to all asynchronous code
* https://issues.couchbase.com/browse/NCBC-2407[NCBC-2407]: 
Couchbase.ServiceNotAvailableException: Service n1ql not available
* https://issues.couchbase.com/browse/NCBC-2416[NCBC-2416]: 
ViewQuery failure/hanging
* https://issues.couchbase.com/browse/NCBC-2421[NCBC-2421]: 
Remove default to NotBounded in FTS
* https://issues.couchbase.com/browse/NCBC-2422[NCBC-2422]: 
Error replacing dead connections on N1QL Failover rebalance
* https://issues.couchbase.com/browse/NCBC-2426[NCBC-2426]: 
Service Restart failure - replacing dead connections failure
* https://issues.couchbase.com/browse/NCBC-2429[NCBC-2429]: 
Should be MaxHttpConnections instead of MaxHttpConnection
* https://issues.couchbase.com/browse/NCBC-2446[NCBC-2446]: 
Ensure bootstrapping continues after BucketNotConnected on pre-6.5 servers
* https://issues.couchbase.com/browse/NCBC-2448[NCBC-2448]: 
unpublish concurrent document mutations
* https://issues.couchbase.com/browse/NCBC-2183[NCBC-2183]: 
Exists must use "getMeta" (0xa0)  instead of Observe
* https://issues.couchbase.com/browse/NCBC-2410[NCBC-2410]: 
LookupInResult has NotImplementedException for some methods
* https://issues.couchbase.com/browse/NCBC-2412[NCBC-2412]: 
Cluster.AnaytlicsIndexes throws NotImplementedException
* https://issues.couchbase.com/browse/NCBC-2414[NCBC-2414]: 
Connection terminated when packet exceeds NetworkStream buffer size
* https://issues.couchbase.com/browse/NCBC-2415[NCBC-2415]: 
error CS0649: Field 'SubDocSingularBase<T>.CurrentSpec' is null
* https://issues.couchbase.com/browse/NCBC-2430[NCBC-2430]: 
HttpMaxConnections renaming breaks DI unit tests
* https://issues.couchbase.com/browse/NCBC-2431[NCBC-2431]: 
Failed DNS resolution throws NullReferenceException
* https://issues.couchbase.com/browse/NCBC-2433[NCBC-2433]: 
Fix failing tests involving MaxHttpConnection
* https://issues.couchbase.com/browse/NCBC-2305[NCBC-2305]: 
RequestId, ClientContextId, and Signature Lost After N1QL Query Enumeration
* https://issues.couchbase.com/browse/NCBC-2358[NCBC-2358]: 
Timeout is not written to the packet when using Durability

=== New Features and Behavioral Changes.
* https://issues.couchbase.com/browse/NCBC-2315[NCBC-2315]: 
Improve logging for each service request
* https://issues.couchbase.com/browse/NCBC-2325[NCBC-2325]: 
Add SCRAM-SHA Sasl Authentication
* https://issues.couchbase.com/browse/NCBC-1863[NCBC-1863]: 
Add Flushing or Deleting a Collection logic
* https://issues.couchbase.com/browse/NCBC-1870[NCBC-1870]: 
Support Log Redaction
* https://issues.couchbase.com/browse/NCBC-1915[NCBC-1915]: 
Add new consistency API to SDK 3.0
* https://issues.couchbase.com/browse/NCBC-2151[NCBC-2151]: 
Migrating from SDK 2 to 3.0
* https://issues.couchbase.com/browse/NCBC-2169[NCBC-2169]: 
Migrating from SDK 2 to 3.0
* https://issues.couchbase.com/browse/NCBC-2209[NCBC-2209]: 
 Add Converters/Transcoders per RFC
* https://issues.couchbase.com/browse/NCBC-2220[NCBC-2220]: 
Ensure ClusterOptions properties are integrated into SDK
* https://issues.couchbase.com/browse/NCBC-2234[NCBC-2234]: 
Mark all ErrorContexts as Uncomitted
* https://issues.couchbase.com/browse/NCBC-2302[NCBC-2302]: 
Getting Started Tidy Up
* https://issues.couchbase.com/browse/NCBC-2413[NCBC-2413]: 
Add XxxErrorContext information to K/V
* https://issues.couchbase.com/browse/NCBC-2417[NCBC-2417]: 
Remove all Singular Sub-Document classes
* https://issues.couchbase.com/browse/NCBC-1799[NCBC-1799]: 
Analytics client needs to support streaming results
* https://issues.couchbase.com/browse/NCBC-1989[NCBC-1989]: 
Add connection pooling
* https://issues.couchbase.com/browse/NCBC-2244[NCBC-2244]: 
WaitUntilReady not available at the cluster and bucket levels
* https://issues.couchbase.com/browse/NCBC-2245[NCBC-2245]: 
Cluster-level ping missing
* https://issues.couchbase.com/browse/NCBC-2260[NCBC-2260]: 
Tighten OperationSpec for lookupIn and mutateIn
* https://issues.couchbase.com/browse/NCBC-2293[NCBC-2293]: 
Remove deprecated ErrorAttribute enum
* https://issues.couchbase.com/browse/NCBC-2297[NCBC-2297]: 
Decrease API surface surrounding K/V operations/connections
* https://issues.couchbase.com/browse/NCBC-2299[NCBC-2299]: 
Implement non-streaming fallback for N1QL queries
* https://issues.couchbase.com/browse/NCBC-2300[NCBC-2300]: 
Support custom stream deserializers for view queries
* https://issues.couchbase.com/browse/NCBC-2310[NCBC-2310]: 
Make IQueryResult implementations internal
* https://issues.couchbase.com/browse/NCBC-2312[NCBC-2312]: 
Make IServiceResult.RetryReason read only
* https://issues.couchbase.com/browse/NCBC-2313[NCBC-2313]: 
Align StreamAlreadyReadException with other Couchbase exceptions
* https://issues.couchbase.com/browse/NCBC-2314[NCBC-2314]: 
Implement non-streaming fallback for view queries
* https://issues.couchbase.com/browse/NCBC-2318[NCBC-2318]: 
Refactor view queries to be strongly typed
* https://issues.couchbase.com/browse/NCBC-2319[NCBC-2319]: 
Implement non-streaming fallback for analytics queries
* https://issues.couchbase.com/browse/NCBC-2320[NCBC-2320]: 
Cleanup K/V classes in root namespace
* https://issues.couchbase.com/browse/NCBC-2322[NCBC-2322]: 
Enable symbol packages and SourceLink for debugging
* https://issues.couchbase.com/browse/NCBC-2323[NCBC-2323]: 
Enable C# 8 nullable ref types for buckets/scopes/collections
* https://issues.couchbase.com/browse/NCBC-2327[NCBC-2327]: 
Create Lightweight DI system for Couchbase SDK
* https://issues.couchbase.com/browse/NCBC-2328[NCBC-2328]: 
Update Cluster and Bucket to use DI for Logging
* https://issues.couchbase.com/browse/NCBC-2329[NCBC-2329]: 
Update RetryOrchestrator to use DI for logging
* https://issues.couchbase.com/browse/NCBC-2330[NCBC-2330]: 
Make transaction/serializer/mapper configurable via DI
* https://issues.couchbase.com/browse/NCBC-2331[NCBC-2331]: 
Use DI for Scope and Collection logging
* https://issues.couchbase.com/browse/NCBC-2332[NCBC-2332]: 
Remove default constructor added to BucketBase (CS8618 warning)
* https://issues.couchbase.com/browse/NCBC-2334[NCBC-2334]: 
All integration tests fail, cannot bootstrap
* https://issues.couchbase.com/browse/NCBC-2336[NCBC-2336]: 
Use DI for CouchbaseHttpClient
* https://issues.couchbase.com/browse/NCBC-2337[NCBC-2337]: 
Remove ClusterContext requirement from service clients
* https://issues.couchbase.com/browse/NCBC-2338[NCBC-2338]: 
Use DI for service clients and their loggers
* https://issues.couchbase.com/browse/NCBC-2340[NCBC-2340]: 
Use DI for logging in configuration handlers
* https://issues.couchbase.com/browse/NCBC-2341[NCBC-2341]: 
Use DI for OrphanedResponseLogger logging
* https://issues.couchbase.com/browse/NCBC-2343[NCBC-2343]: 
Use DI for logging in data structures
* https://issues.couchbase.com/browse/NCBC-2344[NCBC-2344]: 
Use DI for logging in managers
* https://issues.couchbase.com/browse/NCBC-2345[NCBC-2345]: 
Use DI for logging in DNS resolver
* https://issues.couchbase.com/browse/NCBC-2346[NCBC-2346]: 
Use DI for logging in GetResult
* https://issues.couchbase.com/browse/NCBC-2347[NCBC-2347]: 
Use DI for logging in QueryUriTesters 
* https://issues.couchbase.com/browse/NCBC-2348[NCBC-2348]: 
Use DI for VBucket and ErrorMap logging
* https://issues.couchbase.com/browse/NCBC-2349[NCBC-2349]: 
Enable Nullable Ref Types in ClusterOptions
* https://issues.couchbase.com/browse/NCBC-2355[NCBC-2355]: 
Support deserialization of ClusterOptions from configuration
* https://issues.couchbase.com/browse/NCBC-2356[NCBC-2356]: 
Move content services directory to root in Couchbase.UnitTests
* https://issues.couchbase.com/browse/NCBC-2357[NCBC-2357]: 
Enable nullable ref types for XxxOptions classes
* https://issues.couchbase.com/browse/NCBC-2359[NCBC-2359]: 
Use DNS resolver for IP address resolution
* https://issues.couchbase.com/browse/NCBC-2360[NCBC-2360]: 
Use DNS resolver in Ketama key mapper and ClusterContext
* https://issues.couchbase.com/browse/NCBC-2362[NCBC-2362]: 
Make ConfigChanged handling async
* https://issues.couchbase.com/browse/NCBC-2363[NCBC-2363]: 
Use DNS resolver for VBucketServerMap.IPEndPoints
* https://issues.couchbase.com/browse/NCBC-2364[NCBC-2364]: 
Enable null reference types for K/V specs/results
* https://issues.couchbase.com/browse/NCBC-2368[NCBC-2368]: 
Remove Servers From ClusterOptions
* https://issues.couchbase.com/browse/NCBC-2370[NCBC-2370]: 
Support custom port numbers in ConnectionString
* https://issues.couchbase.com/browse/NCBC-2371[NCBC-2371]: 
Make BucketConfig and other config serialization classes internal
* https://issues.couchbase.com/browse/NCBC-2373[NCBC-2373]: 
Implement abstraction layer for connection pool implementations
* https://issues.couchbase.com/browse/NCBC-2374[NCBC-2374]: 
Replace TKey with string parameter in persistent collections
* https://issues.couchbase.com/browse/NCBC-2376[NCBC-2376]: 
Cleanup BootstrapUri on ClusterNode
* https://issues.couchbase.com/browse/NCBC-2377[NCBC-2377]: 
Implement auto scaling on connection pools
* https://issues.couchbase.com/browse/NCBC-2378[NCBC-2378]: 
Add log redaction to DataFlowConnectionPool
* https://issues.couchbase.com/browse/NCBC-2379[NCBC-2379]: 
Respect couchbases scheme for DNS SRV lookup
* https://issues.couchbase.com/browse/NCBC-2380[NCBC-2380]: 
ClusterOptions MgmtPort and EnableTls cleanup
* https://issues.couchbase.com/browse/NCBC-2381[NCBC-2381]: 
Cleanup IConnection interface
* https://issues.couchbase.com/browse/NCBC-2382[NCBC-2382]: 
Support multiplexing on SslConnection
* https://issues.couchbase.com/browse/NCBC-2383[NCBC-2383]: 
NodeAdapter is null on non-bootstrap nodes
* https://issues.couchbase.com/browse/NCBC-2387[NCBC-2387]: 
Reduce heap allocations related to K/V operation response handling
* https://issues.couchbase.com/browse/NCBC-2391[NCBC-2391]: 
Include XML documentation in NuGet package
* https://issues.couchbase.com/browse/NCBC-2392[NCBC-2392]: 
Reduce heap allocations around MultiplexingConnection async state
* https://issues.couchbase.com/browse/NCBC-2393[NCBC-2393]: 
Align QueryScanConsistency with the RFC
* https://issues.couchbase.com/browse/NCBC-2398[NCBC-2398]: 
Change ICollection interface to ICouchbaseCollection interface
* https://issues.couchbase.com/browse/NCBC-2399[NCBC-2399]: 
Add bootstrap service
* https://issues.couchbase.com/browse/NCBC-2408[NCBC-2408]: 
Add BucketContext or equivalent for cohesion and less coupling
* https://issues.couchbase.com/browse/NCBC-2409[NCBC-2409]: 
Route nodes into service specific CouchbaseNodeCollections
* https://issues.couchbase.com/browse/NCBC-2425[NCBC-2425]: 
Reduce heap allocations calling BucketAsync


== Pre-releases

Numerous _Alpha_ and _Beta_ releases were made in the run-up to the 3.0 release, and although unsupported, the release notes and download links are retained for archive purposes xref:3.0-pre-release-notes.adoc[here].


== Older Releases

Although https://www.couchbase.com/support-policy/enterprise-software[no longer supported], documentation for older releases continues to be available in our https://docs-archive.couchbase.com/home/index.html[docs archive].
// end::all[]
