= Compression
:page-topic-type: concept
:page-edition: Enterprise Edition
:page-aliases:ROOT:compression-intro,compression-intro

include::project-docs:partial$attributes.adoc[]

[abstract]
In response to increasing volumes of data being sent over the wire, Couchbase Data Platform now provides data compression between the SDK and Couchbase Server.
However, stable Snappy support is not yet available in .NET.



Couchbase Server (in the Enterprise Edition) stores documents in compressed form, xref:{version-server}@server:learn:buckets-memory-and-storage/compression.adoc#compression-modes[when it is enabled in the server for a particular bucket], using Snappy Compression.
As the Snappy compression library is not available for .NET, the server will automatically uncompress any compressed documents before sending them to the .NET client.

If compression is set to _active_ on the server, documents will be stored there in compressed form, even though the .NET client has sent them uncompressed, thus saving storage space (but not network bandwidth).
