= The Data Model
:nav-title: Data Model
:page-topic-type: concept
:page-aliases: core-operations, datastructures

[abstract]
Couchbase's use of JSON as a storage format allows powerful search and query over documents.
Several data structures are supported by the SDK, including map, list, queue, and set.


include::partial$alpha-warning.adoc[]


The power to search, query, and easily work with data in Couchbase, comes from the choice of JSON as a storage format.
Non-JSON storage is supported -- see the xref:nonjson.adoc[Binary Storage Documentation] -- 
including UTF-8 strings, raw sequences of bytes, and language specific serializations,
however, only JSON is supported by xref:n1ql-query.adoc[Query].
In Couchbase, JSON’s key-value structure allows the storage of collection data structures such as lists, maps, sets and queues
-- __see xref:#data-structures[below]__.
JSON’s tree-like structure allows operations against xref:subdocument.adoc[specific paths in the Document],
and efficient support for these data structures.





== Data Structures 



Data structures in Couchbase are similar in concept to data structures in C# (.NET):

* *Map* is like .NET `Dictionary<TKey, TValue>`, and is a key-value structure, where a value is accessed by using a key string.
* *List* is like a .NET `List<TValue>` and is a sequential data structure.
Values can be placed in the beginning or end of a list, and can be accessed using numeric indexes.
* *Queue* is like a `IQueue` implementation which offers FIFO (first-in-first-out) semantics, allowing it to be used as a lightweight job queue.
* *Set* is a wrapper over a `List<TValue>` which provides the ability to handle unique values.

These data structures are stored as JSON documents in Couchbase, and can therefore be accessed using N1QL and normal key-value operations.
Data structures can also be manipulated using the traditional sub-document and full-document KV APIs.

Using the data structures API may help your application in two ways:

* *Simplicity*: Data structures provide high level operations by which you can deal with documents as if they were container data structures.
Adding an item to a dictionary is expressed as `MapAdd`, rather than retrieving the entire document, modifying it locally, and then saving it back to the server.
* *Efficiency*: Data structure operations do not transfer the entire document across the network.
Only the relevant data is exchanged between client and server, allowing for less network overhead and lower latency.

NOTE: Besides the [.api]`IBucket` level data structure methods, there is a new namespace called [.api]`Couchbase.Collections` which contains implementations of some of the core interfaces in [.api]`System.Collection.Generics` such as [.api]`ISet<TValue>`, [.api]`IList<TValue>`, [.api]`IDictionary<Tkey, TValue>` and a [.api]`CouchbaseQueue` class.
See section <<couchbase-collections,The Couchbase.Collections Namespace>> below for more details.

== Creating a Data Structure

