= Document
:nav-title: Documents & Doc Ops
:page-topic-type: concept
:page-aliases: ROOT:documents,ROOT:documents-basics,ROOT:documents-atomic
:link-with-underscores: https://docs.couchbase.com/sdk-api/couchbase-net-client/html/T_Couchbase_KeyValue_IBinaryCollection.htm

include::partial$attributes.adoc[]

[abstract]
Couchbase supports CRUD operations, various data structures, and binary documents.

Although query and path-based (Sub-Document) services are available, the simplicity of the document-based kv interface is the fastest way to perform operations involving single documents.

include::{version-server}@sdk:shared:partial$documents.adoc[tag=document]

== Primitive Key-Value Operations

[source,python]
----
upsert(docid, document)
insert(docid, document)
replace(docid, document)
get(docid)
remove(docid)
----

include::{version-server}@sdk:shared:partial$documents.adoc[tag=crud-overview]

include::{version-server}@sdk:shared:partial$documents.adoc[tag=store-update]

[NOTE]
====
If you wish to only modify certain parts of a document, you can use xref:subdocument-operations.adoc[sub-document] operations which operate on specific subsets of documents:

[source,C#,indent=0]
----
await collection.MutateInAsync("customer123", new List<MutateInSpec>
{
    MutateInSpec.Upsert("fax", "311-555-0151"),
    MutateInSpec.Upsert("cell", "311-555-5101")
});
----

or xref:{version-server}@server:n1ql:n1ql-language-reference/update.adoc[N1QL UPDATE] to update documents based on specific query criteria:

[source,sql]
----
update `default` SET sale_price = msrp * 0.75 WHERE msrp < 19.95;
----
====

include::{version-server}@sdk:shared:partial$documents.adoc[tag=get_generic]

[source,sql]
----
SELECT * FROM default USE KEYS ["docid"];
----

or

[source,sql]
----
SELECT * FROM default WHERE META(default).id = "docid";
----

You can also retrieve _parts_ of documents using xref:subdocument-operations.adoc[sub-document operations], by specifying one or more sections of the document to be retrieved

[source,C#,indent=0]
----
var r = await collection.LookupInAsync("user:kingarthur", new List<LookupInSpec>
{
    LookupInSpec.Get("contact.name"),
    LookupInSpec.Get("contact.email")
});

string name = r.ContentAs<string>(0);
string email = r.ContentAs<string>(1);
----

// Counters

include::{version-server}@sdk:shared:partial$documents.adoc[tag=counters1]

[source,C#,indent=0]
----
var counterDocId = "counter-doc";
// Increment by 1, creating doc if needed
await collection.Binary.IncrementAsync(counterDocId);
// Decrement by 1
await collection.Binary.DecrementAsync(counterDocId);
// Decrement by 5
await collection.Binary.DecrementAsync(counterDocId, options =>
{
    options.Delta(5);
});
----

include::{version-server}@sdk:shared:partial$documents.adoc[tag=counters2]

[source,C#,indent=0]
----
var rv = await collection.GetAsync("counter_id");
var value = rv.ContentAs<int>();
var cas = rv.Cas;
if (ShouldIncrementValue(value))
{
    await collection.ReplaceAsync("counter_id", value + incrementAmount, options =>
    {
        options.Cas(cas);
    });
}
----

include::{version-server}@sdk:shared:partial$documents.adoc[tag=counters3]


=== Use Cases

The SDK provides a high-level abstraction over the simple `incr()`/`decr()` of Couchbase Server's memcached binary protocol, using `collections.binary()`.
This enables you to work with counters using `get()` and `upsert()` operations -- allowing, _inter alia_, the use of durability options with the operations.
You will find several ways of working with counters {link-with-underscores}[in the API docs].

// Expiry
include::{version-server}@sdk:shared:partial$documents.adoc[tag=expiration]

IMPORTANT: If you are using the overloads that take `IDocument`, note that the `IDocument.Expiry` property assumes ms (milli-seconds), and is converted to seconds before being sent to the server.
All other overloads take a `TimeSpan` or an `uint`, and assume an expiry in seconds
A time of zero will set the document to never expire
(a negative number will set expiry to immediate -- creating a xref:7.0@server:learn:buckets-memory-and-storage/storage.adoc#tombstones[tombstone]).
Values above 0ms but below 1000ms are rounded up to one second before being sent to the server -- _if you are using .NET SDK 3.0.4 or later_.
