= Couchbase .NET SDK 3.2
:page-type: landing-page
:page-layout: landing-page-top-level-sdk
:page-role: tiles
:!sectids:
:page-aliases: ROOT:dotnet-sdk.sdoc


++++
<div class="card-row two-column-row">
++++


[.column]
====== {empty}
[.content]
The Couchbase .NET client allows applications to connect to Couchbase Server using any Common Language Runtime (CLR) language, including C#, F#, and VB.NET.
The SDK is written in C#, and some of its idiomatic patterns reflect that choice.

[.column]
[.content]
[source,c#]
----
await collection
    .InsertAsync(key, Encoding.UTF8.GetBytes("hello"), options =>
    {
        options.Expiry(TimeSpan.FromSeconds(30));
        options.Timeout(TimeSpan.FromMinutes(5));
    })
    .ConfigureAwait(false);

using var result = await collection.GetAsync(key, options => options.Transcoder(new LegacyTranscoder()))
    .ConfigureAwait(false);
----

++++
</div>
++++



[.column]
====== {empty}

== Couchbase .NET SDK 3.2

++++
<div class="card-row three-column-row">
++++


[.column]
====== {empty}
.Getting Started

[.content]
Dive right in with a xref:start-using-sdk.adoc[quick install and Hello World].
// Try out our xref:sample-application.adoc[Travel Sample Application].
// And take a look at the xref:howtos:working-with-collections.adoc[developer preview of Collections].
[]
////
Install using the NuGet Package Manager:
[source,csharp]
----
> Install-Package CouchbaseNetClient -Version 3.2.0
----

Or using the CLI:
[source,csharp]
----
> dotnet add package CouchbaseNetClient --version 3.2.0
----

Or using Package Reference
[source,csharp]
----
<PackageReference Include="CouchbaseNetClient" Version="3.2.0" />
----
////

[.column]
====== {empty}
.Practical Howto Docs

[.content]
Connect to our services -- xref:howtos:kv-operations.adoc[data (KV)];
xref:howtos:n1ql-queries-with-sdk.adoc[Query];
xref:howtos:full-text-searching-with-sdk.adoc[Search];
xref:howtos:analytics-using-sdk.adoc[Analytics];
xref:howtos:view-queries-with-sdk.adoc[Views] --
and the xref:howtos:subdocument-operations.adoc[Sub-Document API].

[.column]
====== {empty}
.Reference Guides

[.content]
The documentation supplements the practical Howto docs with references and xref:concept-docs:concepts.adoc[concept guides], for those who prefer a broader understanding before diving in and coding.
[]
https://docs.couchbase.com/sdk-api/couchbase-net-client[API Docs^]


[.column]
====== {empty}
.What's Hot?

[.content]
Leverage the new Couchbase Server Scopes and Collection features to build multi-tenant micro-service application.
Integrate with Open Telemetry API to instrument telemetry data for your mission critical workloads that will make troubleshooting and debugging of your applications easier than ever.
Add an additional layer of security and protect your sensitive workloads using our Client Side Field Level Encryption capability. 

xref:howtos:distributed-acid-transactions-from-the-sdk.adoc[Distributed ACID Transactions from the .NET SDK].


[.column]
====== {empty}
.About

[.content]
Those useful nuts-and-bolts guides to
xref:project-docs:compatibility.adoc[compatibility tables];
xref:project-docs:sdk-release-notes.adoc[release notes];
xref:project-docs:get-involved.adoc[contribution guide]; and the
xref:project-docs:migrating-sdk-code-to-3.n.adoc[migration guide] for moving to the 3.0 API.

[.column]
====== {empty}
.Community

[.content]
For community help, visit the https://forums.couchbase.com/c/net-sdk/6[Couchbase forums^].
The .NET SDK can be combined with many other projects in the broader .NET ecosystem and beyond.
// Such as?
//  -- in the https://blog.couchbase.com/[Couchbase Blog^] there are examples covering everything from ????

++++
</div>
++++

