= Hello World
:page-aliases: ROOT:getting-started.adoc,ROOT:start-using.adoc,ROOT:hello-couchbase.adoc,ROOT:start-using-sdk.adoc
:page-toclevels: 3
:description: Install, connect, try. A quick start guide to get you up and running with Couchbase and the {name-sdk}.
:forum-link: https://forums.couchbase.com/c/net-sdk/6
:complete-code-include: include::devguide:example$dotnet/StartUsingCapella.cs[]
:page-partial:
:lang: csharp
// :example-source-lang: C#


// Note to editors
//
// This page pulls in content from
// https://github.com/couchbase/docs-sdk-common/blob/api/3.10/modules/shared/partials/start-using-sdk.adoc
//
// and code samples from
// https://github.com/couchbase/docs-sdk-dotnet/tree/release/3.10/modules/devguide/examples/dotnet
//
// It can be seen built at
// https://docs.couchbase.com/dotnet-sdk/3.10/hello-world/start-using-sdk.html


[abstract]
{description}



// intro
include::{version-common}@sdk:shared:partial$start-using-sdk.adoc[tag=intro]


.Creating a new database entry with the {name_platform} SDK, using `upsert()`
[source,{lang-code}]
----
include::devguide:example$dotnet/KvOperations.cs[tag=upsertwithdurability,indent=0]
----




// intro-upsert
include::{version-common}@sdk:shared:partial$start-using-sdk.adoc[tag=intro-upsert]


// TIP - DEE tutoral & Student record tutorial
// include::{version-common}@sdk:shared:partial$start-using-sdk.adoc[tag=other-tutorials]
// ^Uncomment this once the student record tutorial is ported.



== Before You Start


include::{version-common}@sdk:shared:partial$start-using-sdk.adoc[tag=before]



// Script the docs!
// Can any of the SDK installations be scripted?



=== Prerequisites

include::partial$supported.adoc[]
See the xref:project-docs:compatibility.adoc#dotnet-compatibility[Compatibility] section for more details.



// self-managed + Capella pre-reqs
include::{version-common}@sdk:shared:partial$start-using-sdk.adoc[tag=prereq]



== Installation

The quickest way to get up and running is with NuGet, from the Package Manager Console,  within your project:

. From the Visual Studio menu bar, click *Tools*.
. Select *NuGet Package Manager > Package Manager Console*.
. In the console, enter the package installation command:
 ** To install the latest version:

[source,console]
----
Install-Package CouchbaseNetClient
----

All other installation methods can be found in our xref:project-docs:sdk-full-installation.adoc[full installation guide].



=== IDE Plugins

include::{version-common}@sdk:shared:partial$start-using-sdk.adoc[tag=ide]


=== Grab the Code

include::{version-common}@sdk:shared:partial$start-using-sdk.adoc[tag=complete-code]


== Connect to your Database

Connect to your Couchbase Capella operational cluster (or your local Couchbase Cluster, if you are trying out self-managed Couchbase).


[tabs,sync-group-id="Couchbase Capella|Self-Managed Couchbase Server"]
==== 
Couchbase Capella::
+
--
[source,csharp]
----
include::devguide:example$dotnet/Cloud.cs[tags=connect,indent=0]
----
--

Self-Managed Couchbase Server::
+
--
[source,csharp]
----
include::devguide:example$dotnet/StartUsing.cs[tag=connect,indent=0]
----
--

Cloud Native Gateway (CNG)::
+
--
include::{version-common}@sdk:shared:partial$start-using-sdk.adoc[tag=cng]

[source,csharp]
----
    var cluster = await Cluster.ConnectAsync(
        // Update these credentials for your Local Couchbase instance!
        "couchbase2://<your-ip-address>",
        "Administrator",
        "password");
----

Read more on the xref:howtos:managing-connections.adoc#cloud-native-gateway[Connections] page.
--
====

include::{version-common}@sdk:shared:partial$start-using-sdk.adoc[tag=deeper-conn]



=== Opening a Bucket

Following successful authentication, open the bucket with:
////
[source,csharp]
----
include::devguide:example$dotnet/StartUsing.cs[tag=bucket,indent=0]
----
////
[source,csharp]
----
include::devguide:example$dontnet/ClusterExample.cs[tag=waitUntilReady,indent=0]
----


////
client has not yet completed bootstrapping (connecting to the cluster, getting the configuration, connecting to the nodes).
////


`waitUntilReady` is an optional call,
but it is good practice to use it.
Opening resources such as buckets is asynchronous --
that is, the `cluster.bucket` call returns immediately and proceeds in the background.
`waitUntilReady` ensures that the bucket resource is fully loaded before proceeding.
If not present, then the first key-value (KV) operation on the bucket will wait for it to be ready.
// As with the earlier `Cluster.connect`, we use `.get` on the result here for simplicity.

*Collections* allow documents to be grouped by purpose or theme, according to a specified *scope* -- see data modeling, <<data-modeling,below>>.
Here we will use the `airport` collection within the `inventory` scope from `travel-sample` bucket as an example.

[source,csharp]
----
var scope = await bucket.ScopeAsync("inventory");
var collection = await scope.CollectionAsync("airport");
----


== Create, Read, Update, Delete

include::{version-common}@sdk:shared:partial$start-using-sdk.adoc[tag=crud]



////
=== JSON

We'll create a snippet of JSON to work with, using the client's own JSON library,
but you can read about the {name-sdk}'s support for other JSON libraries on the
xref:howtos:json.adoc[] page.

[source,java]
----
include::devguide:example$java/StartUsingCapella.java[tag=json,indent=0]
----
////


=== Insert (Create) and Upsert


xref:howtos:kv-operations.adoc[Data operations], like storing and retrieving documents, can be done using simple methods on the `Collection` class such as `Collection.InsertAsync()` and `Collection.UpsertAsync()`.
`insert` and `upsert` will both create a new document.
The difference between the two is that if a document with that key already exists, the `insert` operation will fail,
throwing a `DocumentExistsException` --
while the `upsert` operation will succeed, replacing the content.


.Insert
[source,csharp]
----
include::devguide:example$dotnet/KvOperations.cs[tag=insert,indent=0]
----


=== Get (Read)

The `get` method reads a document from a collection.
If the collection does not have a document with this ID, the `get` method also throws `DocumentNotFoundException`.

The following code snippet creates a new document in a custom scope and collection and then fetches it again, printing the result.

[source,csharp]
----
include::devguide:example$dotnet/StartUsing.cs[tag=upsert-get,indent=0]
----


=== Replace (Update) and Overloads

The replace method updates the value of an existing document.
Here we add a couple of useful options for expiry and timeout --
read more on our xref:howtos:kv-operations.adoc[using the Data Service] page.

[source,csharp]
----
include::example$KvOperations.cs[tag=replacewithcas,indent=0]
----

CAUTION: When you replace a document, it's usually good practice to use xref:howtos:kv-operations.adoc#optimistic-locking[optimistic locking].
Otherwise, changes might get lost if two people change the same document at the same time.



=== Remove (Delete)

When removing a document, you will have the same concern for durability as with any additive modification to the Bucket:

.Remove (with options)
[source,csharp]
----
include::example$KvOperations.cs[tag=remove,indent=0]
----

Like `Replace`, `Remove` also optionally takes the xref:howtos:kv-operations.adoc#what-is-cas[CAS value] if you want to make sure you are only removing the document if it hasn’t changed since you last fetched it.


== Data Modeling

include::{version-common}@sdk:shared:partial$start-using-sdk.adoc[tag=data-model]



== What Next?

////
Query and KV -
both
- but different emphasis on modelling objects....
////


include::{version-common}@sdk:shared:partial$start-using-sdk.adoc[tag=what-next]























////

= Start Using the .NET SDK
:description: The Couchbase .NET SDK enables you to interact with a Couchbase Server cluster from .NET using C# and other .NET languages.
:page-aliases: ROOT:getting-started,ROOT:start-using,ROOT:hello-couchbase,ROOT:start-using-sdk
:page-toclevels: 2
:page-pagination: full


[abstract]
{description}
It offers an asynchronous API based on the link:https://docs.microsoft.com/en-us/dotnet/standard/asynchronous-programming-patterns/task-based-asynchronous-pattern-tap[_Task-based Asynchronous Pattern (TAP)_].


The Couchbase .NET client allows applications to connect to Couchbase Server using any Common Language Runtime (CLR) language, including C#, F#, and VB.NET.
The SDK is written in C#, and some of its idiomatic patterns reflect that choice.

In this guide, you will learn:

* How to xref:connect[connect to Couchbase Capella or Couchbase Server].

* How to xref:add-and-retrieve-documents[add and retrieve Documents].

* How to xref:sql-lookup[lookup documents] with the {sqlpp_url}[{sqlpp} (formerly N1QL)] query language.

== Hello Couchbase

We will go through the code sample step by step, but for those in a hurry to see it, here it is:

[{tabs}]
====
Couchbase Capella Sample::
+
--
If you are connecting to https://docs.couchbase.com/cloud/index.html[Couchbase Capella], be sure to get the correct endpoint as well as user, password -- and see the <<cloud-connections, Cloud section>>, below.

[source,csharp]
----
include::devguide:example$dotnet/Cloud/Cloud.cs[tags=**]
----

The Couchbase Capella free tier version comes with the Travel Sample Bucket, and its Query indexes, loaded and ready.
--

Local Couchbase Server::
+
--
[source,csharp]
----
include::example$StartUsing.cs[tags=**]
----

As well as the .NET SDK (see below), and a running instance of Couchbase Server, you will need to load up the Travel Sample Bucket
using either the xref:7.2@server:manage:manage-settings/install-sample-buckets.adoc#install-sample-buckets-with-the-ui[Web interface]
or the xref:7.2@server:manage:manage-settings/install-sample-buckets.adoc#install-sample-buckets-with-the-cli[command line].
--
====


== Installing the SDK

include::partial$supported.adoc[]
See the xref:project-docs:compatibility.adoc#dotnet-compatibility[Compatibility] section for more details.

NOTE: Capella's root certificate is *not* signed by a well known CA (Certificate Authority).
However, as the certificate is bundled with the SDK when using .NET 6.0 or later, it is trusted by default.
.NET Framework clients will have to add it to the Windows certificate store.


=== Quick Installation

The quickest way to get up and running is with NuGet, from the Package Manager Console,  within your project:

. From the Visual Studio menu bar, click *Tools*.
. Select *NuGet Package Manager > Package Manager Console*.
. In the console, enter the package installation command:
 ** To install the latest version:

[source,console]
----
Install-Package CouchbaseNetClient
----

All other installation methods can be found in our xref:project-docs:sdk-full-installation.adoc[full installation guide].

== Prerequisites

The following code samples assume:

[{tabs}]
====
Couchbase Capella::
+
--
* You have signed up to https://cloud.couchbase.com/sign-up[Couchbase Capella].

* You have created your own bucket, or loaded the Travel Sample dataset.
Note, the Travel Sample dataset is installed automatically when deploying a Capella free tier cluster.

* A user is created with permissions to access the cluster (at least Application Access permissions).
See the xref:cloud:get-started:cluster-and-data.adoc#credentials[Capella connection page] for more details.

IMPORTANT: Couchbase Capella uses xref:cloud:organizations:organization-projects-overview.adoc[Roles] to control user access to cluster resources.
For the purposes of this guide, you can use the *Organization Owner* role automatically assigned to your account during installation of the Capella cluster.
In a production scenario, we strongly recommend setting up users with more granular access roles as a best practice.
--

Local Couchbase Server::
+
--
* xref:{version-server}@server:getting-started/do-a-quick-install.adoc[Couchbase Server] is installed and accessible locally.

* You have created your own bucket, or loaded the Travel Sample dataset using the xref:{version-server}@server:manage:manage-settings/install-sample-buckets.adoc#install-sample-buckets-with-the-ui[Web interface].

* A user is created with permissions to access your cluster (at least Application Access permissions).
See xref:{version-server}@server:manage:manage-security/manage-users-and-roles.adoc[Manage Users, Groups and Roles] for more details.

IMPORTANT: Couchbase Server uses xref:{version-server}@server:learn:security/roles.adoc[Role Based Access Control (RBAC)] to control access to resources.
In this guide we suggest using the *Full Admin* role created during setup of your local Couchbase Server cluster.
For production client code, you will want to use more appropriate, restrictive settings.
--
====

== Step by Step

Start a new console project (in Visual Studio or VS Code, etc). 
Go to our xref:platform-help.adoc[Platform Introduction] if you don't already have an editor or IDE setup for working in .NET -- e.g. you are evaluating the .NET SDK, but .NET is not your normal platform.

Firstly, you will need to have a few `using` statements at the top of *Program.cs* in your console program:

[source,csharp]
----
include::example$StartUsing.cs[tag=using,indent=0]
----

=== Connect

Connect to your cluster by calling the `Cluster.ConnectAsync()` method and pass it your connection details.
The basic connection details that you’ll need are given below -- for more background information, see xref:howtos:managing-connections.adoc[].

[{tabs}] 
====
Capella Connection::
+
--
From version 3.3, the .NET SDK includes Capella's standard certificates by default, so you do not need to additional configuration.
You do need to enable TLS, which can be done by simply using `couchbases://` in the connection string as in this example.

[source,csharp]
----
include::devguide:example$dotnet/Cloud/Cloud.cs[tag=connect,indent=0]
----

When accessing Capella from a different Wide Area Network or Availability Zone, you may experience latency issues with the default connection settings.
SDK 3.4 introduces a `wan-development` Configuration Profile, which provides pre-configured timeout settings suitable for working in high latency environments.
Basic usage is shown in the example above, but if you want to learn more see xref:ref:client-settings.adoc#constrained-network-environments[Constrained Network Environments].

CAUTION: The Configuration Profiles feature is currently a xref:dotnet-sdk:project-docs:compatibility.adoc#interface-stability[Volatile API] and may be subject to change.
--

Local Server Connection::
+
--
[source,csharp]
----
include::example$StartUsing.cs[tag=connect,indent=0]
----

For developing locally on the same machine as Couchbase Server, your URI can be `couchbase://localhost`.
For production deployments, you will want to use a secure server, with `couchbases://`.
--
====

Following successful authentication, add this code snippet to access your `Bucket`:

[source,csharp]
----
include::example$StartUsing.cs[tag=bucket,indent=0]
----

=== Add and Retrieve Documents

Collections allow Documents to be grouped by purpose or theme, according to specified _Scope_.
Our Travel Sample bucket has separate scopes for inventory (flights, etc.), and for tenants (different travel agents).

[source,csharp]
----
include::devguide:example$dotnet/Cloud/Cloud.cs[tag=collection,indent=0]
----

xref:howtos:kv-operations.adoc[Data operations], like storing and retrieving documents, can be done using simple methods on the `Collection` class such as `Collection.GetAsync()` and `Collection.UpsertAsync()`.

To get you started the following code creates a new document in a custom scope and collection and then fetches it again, printing the result.

[source,csharp]
----
include::example$StartUsing.cs[tag=upsert-get,indent=0]
----

=== {sqlpp} Lookup

Couchbase {sqlpp} queries can be performed at the `Cluster` or `Scope` level by invoking `Cluster.QueryAsync()` or `Scope.QueryAsync()`.

Cluster level queries require you to specify the fully qualified keyspace each time (e.g. `travel-sample.inventory.airline`).
However, with a Scope level query you only need to specify the Collection name -- which in this case is `airline`:

[source,csharp]
----
include::devguide:example$dotnet/Cloud/Cloud.cs[tag=n1ql-query,indent=0]
----

You can learn more about {sqlpp} queries on the xref:howtos:n1ql-queries-with-sdk.adoc[Query page].

== Next Steps

Now you're up and running, try one of the following:

* Our xref:hello-world:sample-application.adoc[Travel Sample Application] demonstrates all the basics you need to know;
* Explore xref:howtos:kv-operations.adoc[Key Value Operations] against a document database;
* Or xref:howtos:n1ql-queries-with-sdk.adoc[Query] with our SQL-based {sqlpp} query language;
// * Try longer-running queries with our xref:howtos:analytics-using-sdk.adoc[Analytics Service];
// * A xref:howtos:full-text-searching-with-sdk.adoc[Full Text Search];
* Or read up on xref:concept-docs:data-services.adoc[which service fits your use case].


=== Additional Resources

The https://docs.couchbase.com/sdk-api/couchbase-net-client/api/index.html[API reference] is generated for each release.
Older API references are linked from their respective sections in the xref:project-docs:sdk-release-notes.adoc[Release Notes].

xref:project-docs:migrating-sdk-code-to-3.n.adoc[The Migrating from SDK2 to 3 page] highlights the main differences to be aware of when migrating your code from our earlier 2.x .NET SDK.

// Couchbase welcomes community contributions to the .NET SDK.
// The .NET SDK source code is available on https://github.com/couchbase/couchbase-net-client[GitHub].

=== Troubleshooting

* Couchbase Server is designed to work in the same WAN or availability zone as the client application.
If you're running the SDK on your laptop against a Capella cluster, see further information on:
** Notes on xref:ref:client-settings.adoc#constrained-network-environments[Constrained Network Environments].
** xref:project-docs:compatibility.adoc#network-requirements[Network Requirements].
** If you have a consumer-grade router which has problems with DNS-SRV records review our xref:howtos:troubleshooting-cloud-connections.adoc#troubleshooting-host-not-found[Troubleshooting Guide].
* Our https://forums.couchbase.com/c/net-sdk/6[community forum] is a great source of help.
////
