= Install and Start Using the .NET SDK with Couchbase Server
:page-aliases: ROOT:getting-started,ROOT:start-using,ROOT:hello-couchbase,ROOT:start-using-sdk
:navtitle: Start Using the SDK

[abstract]
The Couchbase .NET SDK enables you to interact with a Couchbase Server cluster from .NET using C# and other .NET languages.
It offers an asynchronous API based on the _Task-based Asynchronous Pattern (TAP)_.

The Couchbase .NET client allows applications to connect to Couchbase Server using any Common Language Runtime (CLR) language, including C#, F#, and VB.NET. 
The SDK is written in C#, and some of its idiomatic patterns reflect that choice.

== Installing the SDK

include::partial$supported.adoc[]
The library is distributed in a number of ways:

|===
|NuGet |NuGet package host at https://www.nuget.org/packages/CouchbaseNetClient/[nuget.org] (_recommended_)
|Zip |Zip files for each release are linked from the Release Notes xref:project-docs:sdk-release-notes.adoc[here].
|Build from Source |Build the library from https://github.com/couchbase/couchbase-net-client/[source available on GitHub] (not officially supported)
|===


== Hello Couchbase

Start a new console project (in Visual Studio or VS Code, etc). +
Go to our xref:platform-help.adoc[Platform Introduction] if you don't already have an editor or IDE setup for working in .NET -- e.g. you are evaluating the .NET SDK, but .NET is not your normal platform.

Install the latest 3.1 https://www.nuget.org/packages/CouchbaseNetClient/[CouchbaseNetClient^] NuGet package.

The following code samples assume:

* Couchbase Server is installed and accessible locally (xref:server:getting-started:do-a-quick-install.adoc[Do a Quick Install] if you don't already have Couchbase Server installed).
* You have create a bucket (perhaps using the xref:6.6@server:manage:manage-settings/install-sample-buckets.adoc[travel-sample dataset], or by creating a new bucket).
* You have created a Couchbase user named "username" with permissions to access the cluster (at least Application Access permissions).

Firstly, you will need to have a few `using` statements at the top of *Program.cs* in your console program:
[source,csharp]
----
include::example$StartUsing.cs[tag=using,indent=0]
----

Then you can connect to the cluster:

[source,csharp]
----
include::example$StartUsing.cs[tag=connect,indent=0]
----

Couchbase uses xref:server:learn:security/roles.adoc[Role Based Access Control (RBAC)] to control access to resources.
If you're developing client code on the same machine as the Couchbase Server, your URI can be _couchbase://localhost_.

Then open the bucket:
[source,csharp]
----
include::example$StartUsing.cs[tag=bucket,indent=0]
----

Substitute whatever bucket name you want for _bucket-name_ in the above example.

The 3.1 SDK is ready for the introduction of xref:concept-docs:collections.adoc[Collections] in the xref:7.0@server:introduction:whats-new.adoc#whats-new-server-700[next release] of the Couchbase Data Platform.
The latest release, Couchbase Server 6.6, brings a limited _Developer Preview_ of Collections, allowing Documents to be grouped by purpose or theme, according to specified _Scope_.
Here we will use the `DefaultCollection`, which covers the whole Bucket and _must be used when connecting to a 6.6 cluster or earlier_.

[source,csharp]
----
include::example$StartUsing.cs[tag=collection,indent=0]
----

To get you started the following code creates a new document and then fetches it again, printing the result.

[source,csharp]
----
include::example$StartUsing.cs[tag=upsert-get,indent=0]
----

[NOTE]
====
Other possible key/value CRUD Operations are described in detail on the xref:howtos:kv-operations.adoc[KV Operations page].
====

You can also perform a N1QL query with the cluster object:

[source,csharp]
----
include::example$StartUsing.cs[tag=n1ql-query,indent=0]
----

You can learn more about N1QL queries on the xref:howtos:n1ql-queries-with-sdk.adoc[Query page].

== Full Example

If you want to copy and paste to run the full example, here it is:

[{tabs}] 
==== 
Local Couchbase Server::
+ 
-- 
[source,csharp]
----
using System;
using System.Threading.Tasks;
using Couchbase;

namespace examples
{
    class Program
    {
        static async Task Main(string[] args)
        {
            var cluster = await Cluster.ConnectAsync("couchbase://localhost", "username", "password");
            var bucket = await cluster.BucketAsync("bucket-name");
            var collection = bucket.DefaultCollection();

            var upsertResult = await collection.UpsertAsync("my-document-key", new { Name = "Ted", Age = 31 });
            var getResult = await collection.GetAsync("my-document-key");
            Console.WriteLine(getResult.ContentAs<dynamic>());

            var queryResult = await cluster.QueryAsync<dynamic>("select \"Hello World\" as greeting", new Couchbase.Query.QueryOptions());
            await foreach (var row in queryResult) {
                Console.WriteLine(row);
            }
        }
    }
}
----
--

Couchbase Cloud Sample::
+
--
If you are connecting to https://docs.couchbase.com/cloud/index.html[Couchbase Cloud], be sure to get the correct endpoint as well as user, password, and `couchbasecloudbucket` -- and see the <<cloud-connections, Cloud section>>, below.

[source,csharp]
----
include::devguide:example$dotnet/Cloud.cs[]
----
--
====


== Cloud Connections

For developing on Couchbase Cloud, if you are not working from the same _Availability Zone_, refer to the follorwing:

* Notes on xref:ref:client-settings.adoc#constrained-network-environments[Constrained Network Environments], 
* xref:project-docs:compatibility.adoc#network-requirements[Network Requirements], 
* If you have a consumer-grade router which has problems with DNS-SRV records review our xref:howtos:troubleshooting-cloud-connections.adoc#troubleshooting-host-not-found[Troubleshooting Guide].



== Additional Resources

The http://docs.couchbase.com/sdk-api/couchbase-net-client/[API reference] is generated for each release.
Older API references are linked from their respective sections in the xref:project-docs:sdk-release-notes.adoc[Release Notes].

xref:project-docs:migrating-sdk-code-to-3.n.adoc[The Migrating from SDK2 to 3 page] highlights the main differences to be aware of when migrating your code.
