= Install and Start Using the .NET SDK with Couchbase Server
:page-aliases: ROOT:getting-started,ROOT:start-using,ROOT:hello-couchbase,ROOT:start-using-sdk
:navtitle: Start Using the SDK

[abstract]
The Couchbase .NET SDK enables you to interact with a Couchbase Server cluster from the .NET Framework using C# and other .NET languages.
It offers both a traditional synchronous API and an asynchronous API based on the _Task-based Asynchronous Pattern (TAP)_.



The Couchbase .NET client allows applications to connect to the Couchbase Data Platform using any Common Language Runtime (CLR) language, including C#, F#, and VB.NET.
The SDK is written in C#, and some of its idiomatic patterns reflect that choice.
The .NET SDK 3.0 is a complete rewrite of the API, reducing the number of overloads to present a simplified surface area, and adding support for future Couchbase Server features like Collections and Scopes (available in Couchbase Server 6.5 as a xref:concept-docs:collections.adoc[developer preview]).
The API is now fully async.


== Installing the SDK

The Couchbase .NET SDK targets https://docs.microsoft.com/en-us/dotnet/standard/net-standard[.NET Standard 2.0], which in turn supports .NET Framework 4.6.2+ and .NET Core (eg netcoreapp) 2.1. The library is distributed in a number of ways:

|===
|Nuget |Nuget package host at https://www.nuget.org/packages/CouchbaseNetClient/[nuget.org] (_recommended_)
|Zip |Zip file with can be downloaded https://packages.couchbase.com/clients/net/3.0/Couchbase-Net-Client.3.0.0-beta2.zip[here]
|Build from Source |Build the library from source https://github.com/couchbase/couchbase-net-client/[here] (not officially supported)
|===

In VS Code, with the https://marketplace.visualstudio.com/items?itemName=jmrog.vscode-nuget-package-manager[NuGet Package Manager Extension], open the command palette and type "nuget", then "CouchbaseNetClient", and select the latest 3.0 version available.

== Hello Couchbase

Now you have the .NET client installed, open a fresh project in _VS Code_, and try out the following, which assumes a user named "username" with permissions to access the cluster, typically the "Application Access" role.

Of course, you will need to have a few using statements:
[source,csharp]
----
include::example$StartUsing.cs[tag=using,indent=0]
----

Then you can connect to the cluster:

[source,csharp]
----
include::example$StartUsing.cs[tag=connect,indent=0]
----

Couchbase uses xref:6.0@server:learn:security/roles.adoc[Role Based Access Control (RBAC)] to control access to resources.
If you're developing client code on the same VM or machine as the Couchbase Server, your URI can be _couchbase://localhost_.

Then open the bucket:
[source,csharp]
----
include::example$StartUsing.cs[tag=bucket,indent=0]
----

If you installed the travel sample data bucket, substitute _travel-sample_ for _bucket-name_.


The 3.0 SDK is ready for the introduction of xref:concept-docs:collections.adoc[Collections] in an upcoming release of the Couchbase Data Platform.
The latest release, Couchbase Server 6.5, brings a limited _Developer Preview_ of Collections, allowing Documents to be grouped by purpose or theme, according to specified _Scope_.
Here we will use the `DefaultCollection`, which covers the whole Bucket and _must be used when connecting to a 6.5 cluster or earlier_.

[source,csharp]
----
include::example$StartUsing.cs[tag=collection,indent=0]
----

KV Operations are described in detail on the xref:howtos:kv-operations.adoc[KV Operations page].
Now that you know the basics, you may wish to go straight to that page.
To get you started the following code creates a new document and then fetches it again, printing the result.

NOTE: This version of the 3.0 .NET Client is entirely asynchronous, following modern .NET development recommendations.

[source,csharp]
----
include::example$StartUsing.cs[tag=upsert-get,indent=0]
----

You can also perform a N1QL query at the cluster level:

[source,csharp]
----
include::example$StartUsing.cs[tag=n1ql-query,indent=0]
----

You can learn more about N1QL queries on the xref:howtos:n1ql-queries-with-sdk.adoc[Query page].
Other services (like analytics, search or views) work very similar to the two shown above.
Please refer to their respective documentation sections to learn more.

== Full Example

If you want to copy and paste to run the full example, here it is:

[source,csharp]
----
using System;
using System.Threading.Tasks;
using Couchbase;

namespace examples
{
    class Program
    {
        static async Task Main(string[] args)
        {
            await using var cluster = await Cluster.ConnectAsync("couchbase://localhost", "username", "password");
            var bucket = await cluster.BucketAsync("bucket-name");
            var collection = bucket.DefaultCollection();

            var upsertResult = await collection.UpsertAsync("my-document", new { Name = "Ted", Age = 31 });
            var getResult = await collection.GetAsync("my-document");
            Console.WriteLine(getResult.ContentAs<dynamic>());

            var queryResult = await cluster.QueryAsync<dynamic>("select \"Hello World\" as greeting", new Couchbase.Query.QueryOptions());
            await foreach (var row in queryResult) {
                Console.WriteLine(row);
            }
        }
    }
}

}
----


== Additional Resources

The API reference is generated for each release and can be found http://docs.couchbase.com/sdk-api/couchbase-net-client-3.0.0/[here].
Older API references are linked from their respective sections in the xref:project-docs:sdk-release-notes.adoc[Release Notes].

// xref:project-docs:migrating-sdk-code-to-3.n.adoc[The Migrating from SDK2 to 3 page] highlights the main differences to be aware of when migrating your code.

Couchbase welcomes community contributions to the .NET SDK.
The .NET SDK source code is available on https://github.com/couchbase/couchbase-net-client[GitHub].
