= Hello World
:page-aliases: ROOT:getting-started.adoc,ROOT:start-using.adoc,ROOT:hello-couchbase.adoc,ROOT:start-using-sdk.adoc
:page-toclevels: 3
:description: Install, connect, try. A quick start guide to get you up and running with Couchbase and the {name-sdk}.
:forum-link: https://forums.couchbase.com/c/net-sdk/6
:complete-code-include: include::devguide:example$dotnet/StartUsingCapella.cs[]
:page-partial:
:lang: csharp
// :example-source-lang: C#


// Note to editors
//
// This page pulls in content from
// https://github.com/couchbase/docs-sdk-common/blob/api/3.10/modules/shared/partials/start-using-sdk.adoc
//
// and code samples from
// https://github.com/couchbase/docs-sdk-dotnet/tree/release/3.10/modules/devguide/examples/dotnet
//
// It can be seen built at
// https://docs.couchbase.com/dotnet-sdk/3.10/hello-world/start-using-sdk.html


[abstract]
{description}



// intro
include::{version-common}@sdk:shared:partial$start-using-sdk.adoc[tag=intro]


.Creating a new database entry with the {name_platform} SDK, using `upsert()`
[source,{lang-code}]
----
include::devguide:example$dotnet/KvOperations.cs[tag=upsertwithdurability,indent=0]
----




// intro-upsert
include::{version-common}@sdk:shared:partial$start-using-sdk.adoc[tag=intro-upsert]


// TIP - DEE tutoral & Student record tutorial
// include::{version-common}@sdk:shared:partial$start-using-sdk.adoc[tag=other-tutorials]
// ^Uncomment this once the student record tutorial is ported.



== Before You Start


include::{version-common}@sdk:shared:partial$start-using-sdk.adoc[tag=before]



// Script the docs!
// Can any of the SDK installations be scripted?



=== Prerequisites

include::partial$supported.adoc[]
See the xref:project-docs:compatibility.adoc#dotnet-compatibility[Compatibility] section for more details.



// self-managed + Capella pre-reqs
include::{version-common}@sdk:shared:partial$start-using-sdk.adoc[tag=prereq]



== Installation

The quickest way to get up and running is with NuGet, from the Package Manager Console,  within your project:

. From the Visual Studio menu bar, click *Tools*.
. Select *NuGet Package Manager > Package Manager Console*.
. In the console, enter the package installation command:
 ** To install the latest version:

[source,console]
----
Install-Package CouchbaseNetClient
----

All other installation methods can be found in our xref:project-docs:sdk-full-installation.adoc[full installation guide].



=== IDE Plugins

include::{version-common}@sdk:shared:partial$start-using-sdk.adoc[tag=ide]


=== Grab the Code

include::{version-common}@sdk:shared:partial$start-using-sdk.adoc[tag=complete-code]


== Connect to your Database

Connect to your Couchbase Capella operational cluster (or your local Couchbase Cluster, if you are trying out self-managed Couchbase).


[tabs,sync-group-id="Couchbase Capella|Self-Managed Couchbase Server"]
==== 
Couchbase Capella::
+
--
[source,csharp]
----
include::devguide:example$dotnet/Cloud/Cloud.cs[tags=connect,indent=0]
----
--

Self-Managed Couchbase Server::
+
--
[source,csharp]
----
include::devguide:example$dotnet/StartUsing.cs[tag=connect,indent=0]
----
--

Cloud Native Gateway (CNG)::
+
--
include::{version-common}@sdk:shared:partial$start-using-sdk.adoc[tag=cng]

[source,csharp]
----
    var cluster = await Cluster.ConnectAsync(
        // Update these credentials for your Local Couchbase instance!
        "couchbase2://<your-ip-address>",
        "Administrator",
        "password");
----

Read more on the xref:howtos:managing-connections.adoc#cloud-native-gateway[Connections] page.
--
====

include::{version-common}@sdk:shared:partial$start-using-sdk.adoc[tag=deeper-conn]



=== Opening a Bucket

Following successful authentication, open the bucket with:
////
[source,csharp]
----
include::devguide:example$dotnet/StartUsing.cs[tag=bucket,indent=0]
----
////
[source,csharp]
----
include::devguide:example$dotnet/ClusterExample.cs[tag=waitUntilReady,indent=0]
----


////
client has not yet completed bootstrapping (connecting to the cluster, getting the configuration, connecting to the nodes).
////


`waitUntilReady` is an optional call,
but it is good practice to use it.
Opening resources such as buckets is asynchronous --
that is, the `cluster.bucket` call returns immediately and proceeds in the background.
`waitUntilReady` ensures that the bucket resource is fully loaded before proceeding.
If not present, then the first key-value (KV) operation on the bucket will wait for it to be ready.
// As with the earlier `Cluster.connect`, we use `.get` on the result here for simplicity.

*Collections* allow documents to be grouped by purpose or theme, according to a specified *scope* -- see data modeling, <<data-modeling,below>>.
Here we will use the `airport` collection within the `inventory` scope from `travel-sample` bucket as an example.

[source,csharp]
----
var scope = await bucket.ScopeAsync("inventory");
var collection = await scope.CollectionAsync("airport");
----


== Create, Read, Update, Delete

include::{version-common}@sdk:shared:partial$start-using-sdk.adoc[tag=crud]



////
=== JSON

We'll create a snippet of JSON to work with, using the client's own JSON library,
but you can read about the {name-sdk}'s support for other JSON libraries on the
xref:howtos:json.adoc[] page.

[source,java]
----
include::devguide:example$java/StartUsingCapella.java[tag=json,indent=0]
----
////


=== Insert (Create) and Upsert


xref:howtos:kv-operations.adoc[Data operations], like storing and retrieving documents, can be done using simple methods on the `Collection` class such as `Collection.InsertAsync()` and `Collection.UpsertAsync()`.
`insert` and `upsert` will both create a new document.
The difference between the two is that if a document with that key already exists, the `insert` operation will fail,
throwing a `DocumentExistsException` --
while the `upsert` operation will succeed, replacing the content.


.Insert
[source,csharp]
----
include::devguide:example$dotnet/KvOperations.cs[tag=insert,indent=0]
----


=== Get (Read)

The `get` method reads a document from a collection.
If the collection does not have a document with this ID, the `get` method also throws `DocumentNotFoundException`.

The following code snippet creates a new document in a custom scope and collection and then fetches it again, printing the result.

[source,csharp]
----
include::devguide:example$dotnet/StartUsing.cs[tag=upsert-get,indent=0]
----


=== Replace (Update) and Overloads

The replace method updates the value of an existing document.
Here we add a couple of useful options for expiry and timeout --
read more on our xref:howtos:kv-operations.adoc[using the Data Service] page.

[source,csharp]
----
include::devguide:example$dotnet/KvOperations.cs[tag=replacewithcas,indent=0]
----

CAUTION: When you replace a document, it's usually good practice to use xref:howtos:kv-operations.adoc#optimistic-locking[optimistic locking].
Otherwise, changes might get lost if two people change the same document at the same time.



=== Remove (Delete)

When removing a document, you will have the same concern for durability as with any additive modification to the Bucket:

.Remove (with options)
[source,csharp]
----
include::devguide:example$dotnet/KvOperations.cs[tag=remove,indent=0]
----

Like `Replace`, `Remove` also optionally takes the xref:howtos:kv-operations.adoc#what-is-cas[CAS value] if you want to make sure you are only removing the document if it hasn’t changed since you last fetched it.


== Data Modeling

include::{version-common}@sdk:shared:partial$start-using-sdk.adoc[tag=data-model]



== What Next?

////
Query and KV -
both
- but different emphasis on modelling objects....
////


include::{version-common}@sdk:shared:partial$start-using-sdk.adoc[tag=what-next]


