= Install and Start Using the .NET SDK with Couchbase Server
:navtitle: Start Using the SDK

[abstract]
The Couchbase .NET SDK enables you to interact with a Couchbase Server cluster from the .NET Framework using C#.
It offers both a traditional synchronous API and an asynchronous API based on the _Task-based Asynchronous Pattern (TAP)_.

WARNING: These pages cover the first _Developer Preview_ of the Couchbase .NET SDK -- 3.0 _alpha_.
As such they are likely to change without notice.
The _alpha_ code _should not_ be used in production.

== Installing the SDK

The Couchbase .NET SDK targets https://docs.microsoft.com/en-us/dotnet/standard/net-standard[.NET Standard 2.0], which in turn supports .NET Framework 4.6.2+ and .NET Core (eg netcoreapp). The library is distributed in a number of ways:

|===
|Nuget |Nuget package host at https://www.nuget.org/packages/CouchbaseNetClient/[nuget.org] (_recommended_)
|Zip |Zip file with can be downloaded [here]
|Build from Source |Build the library from source
|===

// VS Code stuff here

== Hello Couchbase

Now you have the .NET client installed grab the code from link:href://devguideexamples or open a fresh project in VS Code and try out the following:

[source,csharp]
----
var config = new Configuration()
    .WithServers("couchbase://10.112.180.101")
    .WithCredentials("username", "password")
    .WithBucket("defualt");
----

Couchbase uses xref:6.0@server:learn/security:roles.adoc[Role Based Access Control (RBAC)] to control access to resources.
Here we will use the _Full Admin_ role created during installation of the Couchbase Data Platform.
For production client code, you will want to use xref:howtos:managing-connections.adoc#rbac[more appropriate, restrictive settings], but here we want to get you up and running quickly.
If you're developing client code on the same VM or machine as the Couchbase Server, your URI can be _couchbase://localhost_.

[source,csharp]
----
var cluster = new Cluster(config);
----

[source,csharp]
----
var bucket = await cluster.Bucket("bucket-name");
----

If you installed the travel sample data bucket, substitute _travel-sample_ for _bucket-name_.

[source,csharp]
----
var collection = await bucket.DefaultCollection;
----

The 3.0 SDK is ready for the introduction of xref:#[Collections] in Cheshire Cat, the next release of the Couchbase Data Platform.
The latest release, Mad Hatter, brings a limited _Developer Preview_ of Collections, allowing Documents to be grouped by purpose or theme, according to specified _Scope_.
Here we will use the `DefaultCollection`, which covers the whole Bucket.

[source,csharp]
----
var upsertResult = await collection.Upsert("my-document", new {name = "mike"});
var getResult = await collection.Get("my-document");
----

KV Operations are described in detail on the xref:howtos:kv-operations.adoc[KV Operations page].
Now that you know the basics, you may wish to go straight to that page.
//
//
//
//
// -- or first see a complete worked example of using the Couchbase .NET client, our xref:3.0dp1@sample-application.adoc[Travel Sample Application].
//
//

NOTE: The _Developer Preview_ version of the 3.0 .NET Client is entirely asynchronous -- synchronous alternatives may be added in the future.

== Additional Resources

The API reference is generated for each release and can be found xref:http://docs.couchbase.com/sdk-api/couchbase-net-client-3.0.0dp1/[here].

// xref:project-docs:migrating-sdk-code-to-3.n.adoc[The Migrating from SDK2 to 3 page] highlights the main differences to be aware of when migrating your code.

Couchbase welcomes community contributions to the .NET SDK.
The .NET SDK source code is available on xref:https://github.com/couchbase/couchbase-net-client[GitHub].
