= Start Using the .NET SDK
:description: The Couchbase .NET SDK enables you to interact with a Couchbase Server cluster from .NET using C# and other .NET languages.
:page-aliases: ROOT:getting-started,ROOT:start-using,ROOT:hello-couchbase,ROOT:start-using-sdk
:page-toclevels: 2
:page-pagination: full
:page-topic-type: tutorial

include::project-docs:partial$attributes.adoc[]

[abstract]
{description}
It offers an asynchronous API based on the link:https://docs.microsoft.com/en-us/dotnet/standard/asynchronous-programming-patterns/task-based-asynchronous-pattern-tap[_Task-based Asynchronous Pattern (TAP)_].

The Couchbase .NET client allows applications to connect to Couchbase Server using any Common Language Runtime (CLR) language, including C#, F#, and VB.NET.
The SDK is written in C#, and some of its idiomatic patterns reflect that choice.

In this guide, you will learn:

* How to xref:connect[connect to Couchbase Capella or Couchbase Server].

* How to xref:add-and-retrieve-documents[add and retrieve Documents].

* How to xref:sql-lookup[lookup documents] with the {sqlpp_url}[{sqlpp} (formerly N1QL)] query language.

== Hello Couchbase

We will go through the code sample step by step, but for those in a hurry to see it, here it is:

[{tabs}]
====
Couchbase Capella Sample::
+
--
If you are connecting to https://docs.couchbase.com/cloud/index.html[Couchbase Capella], be sure to get the correct endpoint as well as user, password -- and see the <<cloud-connections, Cloud section>>, below.

[source,csharp]
----
include::devguide:example$dotnet/Cloud/Cloud.cs[tags=**]
----

The Couchbase Capella free trial version comes with the Travel Sample Bucket, and its Query indexes, loaded and ready.
--

Local Couchbase Server::
+
--
[source.try-it,csharp]
----
include::example$StartUsing.csx[tags=**]
----

As well as the .NET SDK (see below), and a running instance of Couchbase Server, you will need to load up the Travel Sample Bucket
using either the xref:7.1@server:manage:manage-settings/install-sample-buckets.adoc#install-sample-buckets-with-the-ui[Web interface]
or the xref:7.1@server:manage:manage-settings/install-sample-buckets.adoc#install-sample-buckets-with-the-cli[command line].
--
====


== Installing the SDK

include::partial$supported.adoc[]
See the xref:project-docs:compatibility.adoc#dotnet-compatibility[Compatibility] section for more details.

=== Quick Installation

The quickest way to get up and running is with NuGet, from the Package Manager Console,  within your project:

. From the Visual Studio menu bar, click *Tools*.
. Select *NuGet Package Manager > Package Manager Console*.
. In the console, enter the package installation command:
 ** To install the latest version:

[source,console]
----
Install-Package CouchbaseNetClient
----

All other installation methods can be found in our xref:project-docs:sdk-full-installation.adoc[full installation guide].

== Prerequisites

The following code samples assume:

[{tabs}]
====
Couchbase Capella::
+
--
* You have signed up to https://cloud.couchbase.com/sign-up[Couchbase Capella].

* You have created your own bucket, or loaded the Travel Sample dataset.
Note, the Travel Sample dataset is installed automatically by the Capella free trial.

* A user is created with permissions to access the cluster (at least Application Access permissions).
See the xref:cloud:get-started:cluster-and-data.adoc#credentials[Capella connection page] for more details.

IMPORTANT: Couchbase Capella uses xref:cloud:organizations:organization-projects-overview.adoc[Roles] to control user access to database resources.
For the purposes of this guide, you can use the *Organization Owner* role automatically assigned to your account during installation of the Capella cluster.
In a production scenario, we strongly recommend setting up users with more granular access roles as a best practice.
--

Local Couchbase Server::
+
--
* xref:{version-server}@server:getting-started/do-a-quick-install.adoc[Couchbase Server] is installed and accessible locally.

* You have created your own bucket, or loaded the Travel Sample dataset using the xref:{version-server}@server:manage:manage-settings/install-sample-buckets.adoc#install-sample-buckets-with-the-ui[Web interface].

* A user is created with permissions to access your cluster (at least Application Access permissions).
See xref:{version-server}@server:manage:manage-security/manage-users-and-roles.adoc[Manage Users, Groups and Roles] for more details.

IMPORTANT: Couchbase Server uses xref:{version-server}@server:learn:security/roles.adoc[Role Based Access Control (RBAC)] to control access to resources.
In this guide we suggest using the *Full Admin* role created during setup of your local Couchbase Server cluster.
For production client code, you will want to use more appropriate, restrictive settings.
--
====

== Step by Step

Start a new console project (in Visual Studio or VS Code, etc). 
Go to our xref:platform-help.adoc[Platform Introduction] if you don't already have an editor or IDE setup for working in .NET -- e.g. you are evaluating the .NET SDK, but .NET is not your normal platform.

Firstly, you will need to have a few `using` statements at the top of *Program.cs* in your console program:

[source,csharp]
----
include::example$StartUsing.csx[tag=using,indent=0]
----

=== Connect

Connect to your cluster by calling the `Cluster.ConnectAsync()` method and pass it your connection details.
The basic connection details that you’ll need are given below -- for more background information, see xref:howtos:managing-connections.adoc[].

[{tabs}] 
====
Capella Connection::
+
--
From version 3.3, the .NET SDK includes Capella's standard certificates by default, so you do not need to additional configuration.
You do need to enable TLS, which can be done by simply using `couchbases://` in the connection string as in this example.

[source,csharp]
----
include::devguide:example$dotnet/Cloud/Cloud.csx[tag=connect,indent=0]
----

When accessing Capella from a different Wide Area Network or Availability Zone, you may experience latency issues with the default connection settings.
SDK 3.4 introduces a `wan-development` Configuration Profile, which provides pre-configured timeout settings suitable for working in high latency environments.
Basic usage is shown in the example above, but if you want to learn more see xref:ref:client-settings.adoc#constrained-network-environments[Constrained Network Environments].

CAUTION: The Configuration Profiles feature is currently a xref:dotnet-sdk:project-docs:compatibility.adoc#interface-stability[Volatile API] and may be subject to change.
--

Local Server Connection::
+
--
[source,csharp]
----
include::example$StartUsing.csx[tag=connect,indent=0]
----

For developing locally on the same machine as Couchbase Server, your URI can be `couchbase://localhost`.
For production deployments, you will want to use a secure server, with `couchbases://`.
--
====

Following successful authentication, add this code snippet to access your `Bucket`:

[source,csharp]
----
include::example$StartUsing.csx[tag=bucket,indent=0]
----

=== Add and Retrieve Documents

Collections allow Documents to be grouped by purpose or theme, according to specified _Scope_.
Our Travel Sample bucket has separate scopes for inventory (flights, etc.), and for tenants (different travel agents).

[source,csharp]
----
include::devguide:example$dotnet/Cloud/Cloud.cs[tag=collection,indent=0]
----

xref:howtos:kv-operations.adoc[Data operations], like storing and retrieving documents, can be done using simple methods on the `Collection` class such as `Collection.GetAsync()` and `Collection.UpsertAsync()`.

To get you started the following code creates a new document in a custom scope and collection and then fetches it again, printing the result.

[source,csharp]
----
include::example$StartUsing.csx[tag=upsert-get,indent=0]
----

=== {sqlpp} Lookup

Couchbase {sqlpp} queries can be performed at the `Cluster` or `Scope` level by invoking `Cluster.QueryAsync()` or `Scope.QueryAsync()`.

Cluster level queries require you to specify the fully qualified keyspace each time (e.g. `travel-sample.inventory.airline`).
However, with a Scope level query you only need to specify the Collection name -- which in this case is `airline`:

[source,csharp]
----
include::devguide:example$dotnet/Cloud/Cloud.cs[tag=n1ql-query,indent=0]
----

You can learn more about {sqlpp} queries on the xref:howtos:n1ql-queries-with-sdk.adoc[Query page].

== Next Steps

Now you're up and running, try one of the following:

* Our xref:hello-world:sample-application.adoc[Travel Sample Application] demonstrates all the basics you need to know;
* Explore xref:howtos:kv-operations.adoc[Key Value Operations] against a document database;
* Or xref:howtos:n1ql-queries-with-sdk.adoc[Query] with our SQL-based {sqlpp} query language;
// * Try longer-running queries with our xref:howtos:analytics-using-sdk.adoc[Analytics Service];
// * A xref:howtos:full-text-searching-with-sdk.adoc[Full Text Search];
* Or read up on xref:concept-docs:data-services.adoc[which service fits your use case].


=== Additional Resources

The https://docs.couchbase.com/sdk-api/couchbase-net-client/api/index.html[API reference] is generated for each release.
Older API references are linked from their respective sections in the xref:project-docs:sdk-release-notes.adoc[Release Notes].

xref:project-docs:migrating-sdk-code-to-3.n.adoc[The Migrating from SDK2 to 3 page] highlights the main differences to be aware of when migrating your code from our earlier 2.x .NET SDK.

// Couchbase welcomes community contributions to the .NET SDK.
// The .NET SDK source code is available on https://github.com/couchbase/couchbase-net-client[GitHub].

=== Troubleshooting

* Couchbase Server is designed to work in the same WAN or availability zone as the client application.
If you're running the SDK on your laptop against a Capella cluster, see further information on:
** Notes on xref:ref:client-settings.adoc#constrained-network-environments[Constrained Network Environments].
** xref:project-docs:compatibility.adoc#network-requirements[Network Requirements].
** If you have a consumer-grade router which has problems with DNS-SRV records review our xref:howtos:troubleshooting-cloud-connections.adoc#troubleshooting-host-not-found[Troubleshooting Guide].
* Our https://forums.couchbase.com/c/net-sdk/6[community forum] is a great source of help.
